// Danish translations for the character sheet's "Features & Traits" content:
// class features, species traits, feat descriptions and subclass descriptions.

export const FEATURE_DA={
  "Action Surge Lvl2":"Ekstra handling (niv 2)",
  "Arcane Recovery 1/long rest":"Arkan genopladning 1/lang hvile",
  "Aura of Protection Lvl6":"Beskyttelsesaura (niv 6)",
  "Bardic Inspiration CHA mod/long rest":"Bardisk inspiration CHA-mod/lang hvile",
  "Blessed Strikes Lvl7":"Velsignede slag (niv 7)",
  "Channel Divinity":"Kanalisér guddom",
  "Cunning Action Lvl2":"Snu handling (niv 2)",
  "Danger Sense Lvl2":"Faresans (niv 2)",
  "Deft Explorer Lvl1":"Behændig opdager (niv 1)",
  "Divine Order Lvl1":"Guddommelig orden (niv 1)",
  "Divine Smite Lvl2":"Guddommeligt smæk (niv 2)",
  "Druidic language":"Druidesprog",
  "Eldritch Invocations Lvl1":"Eldritch-besværgelser (niv 1)",
  "Expertise Lvl1":"Ekspertise (niv 1)",
  "Extra Attack Lvl5":"Ekstra angreb (niv 5)",
  "Favored Enemy Lvl1":"Foretrukken fjende (niv 1)",
  "Fighting Style Lvl1":"Kampstil (niv 1)",
  "Font of Magic Lvl2":"Magikilde (niv 2)",
  "Innate Sorcery Lvl1":"Medfødt trolddom (niv 1)",
  "Jack of All Trades Lvl2":"Altmuligmand (niv 2)",
  "Lay on Hands 5x level HP":"Håndspålæggelse 5x niveau HP",
  "Magical Cunning Lvl2":"Magisk snuhed (niv 2)",
  "Martial Arts Lvl1":"Kampkunst (niv 1)",
  "Metamagic Lvl3":"Metamagi (niv 3)",
  "Monks Focus Lvl2":"Munkens fokus (niv 2)",
  "Pact Boon Lvl3":"Pagtsgave (niv 3)",
  "Pact Magic short rest recharge":"Pagtmagi genoplades ved kort hvile",
  "Primal Order Lvl1":"Oprindelig orden (niv 1)",
  "Rage (2/long rest)":"Raseri (2/lang hvile)",
  "Reckless Attack Lvl2":"Hensynsløst angreb (niv 2)",
  "Second Wind 1/short rest":"Andet stød 1/kort hvile",
  "Sneak Attack 1d6 per 2 levels":"Snigangreb 1d6 pr. 2 niveauer",
  "Spell Mastery Lvl18":"Spell-mesterskab (niv 18)",
  "Spellcasting CHA":"Magi (CHA)",
  "Spellcasting CHA Lvl1":"Magi CHA (niv 1)",
  "Spellcasting INT prepare INT+level":"Magi INT, forbered INT+niveau",
  "Spellcasting WIS Lvl1":"Magi WIS (niv 1)",
  "Stunning Strike Lvl5":"Bedøvende slag (niv 5)",
  "Subclass Lvl3":"Underklasse (niv 3)",
  "Thieves Cant":"Tyvesprog",
  "Unarmored Defense AC=10+DEX+CON":"Rustningsfrit forsvar AC=10+DEX+CON",
  "Unarmored Defense AC=10+DEX+WIS":"Rustningsfrit forsvar AC=10+DEX+WIS",
  "Uncanny Dodge Lvl5":"Uhyggelig undvigelse (niv 5)",
  "Weapon Mastery x2":"Våbenmesterskab x2",
  "Weapon Mastery x3":"Våbenmesterskab x3",
  "Wild Shape Lvl2":"Vildskikkelse (niv 2)",
};

export const TRAIT_DA={
  "Adrenaline Rush":"Adrenalinsus",
  "Brave":"Modig",
  "Breath Weapon":"Åndevåben",
  "Celestial Revelation":"Himmelsk åbenbaring",
  "Damage Resistance":"Skademodstand",
  "Darkvision 120 ft":"Mørkesyn 120 ft",
  "Darkvision 60 ft":"Mørkesyn 60 ft",
  "Draconic Ancestry":"Dragisk afstamning",
  "Dwarven Resilience":"Dværge-hårdførhed",
  "Dwarven Toughness":"Dværge-sejhed",
  "Elven Lineage":"Elverslægt",
  "Fey Ancestry":"Fe-afstamning",
  "Fiendish Legacy":"Djævelsk arv",
  "Giant Ancestry":"Kæmpe-afstamning",
  "Gnomish Cunning":"Gnom-snuhed",
  "Gnomish Lineage":"Gnomslægt",
  "Halfling Nimbleness":"Halfling-adræthed",
  "Healing Hands":"Helbredende hænder",
  "Keen Senses":"Skarpe sanser",
  "Large Form":"Stor form",
  "Light Bearer":"Lysbærer",
  "Lucky":"Heldig",
  "Naturally Stealthy":"Naturligt snigende",
  "Otherworldly Presence":"Overjordisk nærvær",
  "Powerful Build":"Kraftig bygning",
  "Relentless Endurance":"Ubønhørlig udholdenhed",
  "Resourceful":"Opfindsom",
  "Skillful":"Dygtig",
  "Stonecunning":"Stenkløgt",
  "Tool Proficiency":"Tool Proficiency",
  "Trance":"Trance",
  "Versatile":"Alsidig",
};

export const FEATDESC_DA={
  "Alert":"Læg Proficiency Bonus til Initiativ. Kan ikke overraskes når du er ved bevidsthed.",
  "Crafter":"Proficiency i 3 håndværksværktøjer. Håndværk med 20% rabat.",
  "Healer":"Healer-kit: genopret 1d6+4+HD HP én gang pr. væsen pr. hvile.",
  "Lucky":"3 heldpoint pr. lang hvile. Kast en d20 om og vælg resultatet.",
  "Magic Initiate":"Lær 2 cantrips og 1 spell af 1. niveau fra en vilkårlig klasse.",
  "Savage Attacker":"Én gang pr. tur: kast nærkampsskade om og vælg resultatet.",
  "Skilled":"Få proficiency i 3 valgfrie færdigheder eller værktøjer.",
  "Tavern Brawler":"Ubevæbnede slag bruger d4+STR. Bonus-handling: gribe efter træf.",
  "Tough":"Maks HP +2 pr. niveau (med tilbagevirkende kraft).",
  "War Caster":"Fordel på CON concentration saves. Cast spells som lejlighedsangreb.",
  "Great Weapon Master":"Ved kritisk træf eller drab med tungt våben: bonusangreb. Valg: -5/+10.",
  "Mobile":"Fart +10 ft. Dash gennem vanskeligt terræn. Intet lejlighedsangreb fra dem du angriber.",
  "Resilient":"Proficiency i én saving throw. +1 til den evne.",
  "Sentinel":"Lejlighedsangreb sætter fart til 0. Lejlighedsangreb ved Disengage. Reaktion når en allieret angribes.",
  "Sharpshooter":"Ingen langdistancestraf. Ignorér halv/3/4 dækning. Valg: -5/+10.",
  "Inspiring Leader":"10-min tale: op til 6 allierede får midlertidige HP = niveau+CHA.",
  "Skulker":"Skjul dig når du er let sløret. Et forfejlet afstandsangreb afslører dig ikke.",
  "Durable":"+1 CON. Min HP fra livsterninger = 2x CON-mod.",
  "Spell Sniper":"Fordobl rækkevidde på angrebsspells. Ignorér halv og 3/4 dækning.",
  "Polearm Master":"Bonusangreb med skaftenden (1d4). Lejlighedsangreb når fjende træder ind i rækkevidde.",
  "Defense":"Kampstil: +1 AC mens du bærer rustning.",
  "Dueling":"Kampstil: +2 skade med ét nærkampsvåben.",
  "Two-Weapon Fighting":"Kampstil: læg evne-mod til skade med bihånds-våbnet.",
  "Archery":"Kampstil: +2 til afstandsangreb.",
  "Protection":"Kampstil: reaktion for at give ulempe på angreb mod allieret (skjold).",
  "Blind Fighting":"Kampstil: Blindsyn 10 ft.",
  "Elven Accuracy":"(Elf) +1 DEX/INT/WIS/CHA. Kast tre terninger ved fordel.",
  "Fey Teleportation":"(Elf) +1 INT/CHA. Tal Sylvan. 1/kort hvile: Misty Step.",
  "Wood Elf Magic":"(Skovelf) Longstrider, Pass without Trace, én druide-cantrip.",
  "High Elf Cantrip":"(Højelf) Én wizard-cantrip (INT).",
  "Dwarven Fortitude":"(Dværg) +1 CON. Dodge-handling: brug 1 HD til at heale.",
  "Orcish Fury":"(Ork) +1 STR/CON. Ekstra skadeterning på våbenangreb.",
  "Bountiful Luck":"(Halfling) Reaktion: giv allieret Lucky-omkast på en 1'er.",
  "Second Chance":"(Halfling) +1 DEX/CON/CHA. Reaktion: tving et omkast når du angribes.",
  "Squat Nimbleness":"(Lille) +1 STR/DEX. Fart +5. Bevæg dig gennem større væsener.",
  "Hunter":"(Ranger) Colossus Slayer, Giant Killer eller Horde Breaker.",
  "Dragon Fear":"(Dragonborn) +1 STR/CON/CHA. Ånd frygt i stedet for energi.",
  "Dragon Hide":"(Dragonborn) +1 STR/CON/CHA. Naturlig AC 13+DEX, kløangreb.",
  "Fade Away":"(Gnom) +1 INT/DEX. Reaktion: bliv usynlig når du tager skade.",
  "Flames of Phlegethos":"(Tiefling) +1 INT/CHA. Kast ildskade om, ildskjolds-aura.",
  "Infernal Constitution":"(Tiefling) +1 CON. Modstand mod kulde/gift, fordel på poison saves.",
  "Musician":"Proficiency med 3 instrumenter. Spil efter en hvile: allierede får Heroisk inspiration.",
};

// Short description of what each class feature does. Keyed by the English feature string. [en, da].
// Canon D&D keywords (proficiency, saves, spell slots, advantage) kept English in the Danish text too.
export const FEATURE_DESC={
  "Action Surge Lvl2":["Take one extra action on your turn, once per rest.","Tag én ekstra handling på din tur, én gang pr. hvile."],
  "Arcane Recovery 1/long rest":["Recover some spell slots on a short rest, once a day.","Få nogle spell slots tilbage på en kort hvile, én gang om dagen."],
  "Aura of Protection Lvl6":["You and nearby allies add your CHA to saving throws.","Du og nære allierede lægger din CHA til saving throws."],
  "Bardic Inspiration CHA mod/long rest":["Give an ally a bonus die to add to a roll.","Giv en allieret en bonus-terning til at lægge til et slag."],
  "Blessed Strikes Lvl7":["Add extra radiant or necrotic damage to your attacks.","Tilføj ekstra strålende eller nekrotisk skade til dine angreb."],
  "Channel Divinity":["Channel divine energy for powerful special effects.","Kanalisér guddommelig energi til stærke særlige effekter."],
  "Cunning Action Lvl2":["Dash, Disengage or Hide as a bonus action.","Dash, Disengage eller Hide som en bonus-handling."],
  "Danger Sense Lvl2":["Advantage on DEX saves against effects you can see.","Fordel på DEX saves mod effekter du kan se."],
  "Deft Explorer Lvl1":["Expertise in a skill plus extra languages.","Expertise i en færdighed plus ekstra sprog."],
  "Divine Order Lvl1":["Choose Protector (martial) or Thaumaturge (extra cantrip).","Vælg Protector (kamp) eller Thaumaturge (ekstra cantrip)."],
  "Divine Smite Lvl2":["Spend a spell slot for extra radiant damage on a hit.","Brug et spell slot for ekstra strålende skade ved træf."],
  "Druidic language":["You know the secret language of druids.","Du kan druidernes hemmelige sprog."],
  "Eldritch Invocations Lvl1":["Special magical abilities you pick and can swap.","Særlige magiske evner du vælger og kan bytte."],
  "Expertise Lvl1":["Double your proficiency bonus in chosen skills.","Fordobl din proficiency bonus i valgte færdigheder."],
  "Extra Attack Lvl5":["Attack twice when you take the Attack action.","Angrib to gange når du tager Attack-handlingen."],
  "Favored Enemy Lvl1":["Always have Hunter's Mark ready to track prey.","Har altid Hunter's Mark klar til at spore bytte."],
  "Fighting Style Lvl1":["A combat specialty like Archery or Defense.","En kamp-specialitet som Archery eller Defense."],
  "Font of Magic Lvl2":["Sorcery Points to make or convert spell slots.","Sorcery Points til at lave eller omdanne spell slots."],
  "Innate Sorcery Lvl1":["Boost your spells' power for a short burst.","Boost dine spells' styrke i et kort stød."],
  "Jack of All Trades Lvl2":["Add half your proficiency to non-proficient checks.","Læg halv proficiency til tjek du ikke er proficient i."],
  "Lay on Hands 5x level HP":["A pool of healing you touch into yourself or allies.","En pulje af healing du giver dig selv eller allierede ved berøring."],
  "Magical Cunning Lvl2":["Regain some Pact Magic spell slots once per long rest.","Få nogle Pact Magic-spell slots tilbage én gang pr. lang hvile."],
  "Martial Arts Lvl1":["Unarmed strikes and monk weapons scale with a die.","Ubevæbnede slag og munkevåben skalerer med en terning."],
  "Metamagic Lvl3":["Bend your spells: twin, quicken, subtle and more.","Bøj dine spells: twin, quicken, subtle m.m."],
  "Monks Focus Lvl2":["Focus Points power Flurry, Patient Defense and Step of the Wind.","Focus Points driver Flurry, Patient Defense og Step of the Wind."],
  "Pact Boon Lvl3":["A gift from your patron: Blade, Chain, Tome or Talisman.","En gave fra din patron: Blade, Chain, Tome eller Talisman."],
  "Pact Magic short rest recharge":["Your spell slots return after a short rest.","Dine spell slots vender tilbage efter en kort hvile."],
  "Primal Order Lvl1":["Choose Magician (extra cantrip) or Warden (martial).","Vælg Magician (ekstra cantrip) eller Warden (kamp)."],
  "Rage (2/long rest)":["Enter a fury: bonus damage and damage resistance.","Gå i raseri: bonus-skade og skademodstand."],
  "Reckless Attack Lvl2":["Attack with advantage, but enemies hit you more easily.","Angrib med fordel, men fjender rammer dig lettere."],
  "Second Wind 1/short rest":["Heal yourself as a bonus action, once per rest.","Heal dig selv som bonus-handling, én gang pr. hvile."],
  "Sneak Attack 1d6 per 2 levels":["Bonus damage when you have advantage or an ally is near.","Bonus-skade når du har fordel eller en allieret er nær."],
  "Spell Mastery Lvl18":["Cast chosen 1st/2nd-level spells at will.","Cast valgte 1./2.-niveau spells frit."],
  "Spellcasting CHA":["You cast spells using Charisma.","Du caster spells med Charisma."],
  "Spellcasting CHA Lvl1":["You cast spells using Charisma.","Du caster spells med Charisma."],
  "Spellcasting INT prepare INT+level":["Prepare a fresh set of Wizard spells each day.","Forbered et nyt sæt Wizard-spells hver dag."],
  "Spellcasting WIS Lvl1":["You cast spells using Wisdom.","Du caster spells med Wisdom."],
  "Stunning Strike Lvl5":["Spend Focus to try to stun a creature you hit.","Brug Focus for at forsøge at stunne et væsen du rammer."],
  "Subclass Lvl3":["Choose a subclass that shapes your character.","Vælg en underklasse der former din karakter."],
  "Thieves Cant":["A secret code of rogues and criminals.","En hemmelig kode blandt tyve og kriminelle."],
  "Unarmored Defense AC=10+DEX+CON":["Your AC is 10 + DEX + CON while wearing no armor.","Din AC er 10 + DEX + CON når du ikke bærer rustning."],
  "Unarmored Defense AC=10+DEX+WIS":["Your AC is 10 + DEX + WIS while wearing no armor.","Din AC er 10 + DEX + WIS når du ikke bærer rustning."],
  "Uncanny Dodge Lvl5":["Halve the damage from one attack as a reaction.","Halvér skaden fra ét angreb som en reaktion."],
  "Weapon Mastery x2":["Use the mastery property of 2 weapons.","Brug mastery-egenskaben på 2 våben."],
  "Weapon Mastery x3":["Use the mastery property of 3 weapons.","Brug mastery-egenskaben på 3 våben."],
  "Wild Shape Lvl2":["Transform into beasts you have learned.","Forvandl til dyr du har lært."],
};

export const SUBCLASS_DESC_DA={
  // Barbarian
  "Path of the Berserker":"Frenzy for ekstra angreb og frygt.",
  "Path of the Wild Heart":"Dyreånd-kræfter mens du raser.",
  "Path of the World Tree":"Livgivende vitalitet og gren-teleports.",
  "Path of the Zealot":"Guddommeligt raseri; svær at dræbe.",
  // Bard
  "College of Dance":"Adræt rustningsfrit forsvar og mobil inspiration.",
  "College of Glamour":"Fe-charme og fængslende optræden.",
  "College of Lore":"Ekstra færdigheder og Cutting Words.",
  "College of Valor":"Rustning, våben og kamp-inspiration.",
  // Cleric
  "Life Domain":"Den bedste healing i spillet.",
  "Light Domain":"Strålende ild og Warding Flare.",
  "Trickery Domain":"Illusioner, snig og dobbeltgængere.",
  "War Domain":"Våbendygtighed og krigs-velsignelser.",
  // Druid
  "Circle of the Land":"Bonus-spells fra valgt terræn.",
  "Circle of the Moon":"Stærke Wild Shape-kampformer.",
  "Circle of the Sea":"Storm, bølger og havets raseri.",
  "Circle of the Stars":"Stjernebilled-former.",
  // Fighter
  "Battle Master":"Taktiske manøvrer med superioritetsterninger.",
  "Champion":"Kritiske træf på 19-20.",
  "Eldritch Knight":"Wizard-spells plus våben.",
  "Psi Warrior":"Telekinetiske psioniske slag og skjolde.",
  // Monk
  "Warrior of Mercy":"Helbredende hænder eller skadende berøring.",
  "Warrior of Shadow":"Mørke, snig og skygge-teleports.",
  "Warrior of the Elements":"Elementinfunderede slag.",
  "Warrior of the Open Hand":"Klassisk kampkunst-mester.",
  // Paladin
  "Oath of Devotion":"Beskyttelse, ærlighed og helligt våben.",
  "Oath of Glory":"Atletisk fortræffelighed og heltemod.",
  "Oath of the Ancients":"Naturmagi og fe-lys.",
  "Oath of Vengeance":"Ubønhørlig jæger af ugerningsmænd.",
  // Ranger
  "Beast Master":"En loyal dyrekammerat kæmper med dig.",
  "Fey Wanderer":"Fe-charme og sindsbeskyttelse.",
  "Gloom Stalker":"Dødbringende baghold i mørke.",
  "Hunter":"Colossus Slayer og monster-dræbertaktik.",
  // Rogue
  "Arcane Trickster":"Snigende wizard-spells og Mage Hand-tricks.",
  "Assassin":"Dødbringende slag i overraskelsesrunden.",
  "Soulknife":"Psykiske blade og telepati.",
  "Thief":"Fast Hands og suveræn klatring.",
  // Sorcerer
  "Aberrant Sorcery":"Psioniske sindskræfter.",
  "Clockwork Sorcery":"Orden, balance og genoprettede kast.",
  "Draconic Sorcery":"Drage-hårdførhed og elementkraft.",
  "Wild Magic Sorcery":"Kaotiske magiske udladninger.",
  // Warlock
  "Archfey Patron":"Fe-teleports og forheksende magi.",
  "Celestial Patron":"Helbredende lys fra oven.",
  "Fiend Patron":"Ild, midlertidige HP og mørke aftaler.",
  "Great Old One Patron":"Psykiske hvisken og telepati.",
  // Wizard
  "Abjurer":"Beskyttende Arcane Ward opsuger skade.",
  "Diviner":"Portent: forudse og erstat terningkast.",
  "Evoker":"Form dine besværgelser uden om allierede.",
  "Illusionist":"Mester i forbedrede illusioner.",
};
