// Danish translations for the character sheet's "Features & Traits" content:
// class features, species traits, feat descriptions and subclass descriptions.

export const FEATURE_DA={
  "Action Surge Lvl2":"Ekstra handling (niv 2)",
  "Arcane Recovery 1/long rest":"Arkan genopladning 1/Long Rest",
  "Aura of Protection Lvl6":"Beskyttelsesaura (niv 6)",
  "Bardic Inspiration CHA mod/long rest":"Bardisk inspiration CHA-mod/Long Rest",
  "Blessed Strikes Lvl7":"Velsignede slag (niv 7)",
  "Channel Divinity":"Kanalisér guddom",
  "Cunning Action Lvl2":"Snu handling (niv 2)",
  "Danger Sense Lvl2":"Faresans (niv 2)",
  "Primal Knowledge Lvl3":"Primal viden (niv 3)",
  "Deft Explorer Lvl1":"Behændig opdager (niv 1)",
  "Divine Order Lvl1":"Guddommelig orden (niv 1)",
  "Divine Smite Lvl2":"Guddommeligt smæk (niv 2)",
  "Druidic language":"Druidesprog",
  "Eldritch Invocations Lvl1":"Eldritch-besværgelser (niv 1)",
  "Expertise Lvl1":"Ekspertise (niv 1)",
  "Extra Attack Lvl5":"Ekstra angreb (niv 5)",
  "Favored Enemy Lvl1":"Foretrukken fjende (niv 1)",
  "Fighting Style Lvl1":"Kampstil (niv 1)",
  "Font of Magic Lvl2":"Magikilde (niv 2)",
  "Innate Sorcery Lvl1":"Medfødt trolddom (niv 1)",
  "Jack of All Trades Lvl2":"Altmuligmand (niv 2)",
  "Lay on Hands 5x level HP":"Håndspålæggelse 5x niveau HP",
  "Magical Cunning Lvl2":"Magisk snuhed (niv 2)",
  "Martial Arts Lvl1":"Kampkunst (niv 1)",
  "Metamagic Lvl3":"Metamagi (niv 3)",
  "Monks Focus Lvl2":"Munkens fokus (niv 2)",
  "Pact Boon Lvl3":"Pagtsgave (niv 3)",
  "Pact Magic short rest recharge":"Pagtmagi genoplades ved Short Rest",
  "Primal Order Lvl1":"Oprindelig orden (niv 1)",
  "Rage (2/long rest)":"Raseri (2/Long Rest)",
  "Reckless Attack Lvl2":"Hensynsløst angreb (niv 2)",
  "Second Wind Lvl1":"Andet stød (niv 1)",
  "Sneak Attack 1d6 per 2 levels":"Snigangreb 1d6 pr. 2 niveauer",
  "Spell Mastery Lvl18":"Spell-mesterskab (niv 18)",
  "Spellcasting CHA":"Magi (CHA)",
  "Spellcasting CHA Lvl1":"Magi CHA (niv 1)",
  "Spellcasting INT prepare INT+level":"Magi INT, forbered INT+niveau",
  "Spellcasting WIS Lvl1":"Magi WIS (niv 1)",
  "Stunning Strike Lvl5":"Bedøvende slag (niv 5)",
  "Subclass Lvl3":"Underklasse (niv 3)",
  "Thieves Cant":"Tyvesprog",
  "Unarmored Defense AC=10+DEX+CON":"Rustningsfrit forsvar AC=10+DEX+CON",
  "Unarmored Defense AC=10+DEX+WIS":"Rustningsfrit forsvar AC=10+DEX+WIS",
  "Uncanny Dodge Lvl5":"Uhyggelig undvigelse (niv 5)",
  "Weapon Mastery x2":"Våbenmesterskab x2",
  "Weapon Mastery x3":"Våbenmesterskab x3",
  "Wild Shape Lvl2":"Vildskikkelse (niv 2)",
};

export const TRAIT_DA={
  "Adrenaline Rush":"Adrenalinsus",
  "Brave":"Modig",
  "Breath Weapon":"Åndevåben",
  "Celestial Resistance":"Himmelsk modstand",
  "Celestial Revelation":"Himmelsk åbenbaring",
  "Damage Resistance":"Skademodstand",
  "Darkvision 120 ft":"Mørkesyn 120 ft",
  "Darkvision 60 ft":"Mørkesyn 60 ft",
  "Draconic Ancestry":"Dragisk afstamning",
  "Draconic Flight":"Dragisk flugt",
  "Dwarven Resilience":"Dværge-hårdførhed",
  "Dwarven Toughness":"Dværge-sejhed",
  "Elven Lineage":"Elverslægt",
  "Fey Ancestry":"Fe-afstamning",
  "Fiendish Legacy":"Djævelsk arv",
  "Giant Ancestry":"Kæmpe-afstamning",
  "Gnomish Cunning":"Gnom-snuhed",
  "Gnomish Lineage":"Gnomslægt",
  "Halfling Nimbleness":"Halfling-adræthed",
  "Healing Hands":"Helbredende hænder",
  "Keen Senses":"Skarpe sanser",
  "Large Form":"Stor form",
  "Light Bearer":"Lysbærer",
  "Luck":"Held",
  "Naturally Stealthy":"Naturligt snigende",
  "Otherworldly Presence":"Overjordisk nærvær",
  "Powerful Build":"Kraftig bygning",
  "Relentless Endurance":"Ubønhørlig udholdenhed",
  "Resourceful":"Opfindsom",
  "Skillful":"Dygtig",
  "Stonecunning":"Stenkløgt",
  "Trance":"Trance",
  "Versatile":"Alsidig",
};

// One-line description of each species trait, verified against the 2024 PHB (p.186-197). [en, da].
export const TRAIT_DESC={
  "Adrenaline Rush":["Bonus Action: Dash and gain temp HP = Prof. Bonus. Uses = Prof. Bonus per Short/Long Rest.","Bonus-handling: Dash og få midlertidige HP = Prof. Bonus. Antal brug = Prof. Bonus pr. Short/Long Rest."],
  "Brave":["Advantage on saving throws to avoid or end the Frightened condition.","Fordel på saving throws for at undgå eller afslutte Frightened."],
  "Breath Weapon":["Replace an attack with a 15-ft cone or 30-ft line; DEX save or take damage of your Draconic Ancestry's type (scales with level).","Erstat et angreb med en 15 ft kegle eller 30 ft linje; DEX save eller tag skade af typen fra din Draconic Ancestry (skalerer med niveau)."],
  "Celestial Resistance":["Resistance to Necrotic and Radiant damage.","Modstand mod Necrotic- og Radiant-skade."],
  "Celestial Revelation":["Lvl 3: Bonus Action to transform (Heavenly Wings, Inner Radiance or Necrotic Shroud) for 1 minute, once per Long Rest.","Niv. 3: Bonus-handling til at transformere (Heavenly Wings, Inner Radiance eller Necrotic Shroud) i 1 minut, én gang pr. Long Rest."],
  "Damage Resistance":["Resistance to the damage type determined by your Draconic Ancestry.","Modstand mod skadetypen bestemt af din Draconic Ancestry."],
  "Darkvision 120 ft":["See in dim and dark light within 120 ft as if it were bright/dim light (no color in darkness).","Se i dæmpet og mørkt lys inden for 120 ft som var det lyst/dæmpet lys (ingen farver i mørke)."],
  "Darkvision 60 ft":["See in dim and dark light within 60 ft as if it were bright/dim light (no color in darkness).","Se i dæmpet og mørkt lys inden for 60 ft som var det lyst/dæmpet lys (ingen farver i mørke)."],
  "Draconic Ancestry":["Choose a dragon type; determines your Breath Weapon and Damage Resistance types.","Vælg en dragetype; bestemmer typen for dit Breath Weapon og Damage Resistance."],
  "Draconic Flight":["Lvl 5: Bonus Action to sprout spectral wings; Fly Speed = your Speed for 10 minutes, once per Long Rest.","Niv. 5: Bonus-handling til at få spektralvinger; Fly Speed = din Speed i 10 minutter, én gang pr. Long Rest."],
  "Dwarven Resilience":["Resistance to Poison damage. Advantage on saving throws to avoid or end the Poisoned condition.","Modstand mod Poison-skade. Fordel på saving throws for at undgå eller afslutte Poisoned."],
  "Dwarven Toughness":["Hit Point maximum increases by 1, and again by 1 every level.","Maks. HP stiger med 1, og igen med 1 hvert niveau."],
  "Elven Lineage":["Choose a lineage (Drow, High Elf or Wood Elf) for a bonus cantrip; learn a higher-level spell at levels 3 and 5.","Vælg en slægt (Drow, Højelver eller Skovelver) for en bonus-cantrip; lær en spell af højere niveau ved niv. 3 og 5."],
  "Fey Ancestry":["Advantage on saving throws to avoid or end the Charmed condition.","Fordel på saving throws for at undgå eller afslutte Charmed."],
  "Fiendish Legacy":["Choose a legacy (Abyssal, Chthonic or Infernal) for a damage resistance and cantrip; learn a higher-level spell at levels 3 and 5.","Vælg en arv (Abyssal, Chthonic eller Infernal) for skademodstand og cantrip; lær en spell af højere niveau ved niv. 3 og 5."],
  "Giant Ancestry":["Choose a giant-based boon, usable a number of times equal to Prof. Bonus per Long Rest.","Vælg en kæmpe-baseret gave, som kan bruges et antal gange svarende til Prof. Bonus pr. Long Rest."],
  "Gnomish Cunning":["Advantage on Intelligence, Wisdom and Charisma saving throws.","Fordel på Intelligence-, Wisdom- og Charisma-saving throws."],
  "Gnomish Lineage":["Choose Forest Gnome (Minor Illusion + Speak with Animals) or Rock Gnome (Mending + Prestidigitation, plus clockwork devices).","Vælg Skovgnom (Minor Illusion + Speak with Animals) eller Klippegnom (Mending + Prestidigitation, samt urværksapparater)."],
  "Halfling Nimbleness":["Move through the space of any creature that is a size larger than you.","Bevæg dig gennem feltet for et væsen, der er én størrelse større end dig."],
  "Healing Hands":["Magic action: touch a creature and roll a number of d4s equal to Prof. Bonus; it regains that many HP. Once per Long Rest.","Magisk handling: rør et væsen og kast et antal d4'ere svarende til Prof. Bonus; det genopretter så mange HP. Én gang pr. Long Rest."],
  "Keen Senses":["Proficiency in the Insight, Perception or Survival skill.","Proficiency i færdigheden Insight, Perception eller Survival."],
  "Large Form":["Lvl 5: Bonus Action to become Large for 10 minutes; Advantage on Strength checks, Speed +10 ft. Once per Long Rest.","Niv. 5: Bonus-handling til at blive Large i 10 minutter; fordel på Strength checks, Speed +10 ft. Én gang pr. Long Rest."],
  "Light Bearer":["You know the Light cantrip (Charisma).","Du kender cantrippen Light (Charisma)."],
  "Luck":["When you roll a 1 on the d20 of a D20 Test, you can reroll the die and must use the new roll.","Når du slår en 1'er på d20'eren i et D20 Test, kan du kaste om og skal bruge det nye resultat."],
  "Naturally Stealthy":["You can Hide even when obscured only by a creature at least one size larger than you.","Du kan bruge Hide selv når du kun er skjult af et væsen, der er mindst én størrelse større end dig."],
  "Otherworldly Presence":["You know the Thaumaturgy cantrip.","Du kender cantrippen Thaumaturgy."],
  "Powerful Build":["Advantage on saving throws to end the Grappled condition. Count as one size larger for carrying capacity.","Fordel på saving throws for at afslutte Grappled. Tæller som én størrelse større ift. bæreevne."],
  "Relentless Endurance":["When reduced to 0 HP but not killed outright, you can drop to 1 HP instead. Once per Long Rest.","Når du rammes ned til 0 HP uden at blive dræbt direkte, kan du i stedet falde til 1 HP. Én gang pr. Long Rest."],
  "Resourceful":["You gain Heroic Inspiration whenever you finish a Long Rest.","Du får Heroic Inspiration, hver gang du fuldfører en Long Rest."],
  "Skillful":["You gain proficiency in one skill of your choice.","Du får proficiency i én valgfri færdighed."],
  "Stonecunning":["Bonus Action: gain Tremorsense 60 ft for 10 minutes while on or touching stone. Uses = Prof. Bonus per Long Rest.","Bonus-handling: få Tremorsense 60 ft i 10 minutter mens du er på eller rører sten. Antal brug = Prof. Bonus pr. Long Rest."],
  "Trance":["You don't need to sleep. You can finish a Long Rest in 4 hours of trance instead.","Du behøver ikke sove. Du kan fuldføre en Long Rest på 4 timers trance i stedet."],
  "Versatile":["You gain an Origin feat of your choice.","Du får et valgfrit Origin-feat."],
};

// PHB page reference for each species trait (2024 edition, Character Origins chapter).
export const TRAIT_PG={
  "Adrenaline Rush":195,"Brave":193,"Breath Weapon":187,"Celestial Resistance":186,"Celestial Revelation":186,
  "Damage Resistance":187,"Darkvision 120 ft":188,"Darkvision 60 ft":186,"Draconic Ancestry":187,"Draconic Flight":187,
  "Dwarven Resilience":188,"Dwarven Toughness":188,"Elven Lineage":190,"Fey Ancestry":190,"Fiendish Legacy":197,
  "Giant Ancestry":192,"Gnomish Cunning":191,"Gnomish Lineage":191,"Halfling Nimbleness":193,"Healing Hands":186,
  "Keen Senses":190,"Large Form":192,"Light Bearer":186,"Luck":193,"Naturally Stealthy":193,
  "Otherworldly Presence":197,"Powerful Build":192,"Relentless Endurance":195,"Resourceful":194,"Skillful":194,
  "Stonecunning":188,"Trance":190,"Versatile":194,
};

export const FEATDESC_DA={
  "Alert":"Læg Proficiency Bonus til Initiativ. Kan ikke overraskes når du er ved bevidsthed.",
  "Crafter":"Proficiency i 3 håndværksværktøjer. Håndværk med 20% rabat.",
  "Healer":"Battle Medic: brug en anvendelse af et Healer's Kit til at lade et væsen inden for 5 ft bruge en Hit Die (genopret slag+Prof.Bonus HP). Kast om ved 1'ere på enhver helings-terning.",
  "Lucky":"3 heldpoint pr. Long Rest. Kast en d20 om og vælg resultatet.",
  "Magic Initiate":"Lær 2 cantrips og 1 spell af 1. niveau fra en vilkårlig klasse.",
  "Savage Attacker":"Én gang pr. tur: kast nærkampsskade om og vælg resultatet.",
  "Skilled":"Få proficiency i 3 valgfrie færdigheder eller værktøjer.",
  "Tavern Brawler":"Ubevæbnede slag bruger d4+STR. Bonus-handling: gribe efter træf.",
  "Tough":"Maks HP +2 pr. niveau (med tilbagevirkende kraft).",
  "War Caster":"Fordel på CON concentration saves. Cast spells som lejlighedsangreb.",
  "Great Weapon Master":"Ved kritisk træf eller drab med tungt våben: bonusangreb. Valg: -5/+10.",
  "Mobile":"Fart +10 ft. Dash gennem vanskeligt terræn. Intet lejlighedsangreb fra dem du angriber.",
  "Resilient":"Proficiency i én saving throw. +1 til den evne.",
  "Sentinel":"Lejlighedsangreb sætter fart til 0. Lejlighedsangreb ved Disengage. Reaktion når en allieret angribes.",
  "Sharpshooter":"Ingen langdistancestraf. Ignorér halv/3/4 dækning. Valg: -5/+10.",
  "Inspiring Leader":"10-min tale: op til 6 allierede får midlertidige HP = niveau+CHA.",
  "Skulker":"Skjul dig når du er let sløret. Et forfejlet afstandsangreb afslører dig ikke.",
  "Durable":"+1 CON. Min HP fra livsterninger = 2x CON-mod.",
  "Spell Sniper":"Fordobl rækkevidde på angrebsspells. Ignorér halv og 3/4 dækning.",
  "Polearm Master":"Bonusangreb med skaftenden (1d4). Lejlighedsangreb når fjende træder ind i rækkevidde.",
  "Defense":"Kampstil: +1 AC mens du bærer rustning.",
  "Dueling":"Kampstil: +2 skade med ét nærkampsvåben.",
  "Two-Weapon Fighting":"Kampstil: læg evne-mod til skade med bihånds-våbnet.",
  "Archery":"Kampstil: +2 til afstandsangreb.",
  "Protection":"Kampstil: reaktion for at give ulempe på angreb mod allieret (skjold).",
  "Blind Fighting":"Kampstil: Blindsyn 10 ft.",
  "Elven Accuracy":"(Elf) +1 DEX/INT/WIS/CHA. Kast tre terninger ved fordel.",
  "Fey Teleportation":"(Elf) +1 INT/CHA. Tal Sylvan. 1/Short Rest: Misty Step.",
  "Wood Elf Magic":"(Skovelf) Longstrider, Pass without Trace, én druide-cantrip.",
  "High Elf Cantrip":"(Højelf) Én wizard-cantrip (INT).",
  "Dwarven Fortitude":"(Dværg) +1 CON. Dodge-handling: brug 1 HD til at heale.",
  "Orcish Fury":"(Ork) +1 STR/CON. Ekstra skadeterning på våbenangreb.",
  "Bountiful Luck":"(Halfling) Reaktion: giv allieret Lucky-omkast på en 1'er.",
  "Second Chance":"(Halfling) +1 DEX/CON/CHA. Reaktion: tving et omkast når du angribes.",
  "Squat Nimbleness":"(Lille) +1 STR/DEX. Fart +5. Bevæg dig gennem større væsener.",
  "Hunter":"(Ranger) Colossus Slayer, Giant Killer eller Horde Breaker.",
  "Dragon Fear":"(Dragonborn) +1 STR/CON/CHA. Ånd frygt i stedet for energi.",
  "Dragon Hide":"(Dragonborn) +1 STR/CON/CHA. Naturlig AC 13+DEX, kløangreb.",
  "Fade Away":"(Gnom) +1 INT/DEX. Reaktion: bliv usynlig når du tager skade.",
  "Flames of Phlegethos":"(Tiefling) +1 INT/CHA. Kast ildskade om, ildskjolds-aura.",
  "Infernal Constitution":"(Tiefling) +1 CON. Modstand mod kulde/gift, fordel på poison saves.",
  "Musician":"Proficiency med 3 instrumenter. Spil efter en Short eller Long Rest: allierede der hører det får Heroisk inspiration.",
  "Fey-Touched":"+1 INT/WIS/CHA. Altid-forberedt Misty Step + et Spådom- eller Fortryllelse-spell, castbart gratis 1/Long Rest.",
  "Shadow-Touched":"+1 INT/WIS/CHA. Altid-forberedt Invisibility + et Illusion- eller Nekromanti-spell, castbart gratis 1/Long Rest.",
};

// Short description of what each class feature does. Keyed by the English feature string. [en, da].
// Canon D&D keywords (proficiency, saves, spell slots, advantage) kept English in the Danish text too.
export const FEATURE_DESC={
  "Action Surge Lvl2":["Take one extra action on your turn, once per rest.","Tag én ekstra handling på din tur, én gang pr. Rest."],
  "Arcane Recovery 1/long rest":["Recover some spell slots on a short rest, once a day.","Få nogle spell slots tilbage på en Short Rest, én gang om dagen."],
  "Aura of Protection Lvl6":["You and nearby allies add your CHA to saving throws.","Du og nære allierede lægger din CHA til saving throws."],
  "Bardic Inspiration CHA mod/long rest":["Give an ally a bonus die to add to a roll.","Giv en allieret en bonus-terning til at lægge til et slag."],
  "Blessed Strikes Lvl7":["Add extra radiant or necrotic damage to your attacks.","Tilføj ekstra strålende eller nekrotisk skade til dine angreb."],
  "Channel Divinity":["Channel divine energy for powerful special effects.","Kanalisér guddommelig energi til stærke særlige effekter."],
  "Cunning Action Lvl2":["Dash, Disengage or Hide as a bonus action.","Dash, Disengage eller Hide som en bonus-handling."],
  "Danger Sense Lvl2":["Advantage on DEX saves against effects you can see.","Fordel på DEX saves mod effekter du kan se."],
  "Primal Knowledge Lvl3":["Extra skill proficiency; while raging, use STR instead of certain skills' normal ability.","Ekstra færdigheds-proficiency; brug STR i stedet for visse færdigheders normale evne mens du raser."],
  "Deft Explorer Lvl1":["Expertise in a skill plus extra languages.","Expertise i en færdighed plus ekstra sprog."],
  "Divine Order Lvl1":["Choose Protector (martial) or Thaumaturge (extra cantrip).","Vælg Protector (kamp) eller Thaumaturge (ekstra cantrip)."],
  "Divine Smite Lvl2":["Spend a spell slot for extra radiant damage on a hit.","Brug et spell slot for ekstra strålende skade ved træf."],
  "Druidic language":["You know the secret language of druids.","Du kan druidernes hemmelige sprog."],
  "Eldritch Invocations Lvl1":["Special magical abilities you pick and can swap.","Særlige magiske evner du vælger og kan bytte."],
  "Expertise Lvl1":["Double your proficiency bonus in chosen skills.","Fordobl din proficiency bonus i valgte færdigheder."],
  "Extra Attack Lvl5":["Attack twice when you take the Attack action.","Angrib to gange når du tager Attack-handlingen."],
  "Favored Enemy Lvl1":["Always have Hunter's Mark ready to track prey.","Har altid Hunter's Mark klar til at spore bytte."],
  "Fighting Style Lvl1":["A combat specialty like Archery or Defense.","En kamp-specialitet som Archery eller Defense."],
  "Font of Magic Lvl2":["Sorcery Points to make or convert spell slots.","Sorcery Points til at lave eller omdanne spell slots."],
  "Innate Sorcery Lvl1":["Boost your spells' power for a short burst.","Boost dine spells' styrke i et kort stød."],
  "Jack of All Trades Lvl2":["Add half your proficiency to non-proficient checks.","Læg halv proficiency til tjek du ikke er proficient i."],
  "Lay on Hands 5x level HP":["A pool of healing you touch into yourself or allies.","En pulje af healing du giver dig selv eller allierede ved berøring."],
  "Magical Cunning Lvl2":["Regain some Pact Magic spell slots once per long rest.","Få nogle Pact Magic-spell slots tilbage én gang pr. Long Rest."],
  "Martial Arts Lvl1":["Unarmed strikes and monk weapons scale with a die.","Ubevæbnede slag og munkevåben skalerer med en terning."],
  "Metamagic Lvl3":["Bend your spells: twin, quicken, subtle and more.","Bøj dine spells: twin, quicken, subtle m.m."],
  "Monks Focus Lvl2":["Focus Points power Flurry, Patient Defense and Step of the Wind.","Focus Points driver Flurry, Patient Defense og Step of the Wind."],
  "Pact Boon Lvl3":["A gift from your patron: Blade, Chain, Tome or Talisman.","En gave fra din patron: Blade, Chain, Tome eller Talisman."],
  "Pact Magic short rest recharge":["Your spell slots return after a short rest.","Dine spell slots vender tilbage efter en Short Rest."],
  "Primal Order Lvl1":["Choose Magician (extra cantrip) or Warden (martial).","Vælg Magician (ekstra cantrip) eller Warden (kamp)."],
  "Rage (2/long rest)":["Enter a fury: bonus damage and damage resistance.","Gå i raseri: bonus-skade og skademodstand."],
  "Reckless Attack Lvl2":["Attack with advantage, but enemies hit you more easily.","Angrib med fordel, men fjender rammer dig lettere."],
  "Second Wind Lvl1":["Bonus Action: regain 1d10+Fighter level HP. 2 uses at level 1 (3 at level 4, 4 at level 9); regain 1 per Short Rest, all per Long Rest.","Bonus-handling: genopret 1d10+Fighter-niveau HP. 2 brug ved niveau 1 (3 ved niveau 4, 4 ved niveau 9); genopret 1 pr. Short Rest, alle pr. Long Rest."],
  "Sneak Attack 1d6 per 2 levels":["Bonus damage when you have advantage or an ally is near.","Bonus-skade når du har fordel eller en allieret er nær."],
  "Spell Mastery Lvl18":["Cast chosen 1st/2nd-level spells at will.","Cast valgte 1./2.-niveau spells frit."],
  "Spellcasting CHA":["You cast spells using Charisma.","Du caster spells med Charisma."],
  "Spellcasting CHA Lvl1":["You cast spells using Charisma.","Du caster spells med Charisma."],
  "Spellcasting INT prepare INT+level":["Prepare a fresh set of Wizard spells each day.","Forbered et nyt sæt Wizard-spells hver dag."],
  "Spellcasting WIS Lvl1":["You cast spells using Wisdom.","Du caster spells med Wisdom."],
  "Stunning Strike Lvl5":["Spend Focus to try to stun a creature you hit.","Brug Focus for at forsøge at stunne et væsen du rammer."],
  "Subclass Lvl3":["Choose a subclass that shapes your character.","Vælg en underklasse der former din karakter."],
  "Thieves Cant":["A secret code of rogues and criminals.","En hemmelig kode blandt tyve og kriminelle."],
  "Unarmored Defense AC=10+DEX+CON":["Your AC is 10 + DEX + CON while wearing no armor.","Din AC er 10 + DEX + CON når du ikke bærer rustning."],
  "Unarmored Defense AC=10+DEX+WIS":["Your AC is 10 + DEX + WIS while wearing no armor.","Din AC er 10 + DEX + WIS når du ikke bærer rustning."],
  "Uncanny Dodge Lvl5":["Halve the damage from one attack as a reaction.","Halvér skaden fra ét angreb som en reaktion."],
  "Weapon Mastery x2":["Use the mastery property of 2 weapons.","Brug mastery-egenskaben på 2 våben."],
  "Weapon Mastery x3":["Use the mastery property of 3 weapons.","Brug mastery-egenskaben på 3 våben."],
  "Wild Shape Lvl2":["Transform into beasts you have learned.","Forvandl til dyr du har lært."],
};

export const SUBCLASS_DESC_DA={
  // Barbarian
  "Path of the Berserker":"Frenzy for ekstra angreb og frygt.",
  "Path of the Wild Heart":"Dyreånd-kræfter mens du raser.",
  "Path of the World Tree":"Livgivende vitalitet og gren-teleports.",
  "Path of the Zealot":"Guddommeligt raseri; svær at dræbe.",
  // Bard
  "College of Dance":"Adræt rustningsfrit forsvar og mobil inspiration.",
  "College of Glamour":"Fe-charme og fængslende optræden.",
  "College of Lore":"Ekstra færdigheder og Cutting Words.",
  "College of Valor":"Rustning, våben og kamp-inspiration.",
  // Cleric
  "Life Domain":"Den bedste healing i spillet.",
  "Light Domain":"Strålende ild og Warding Flare.",
  "Trickery Domain":"Illusioner, snig og dobbeltgængere.",
  "War Domain":"Våbendygtighed og krigs-velsignelser.",
  // Druid
  "Circle of the Land":"Bonus-spells fra valgt terræn.",
  "Circle of the Moon":"Stærke Wild Shape-kampformer.",
  "Circle of the Sea":"Storm, bølger og havets raseri.",
  "Circle of the Stars":"Stjernebilled-former.",
  // Fighter
  "Battle Master":"Taktiske manøvrer med superioritetsterninger.",
  "Champion":"Kritiske træf på 19-20.",
  "Eldritch Knight":"Wizard-spells plus våben.",
  "Psi Warrior":"Telekinetiske psioniske slag og skjolde.",
  // Monk
  "Warrior of Mercy":"Helbredende hænder eller skadende berøring.",
  "Warrior of Shadow":"Mørke, snig og skygge-teleports.",
  "Warrior of the Elements":"Elementinfunderede slag.",
  "Warrior of the Open Hand":"Klassisk kampkunst-mester.",
  // Paladin
  "Oath of Devotion":"Beskyttelse, ærlighed og helligt våben.",
  "Oath of Glory":"Atletisk fortræffelighed og heltemod.",
  "Oath of the Ancients":"Naturmagi og fe-lys.",
  "Oath of Vengeance":"Ubønhørlig jæger af ugerningsmænd.",
  // Ranger
  "Beast Master":"En loyal dyrekammerat kæmper med dig.",
  "Fey Wanderer":"Fe-charme og sindsbeskyttelse.",
  "Gloom Stalker":"Dødbringende baghold i mørke.",
  "Hunter":"Colossus Slayer og monster-dræbertaktik.",
  // Rogue
  "Arcane Trickster":"Snigende wizard-spells og Mage Hand-tricks.",
  "Assassin":"Dødbringende slag i overraskelsesrunden.",
  "Soulknife":"Psykiske blade og telepati.",
  "Thief":"Fast Hands og suveræn klatring.",
  // Sorcerer
  "Aberrant Sorcery":"Psioniske sindskræfter.",
  "Clockwork Sorcery":"Orden, balance og genoprettede kast.",
  "Draconic Sorcery":"Drage-hårdførhed og elementkraft.",
  "Wild Magic Sorcery":"Kaotiske magiske udladninger.",
  // Warlock
  "Archfey Patron":"Fe-teleports og forheksende magi.",
  "Celestial Patron":"Helbredende lys fra oven.",
  "Fiend Patron":"Ild, midlertidige HP og mørke aftaler.",
  "Great Old One Patron":"Psykiske hvisken og telepati.",
  // Wizard
  "Abjurer":"Beskyttende Arcane Ward opsuger skade.",
  "Diviner":"Portent: forudse og erstat terningkast.",
  "Evoker":"Form dine besværgelser uden om allierede.",
  "Illusionist":"Mester i forbedrede illusioner.",
};
