// Danish translations for the character sheet's "Features & Traits" content:
// class features, species traits, feat descriptions and subclass descriptions.

export const FEATURE_DA={
  "Action Surge Lvl2":"Ekstra handling (niv 2)",
  "Arcane Recovery 1/long rest":"Arkan genopladning 1/Long Rest",
  "Ritual Adept Lvl1":"Ritual-adept (niv 1)",
  "Scholar Lvl2":"Lærd (niv 2)",
  "Memorize Spell Lvl5":"Memorer spell (niv 5)",
  "Signature Spells Lvl20":"Signaturspells (niv 20)",
  "Aura of Protection Lvl6":"Beskyttelsesaura (niv 6)",
  "Bardic Inspiration CHA mod/long rest":"Bardisk inspiration CHA-mod/Long Rest",
  "Blessed Strikes Lvl7":"Velsignede slag (niv 7)",
  "Channel Divinity":"Kanalisér guddom",
  "Cunning Action Lvl2":"Snu handling (niv 2)",
  "Danger Sense Lvl2":"Faresans (niv 2)",
  "Primal Knowledge Lvl3":"Primal viden (niv 3)",
  "Deft Explorer Lvl2":"Behændig opdager (niv 2)",
  "Roving Lvl6":"Omstrejfende (niv 6)",
  "Tireless Lvl10":"Utrættelig (niv 10)",
  "Relentless Hunter Lvl13":"Ubønhørlig jæger (niv 13)",
  "Nature's Veil Lvl14":"Naturens slør (niv 14)",
  "Precise Hunter Lvl17":"Præcis jæger (niv 17)",
  "Feral Senses Lvl18":"Vilde sanser (niv 18)",
  "Foe Slayer Lvl20":"Fjendedræber (niv 20)",
  "Divine Order Lvl1":"Guddommelig orden (niv 1)",
  "Paladin's Smite Lvl2":"Paladinens smæk (niv 2)",
  "Channel Divinity Lvl2":"Kanaliser guddom (niv 2)",
  "Channel Divinity Lvl3":"Kanaliser guddom (niv 3)",
  "Faithful Steed Lvl5":"Trofast ganger (niv 5)",
  "Abjure Foes Lvl9":"Afsvær fjender (niv 9)",
  "Aura of Courage Lvl10":"Modets aura (niv 10)",
  "Radiant Strikes Lvl11":"Strålende slag (niv 11)",
  "Restoring Touch Lvl14":"Genoprettende berøring (niv 14)",
  "Aura Expansion Lvl18":"Aura-udvidelse (niv 18)",
  "Sear Undead Lvl5":"Svid Undead (niv 5)",
  "Divine Intervention Lvl10":"Guddommelig indgriben (niv 10)",
  "Improved Blessed Strikes Lvl14":"Forbedrede velsignede slag (niv 14)",
  "Greater Divine Intervention Lvl20":"Større guddommelig indgriben (niv 20)",
  "Druidic language":"Druidesprog",
  "Wild Companion Lvl2":"Vild følgesvend (niv 2)",
  "Wild Resurgence Lvl5":"Vild genopblomstring (niv 5)",
  "Elemental Fury Lvl7":"Elementarraseri (niv 7)",
  "Improved Elemental Fury Lvl15":"Forbedret elementarraseri (niv 15)",
  "Beast Spells Lvl18":"Dyre-spells (niv 18)",
  "Archdruid Lvl20":"Ærkedruide (niv 20)",
  "Eldritch Invocations Lvl1":"Eldritch-besværgelser (niv 1)",
  "Epic Boon Lvl19":"Epic Boon (niv 19)",
  "Expertise Lvl1":"Ekspertise (niv 1)",
  "Extra Attack Lvl5":"Ekstra angreb (niv 5)",
  "Expertise Lvl2":"Ekspertise (niv 2)",
  "Expertise Lvl9":"Ekspertise (niv 9)",
  "Font of Inspiration Lvl5":"Inspirationskilde (niv 5)",
  "Countercharm Lvl7":"Modtryllesang (niv 7)",
  "Magical Secrets Lvl10":"Magiske hemmeligheder (niv 10)",
  "Superior Inspiration Lvl18":"Overlegen inspiration (niv 18)",
  "Words of Creation Lvl20":"Skabelsens ord (niv 20)",
  "Favored Enemy Lvl1":"Foretrukken fjende (niv 1)",
  "Tactical Mind Lvl2":"Taktisk sind (niv 2)",
  "Tactical Shift Lvl5":"Taktisk forskydning (niv 5)",
  "Indomitable Lvl9":"Ukuelig (niv 9)",
  "Tactical Master Lvl9":"Taktisk mester (niv 9)",
  "Two Extra Attacks Lvl11":"To ekstra angreb (niv 11)",
  "Studied Attacks Lvl13":"Studerede angreb (niv 13)",
  "Three Extra Attacks Lvl20":"Tre ekstra angreb (niv 20)",
  "Rage Lvl1":"Raseri (niv 1)",
  "Fast Movement Lvl5":"Hurtig bevægelse (niv 5)",
  "Feral Instinct Lvl7":"Vildt instinkt (niv 7)",
  "Instinctive Pounce Lvl7":"Instinktivt spring (niv 7)",
  "Brutal Strike Lvl9":"Brutalt slag (niv 9)",
  "Relentless Rage Lvl11":"Ubønhørligt raseri (niv 11)",
  "Improved Brutal Strike Lvl13":"Forbedret brutalt slag (niv 13)",
  "Persistent Rage Lvl15":"Vedvarende raseri (niv 15)",
  "Improved Brutal Strike Lvl17":"Forbedret brutalt slag (niv 17)",
  "Indomitable Might Lvl18":"Ukuelig styrke (niv 18)",
  "Primal Champion Lvl20":"Primal mester (niv 20)",
  "Fighting Style Lvl1":"Kampstil (niv 1)",
  "Font of Magic Lvl2":"Magikilde (niv 2)",
  "Innate Sorcery Lvl1":"Medfødt trolddom (niv 1)",
  "Jack of All Trades Lvl2":"Altmuligmand (niv 2)",
  "Lay on Hands 5x level HP":"Håndspålæggelse 5x niveau HP",
  "Magical Cunning Lvl2":"Magisk snuhed (niv 2)",
  "Contact Patron Lvl9":"Kontakt patron (niv 9)",
  "Mystic Arcanum Lvl11":"Mystisk arcanum (niv 11)",
  "Mystic Arcanum Lvl13":"Mystisk arcanum (niv 13)",
  "Mystic Arcanum Lvl15":"Mystisk arcanum (niv 15)",
  "Mystic Arcanum Lvl17":"Mystisk arcanum (niv 17)",
  "Eldritch Master Lvl20":"Eldritch-mester (niv 20)",
  "Martial Arts Lvl1":"Kampkunst (niv 1)",
  "Unarmored Movement Lvl2":"Rustningsfri bevægelse (niv 2)",
  "Uncanny Metabolism Lvl2":"Uhyggeligt stofskifte (niv 2)",
  "Deflect Attacks Lvl3":"Afled angreb (niv 3)",
  "Slow Fall Lvl4":"Langsomt fald (niv 4)",
  "Empowered Strikes Lvl6":"Styrkede slag (niv 6)",
  "Evasion Lvl7":"Undvigelse (niv 7)",
  "Acrobatic Movement Lvl9":"Akrobatisk bevægelse (niv 9)",
  "Heightened Focus Lvl10":"Forstærket fokus (niv 10)",
  "Self-Restoration Lvl10":"Selvhelbredelse (niv 10)",
  "Deflect Energy Lvl13":"Afled energi (niv 13)",
  "Disciplined Survivor Lvl14":"Disciplineret overlever (niv 14)",
  "Perfect Focus Lvl15":"Perfekt fokus (niv 15)",
  "Superior Defense Lvl18":"Overlegent forsvar (niv 18)",
  "Body and Mind Lvl20":"Krop og sind (niv 20)",
  "Metamagic Lvl2":"Metamagi (niv 2)",
  "Sorcerous Restoration Lvl5":"Sorcerisk genopretning (niv 5)",
  "Sorcery Incarnate Lvl7":"Sorcery inkarneret (niv 7)",
  "Metamagic Lvl10":"Metamagi (niv 10)",
  "Metamagic Lvl17":"Metamagi (niv 17)",
  "Arcane Apotheosis Lvl20":"Arkan apoteose (niv 20)",
  "Monks Focus Lvl2":"Munkens fokus (niv 2)",
  "Pact Magic short rest recharge":"Pagtmagi genoplades ved Short Rest",
  "Primal Order Lvl1":"Oprindelig orden (niv 1)",
  "Rage (2/long rest)":"Raseri (2/Long Rest)",
  "Reckless Attack Lvl2":"Hensynsløst angreb (niv 2)",
  "Second Wind Lvl1":"Andet stød (niv 1)",
  "Sneak Attack 1d6 per 2 levels":"Snigangreb 1d6 pr. 2 niveauer",
  "Steady Aim Lvl3":"Stabilt sigte (niv 3)",
  "Cunning Strike Lvl5":"Snu slag (niv 5)",
  "Expertise Lvl6":"Ekspertise (niv 6)",
  "Reliable Talent Lvl7":"Pålideligt talent (niv 7)",
  "Improved Cunning Strike Lvl11":"Forbedret snu slag (niv 11)",
  "Devious Strikes Lvl14":"Underfundige slag (niv 14)",
  "Slippery Mind Lvl15":"Glat sind (niv 15)",
  "Elusive Lvl18":"Undvigende (niv 18)",
  "Stroke of Luck Lvl20":"Heldigt tilfælde (niv 20)",
  "Spell Mastery Lvl18":"Spell-mesterskab (niv 18)",
  "Spellcasting CHA":"Magi (CHA)",
  "Spellcasting CHA Lvl1":"Magi CHA (niv 1)",
  "Spellcasting INT":"Magi (INT)",
  "Spellcasting WIS Lvl1":"Magi WIS (niv 1)",
  "Stunning Strike Lvl5":"Bedøvende slag (niv 5)",
  "Subclass Lvl3":"Underklasse (niv 3)",
  "Thieves Cant":"Tyvesprog",
  "Unarmored Defense AC=10+DEX+CON":"Rustningsfrit forsvar AC=10+DEX+CON",
  "Unarmored Defense AC=10+DEX+WIS":"Rustningsfrit forsvar AC=10+DEX+WIS",
  "Uncanny Dodge Lvl5":"Uhyggelig undvigelse (niv 5)",
  "Weapon Mastery x2":"Våbenmesterskab x2",
  "Weapon Mastery x3":"Våbenmesterskab x3",
  "Wild Shape Lvl2":"Vildskikkelse (niv 2)",
};

export const TRAIT_DA={
  "Adrenaline Rush":"Adrenalinsus",
  "Brave":"Modig",
  "Breath Weapon":"Åndevåben",
  "Celestial Resistance":"Himmelsk modstand",
  "Celestial Revelation":"Himmelsk åbenbaring",
  "Damage Resistance":"Skademodstand",
  "Darkvision 120 ft":"Mørkesyn 120 ft",
  "Darkvision 60 ft":"Mørkesyn 60 ft",
  "Draconic Ancestry":"Dragisk afstamning",
  "Draconic Flight":"Dragisk flugt",
  "Dwarven Resilience":"Dværge-hårdførhed",
  "Dwarven Toughness":"Dværge-sejhed",
  "Elven Lineage":"Elverslægt",
  "Fey Ancestry":"Fe-afstamning",
  "Fiendish Legacy":"Djævelsk arv",
  "Giant Ancestry":"Kæmpe-afstamning",
  "Gnomish Cunning":"Gnom-snuhed",
  "Gnomish Lineage":"Gnomslægt",
  "Halfling Nimbleness":"Halfling-adræthed",
  "Healing Hands":"Helbredende hænder",
  "Keen Senses":"Skarpe sanser",
  "Large Form":"Stor form",
  "Light Bearer":"Lysbærer",
  "Luck":"Held",
  "Naturally Stealthy":"Naturligt snigende",
  "Otherworldly Presence":"Overjordisk nærvær",
  "Powerful Build":"Kraftig bygning",
  "Relentless Endurance":"Ubønhørlig udholdenhed",
  "Resourceful":"Opfindsom",
  "Skillful":"Dygtig",
  "Stonecunning":"Stenkløgt",
  "Trance":"Trance",
  "Versatile":"Alsidig",
};

// One-line description of each species trait, verified against the 2024 PHB (p.186-197). [en, da].
export const TRAIT_DESC={
  "Adrenaline Rush":["Bonus Action: Dash and gain temp HP = Prof. Bonus. Uses = Prof. Bonus per Short/Long Rest.","Bonus-handling: Dash og få midlertidige HP = Prof. Bonus. Antal brug = Prof. Bonus pr. Short/Long Rest."],
  "Brave":["Advantage on saving throws to avoid or end the Frightened condition.","Fordel på saving throws for at undgå eller afslutte Frightened."],
  "Breath Weapon":["Replace an attack with a 15-ft cone or 30-ft line; DEX save for half damage of your Draconic Ancestry's type (full on a fail), scales with level. Uses = Prof. Bonus per Long Rest.","Erstat et angreb med en 15 ft kegle eller 30 ft linje; DEX save for halv skade af typen fra din Draconic Ancestry (fuld skade ved fejl), skalerer med niveau. Antal brug = Prof. Bonus pr. Long Rest."],
  "Celestial Resistance":["Resistance to Necrotic and Radiant damage.","Modstand mod Necrotic- og Radiant-skade."],
  "Celestial Revelation":["Lvl 3: Bonus Action to transform (Heavenly Wings, Inner Radiance or Necrotic Shroud) for 1 minute, once per Long Rest. Once per turn while transformed, deal extra damage = Prof. Bonus (Necrotic for Necrotic Shroud, Radiant for the other two) on a hit.","Niv. 3: Bonus-handling til at transformere (Heavenly Wings, Inner Radiance eller Necrotic Shroud) i 1 minut, én gang pr. Long Rest. Én gang pr. tur mens du er transformeret: giv ekstra skade = Prof. Bonus (Necrotic for Necrotic Shroud, Radiant for de to andre) ved et træf."],
  "Damage Resistance":["Resistance to the damage type determined by your Draconic Ancestry.","Modstand mod skadetypen bestemt af din Draconic Ancestry."],
  "Darkvision 120 ft":["See in dim and dark light within 120 ft as if it were bright/dim light (no color in darkness).","Se i dæmpet og mørkt lys inden for 120 ft som var det lyst/dæmpet lys (ingen farver i mørke)."],
  "Darkvision 60 ft":["See in dim and dark light within 60 ft as if it were bright/dim light (no color in darkness).","Se i dæmpet og mørkt lys inden for 60 ft som var det lyst/dæmpet lys (ingen farver i mørke)."],
  "Draconic Ancestry":["Choose a dragon type; determines your Breath Weapon and Damage Resistance types.","Vælg en dragetype; bestemmer typen for dit Breath Weapon og Damage Resistance."],
  "Draconic Flight":["Lvl 5: Bonus Action to sprout spectral wings; Fly Speed = your Speed for 10 minutes, once per Long Rest.","Niv. 5: Bonus-handling til at få spektralvinger; Fly Speed = din Speed i 10 minutter, én gang pr. Long Rest."],
  "Dwarven Resilience":["Resistance to Poison damage. Advantage on saving throws to avoid or end the Poisoned condition.","Modstand mod Poison-skade. Fordel på saving throws for at undgå eller afslutte Poisoned."],
  "Dwarven Toughness":["Hit Point maximum increases by 1, and again by 1 every level.","Maks. HP stiger med 1, og igen med 1 hvert niveau."],
  "Elven Lineage":["Choose a lineage (Drow, High Elf or Wood Elf) for a bonus cantrip; learn a higher-level spell at levels 3 and 5.","Vælg en slægt (Drow, Højelver eller Skovelver) for en bonus-cantrip; lær en spell af højere niveau ved niv. 3 og 5."],
  "Fey Ancestry":["Advantage on saving throws to avoid or end the Charmed condition.","Fordel på saving throws for at undgå eller afslutte Charmed."],
  "Fiendish Legacy":["Choose a legacy (Abyssal, Chthonic or Infernal) for a damage resistance and cantrip; learn a higher-level spell at levels 3 and 5.","Vælg en arv (Abyssal, Chthonic eller Infernal) for skademodstand og cantrip; lær en spell af højere niveau ved niv. 3 og 5."],
  "Giant Ancestry":["Choose a giant-based boon, usable a number of times equal to Prof. Bonus per Long Rest.","Vælg en kæmpe-baseret gave, som kan bruges et antal gange svarende til Prof. Bonus pr. Long Rest."],
  "Gnomish Cunning":["Advantage on Intelligence, Wisdom and Charisma saving throws.","Fordel på Intelligence-, Wisdom- og Charisma-saving throws."],
  "Gnomish Lineage":["Choose Forest Gnome (Minor Illusion + Speak with Animals) or Rock Gnome (Mending + Prestidigitation, plus clockwork devices).","Vælg Skovgnom (Minor Illusion + Speak with Animals) eller Klippegnom (Mending + Prestidigitation, samt urværksapparater)."],
  "Halfling Nimbleness":["Move through the space of any creature that is a size larger than you.","Bevæg dig gennem feltet for et væsen, der er én størrelse større end dig."],
  "Healing Hands":["Magic action: touch a creature and roll a number of d4s equal to Prof. Bonus; it regains that many HP. Once per Long Rest.","Magisk handling: rør et væsen og kast et antal d4'ere svarende til Prof. Bonus; det genopretter så mange HP. Én gang pr. Long Rest."],
  "Keen Senses":["Proficiency in the Insight, Perception or Survival skill.","Proficiency i færdigheden Insight, Perception eller Survival."],
  "Large Form":["Lvl 5: Bonus Action to become Large for 10 minutes; Advantage on Strength checks, Speed +10 ft. Once per Long Rest.","Niv. 5: Bonus-handling til at blive Large i 10 minutter; fordel på Strength checks, Speed +10 ft. Én gang pr. Long Rest."],
  "Light Bearer":["You know the Light cantrip (Charisma).","Du kender cantrippen Light (Charisma)."],
  "Luck":["When you roll a 1 on the d20 of a D20 Test, you can reroll the die and must use the new roll.","Når du slår en 1'er på d20'eren i et D20 Test, kan du kaste om og skal bruge det nye resultat."],
  "Naturally Stealthy":["You can Hide even when obscured only by a creature at least one size larger than you.","Du kan bruge Hide selv når du kun er skjult af et væsen, der er mindst én størrelse større end dig."],
  "Otherworldly Presence":["You know the Thaumaturgy cantrip.","Du kender cantrippen Thaumaturgy."],
  "Powerful Build":["Advantage on saving throws to end the Grappled condition. Count as one size larger for carrying capacity.","Fordel på saving throws for at afslutte Grappled. Tæller som én størrelse større ift. bæreevne."],
  "Relentless Endurance":["When reduced to 0 HP but not killed outright, you can drop to 1 HP instead. Once per Long Rest.","Når du rammes ned til 0 HP uden at blive dræbt direkte, kan du i stedet falde til 1 HP. Én gang pr. Long Rest."],
  "Resourceful":["You gain Heroic Inspiration whenever you finish a Long Rest.","Du får Heroic Inspiration, hver gang du fuldfører en Long Rest."],
  "Skillful":["You gain proficiency in one skill of your choice.","Du får proficiency i én valgfri færdighed."],
  "Stonecunning":["Bonus Action: gain Tremorsense 60 ft for 10 minutes while on or touching stone. Uses = Prof. Bonus per Long Rest.","Bonus-handling: få Tremorsense 60 ft i 10 minutter mens du er på eller rører sten. Antal brug = Prof. Bonus pr. Long Rest."],
  "Trance":["You don't need to sleep. You can finish a Long Rest in 4 hours of trance instead.","Du behøver ikke sove. Du kan fuldføre en Long Rest på 4 timers trance i stedet."],
  "Versatile":["You gain an Origin feat of your choice.","Du får et valgfrit Origin-feat."],
};

// PHB page reference for each species trait (2024 edition, Character Origins chapter).
// Base class feature page refs (PHB 2024), keyed by class then by the exact string used in
// CLASSES[cn].features — several feature names (Subclass Lvl3, Channel Divinity, Extra Attack, ...)
// are reused across classes on different pages, so this can't be a single flat lookup like TRAIT_PG.
// Verified against every class's own "[Class] Features" section (Chapter 3) page by page. A few
// levels (e.g. Bard/Rogue's second Expertise, Sorcerer's later Metamagic, Warlock's later Mystic
// Arcanum) don't get their own heading in the book - they're additional lines within an earlier
// level's own feature text, so they cite that earlier feature's page.
export const CLASS_FEATURE_PG={
  Barbarian:{"Rage Lvl1":51,"Unarmored Defense AC=10+DEX+CON":51,"Weapon Mastery":52,"Reckless Attack Lvl2":52,"Danger Sense Lvl2":52,"Primal Knowledge Lvl3":52,"Subclass Lvl3":52,"Extra Attack Lvl5":53,"Fast Movement Lvl5":53,"Feral Instinct Lvl7":53,"Instinctive Pounce Lvl7":53,"Brutal Strike Lvl9":53,"Relentless Rage Lvl11":53,"Improved Brutal Strike Lvl13":53,"Persistent Rage Lvl15":53,"Improved Brutal Strike Lvl17":53,"Indomitable Might Lvl18":53,"Epic Boon Lvl19":53,"Primal Champion Lvl20":53},
  Bard:{"Bardic Inspiration CHA mod/long rest":59,"Expertise Lvl2":60,"Jack of All Trades Lvl2":60,"Subclass Lvl3":60,"Font of Inspiration Lvl5":61,"Countercharm Lvl7":61,"Expertise Lvl9":60,"Magical Secrets Lvl10":61,"Superior Inspiration Lvl18":61,"Epic Boon Lvl19":61,"Words of Creation Lvl20":61},
  Cleric:{"Divine Order Lvl1":70,"Channel Divinity Lvl2":70,"Subclass Lvl3":71,"Sear Undead Lvl5":71,"Blessed Strikes Lvl7":71,"Divine Intervention Lvl10":71,"Improved Blessed Strikes Lvl14":71,"Epic Boon Lvl19":71,"Greater Divine Intervention Lvl20":71},
  Druid:{"Druidic language":79,"Primal Order Lvl1":79,"Wild Shape Lvl2":80,"Wild Companion Lvl2":81,"Subclass Lvl3":81,"Wild Resurgence Lvl5":81,"Elemental Fury Lvl7":81,"Improved Elemental Fury Lvl15":81,"Beast Spells Lvl18":81,"Epic Boon Lvl19":81,"Archdruid Lvl20":82},
  Fighter:{"Fighting Style Lvl1":91,"Second Wind Lvl1":91,"Weapon Mastery":91,"Action Surge Lvl2":91,"Tactical Mind Lvl2":91,"Subclass Lvl3":92,"Extra Attack Lvl5":92,"Tactical Shift Lvl5":92,"Indomitable Lvl9":92,"Tactical Master Lvl9":92,"Two Extra Attacks Lvl11":92,"Studied Attacks Lvl13":92,"Epic Boon Lvl19":92,"Three Extra Attacks Lvl20":92},
  Monk:{"Martial Arts Lvl1":101,"Unarmored Defense AC=10+DEX+WIS":101,"Monks Focus Lvl2":101,"Unarmored Movement Lvl2":102,"Uncanny Metabolism Lvl2":102,"Deflect Attacks Lvl3":102,"Subclass Lvl3":103,"Slow Fall Lvl4":103,"Extra Attack Lvl5":103,"Stunning Strike Lvl5":103,"Empowered Strikes Lvl6":103,"Evasion Lvl7":103,"Acrobatic Movement Lvl9":103,"Heightened Focus Lvl10":103,"Self-Restoration Lvl10":103,"Deflect Energy Lvl13":103,"Disciplined Survivor Lvl14":103,"Perfect Focus Lvl15":103,"Superior Defense Lvl18":103,"Epic Boon Lvl19":103,"Body and Mind Lvl20":103},
  Paladin:{"Lay on Hands 5x level HP":109,"Spellcasting CHA Lvl1":109,"Weapon Mastery x2":110,"Paladin's Smite Lvl2":110,"Channel Divinity Lvl3":110,"Subclass Lvl3":111,"Extra Attack Lvl5":111,"Faithful Steed Lvl5":111,"Aura of Protection Lvl6":111,"Abjure Foes Lvl9":111,"Aura of Courage Lvl10":111,"Radiant Strikes Lvl11":111,"Restoring Touch Lvl14":111,"Aura Expansion Lvl18":111,"Epic Boon Lvl19":111},
  Ranger:{"Spellcasting WIS Lvl1":119,"Favored Enemy Lvl1":119,"Weapon Mastery x2":120,"Deft Explorer Lvl2":120,"Subclass Lvl3":120,"Extra Attack Lvl5":120,"Roving Lvl6":121,"Expertise Lvl9":121,"Tireless Lvl10":121,"Relentless Hunter Lvl13":121,"Nature's Veil Lvl14":121,"Precise Hunter Lvl17":121,"Feral Senses Lvl18":121,"Epic Boon Lvl19":121,"Foe Slayer Lvl20":121},
  Rogue:{"Expertise Lvl1":129,"Sneak Attack 1d6 per 2 levels":129,"Thieves Cant":129,"Weapon Mastery x2":129,"Cunning Action Lvl2":130,"Subclass Lvl3":130,"Steady Aim Lvl3":130,"Cunning Strike Lvl5":130,"Uncanny Dodge Lvl5":131,"Expertise Lvl6":129,"Evasion Lvl7":131,"Reliable Talent Lvl7":131,"Improved Cunning Strike Lvl11":131,"Devious Strikes Lvl14":131,"Slippery Mind Lvl15":131,"Elusive Lvl18":131,"Epic Boon Lvl19":131,"Stroke of Luck Lvl20":131},
  Sorcerer:{"Spellcasting CHA":139,"Innate Sorcery Lvl1":140,"Font of Magic Lvl2":140,"Metamagic Lvl2":141,"Subclass Lvl3":141,"Sorcerous Restoration Lvl5":141,"Sorcery Incarnate Lvl7":142,"Metamagic Lvl10":141,"Metamagic Lvl17":141,"Epic Boon Lvl19":142,"Arcane Apotheosis Lvl20":142},
  Warlock:{"Eldritch Invocations Lvl1":153,"Pact Magic short rest recharge":153,"Magical Cunning Lvl2":154,"Subclass Lvl3":154,"Contact Patron Lvl9":155,"Mystic Arcanum Lvl11":155,"Mystic Arcanum Lvl13":155,"Mystic Arcanum Lvl15":155,"Mystic Arcanum Lvl17":155,"Epic Boon Lvl19":155,"Eldritch Master Lvl20":155},
  Wizard:{"Spellcasting INT":165,"Ritual Adept Lvl1":166,"Arcane Recovery 1/long rest":166,"Scholar Lvl2":166,"Subclass Lvl3":167,"Memorize Spell Lvl5":167,"Spell Mastery Lvl18":167,"Epic Boon Lvl19":167,"Signature Spells Lvl20":167},
};
export const TRAIT_PG={
  "Adrenaline Rush":195,"Brave":193,"Breath Weapon":187,"Celestial Resistance":186,"Celestial Revelation":186,
  "Damage Resistance":187,"Darkvision 120 ft":188,"Darkvision 60 ft":186,"Draconic Ancestry":187,"Draconic Flight":187,
  "Dwarven Resilience":188,"Dwarven Toughness":188,"Elven Lineage":190,"Fey Ancestry":190,"Fiendish Legacy":197,
  "Giant Ancestry":192,"Gnomish Cunning":191,"Gnomish Lineage":191,"Halfling Nimbleness":193,"Healing Hands":186,
  "Keen Senses":190,"Large Form":192,"Light Bearer":186,"Luck":193,"Naturally Stealthy":193,
  "Otherworldly Presence":197,"Powerful Build":192,"Relentless Endurance":195,"Resourceful":194,"Skillful":194,
  "Stonecunning":188,"Trance":190,"Versatile":194,
};

export const FEATDESC_DA={
  "Alert":"Læg Proficiency Bonus til Initiativ. Kan bytte dit Initiativ med en villig alliereret i samme kamp (ikke hvis nogen af jer er Incapacitated).",
  "Crafter":"Proficiency i 3 håndværksværktøjer. Håndværk med 20% rabat. Efter en Long Rest: håndlav én genstand fra Fast Crafting-tabellen (holder til din næste Long Rest).",
  "Healer":"Battle Medic: brug en anvendelse af et Healer's Kit til at lade et væsen inden for 5 ft bruge en Hit Die (genopret slag+Prof.Bonus HP). Kast om ved 1'ere på HP-terninger fra en spell eller fra Battle Medic.",
  "Lucky":"Heldpoint = Proficiency Bonus pr. Long Rest. Brug ét for at få Fordel på en D20 Test, eller for at give Ulempe på et angreb mod dig.",
  "Magic Initiate":"Lær 2 cantrips og 1 altid-forberedt spell af 1. niveau (castes gratis én gang pr. Long Rest) fra Cleric-, Druid- eller Wizard-listen.",
  "Savage Attacker":"Én gang pr. tur: slå et våbens skadeterninger to gange og brug det ene resultat.",
  "Skilled":"Få proficiency i 3 valgfrie færdigheder eller værktøjer.",
  "Tavern Brawler":"Ubevæbnede slag bruger d4+STR (kast en 1'er om); proficiency med improviserede våben; én gang pr. tur skubber et ramt Unarmed Strike-mål 5 ft.",
  "Tough":"Maks HP +2 pr. niveau (med tilbagevirkende kraft).",
  "War Caster":"Fordel på CON concentration saves. Cast en spell som Reaction i stedet for et lejlighedsangreb. Kan udføre Somatic-komponenter selv med våben eller skjold i hånden.",
  "Great Weapon Master":"+1 STR. Træf med tungt våben giver +Prof.Bonus skade. Hew: bonusangreb ved kritisk træf eller drab.",
  "Resilient":"Proficiency i én saving throw. +1 til den evne.",
  "Sentinel":"Lejlighedsangreb sætter fart til 0. Lejlighedsangreb ved Disengage. Reaktion når en allieret angribes.",
  "Sharpshooter":"+1 DEX. Ignorér Half og Three-Quarters Cover på afstandsangreb.",
  "Inspiring Leader":"Efter en Short eller Long Rest: giv en optræden. Op til 6 allierede (inkl. dig selv) inden for 30 ft får midlertidige HP = dit niveau + modifier for den evne du øgede (WIS eller CHA).",
  "Skulker":"Blindsyn 10 ft. Fordel på Dexterity (Stealth)-checket for at gemme dig i kamp. Et forfejlet angrebsslag mens du er skjult afslører ikke din position.",
  "Durable":"+1 CON. Fordel på Death Saving Throws. Bonus Action: brug en livsterning og genopret HP svarende til slaget.",
  "Speedy":"+1 DEX eller CON. Fart +10 ft. Dash ignorerer vanskeligt terræn. Fordel mod lejlighedsangreb.",
  "Spell Sniper":"+1 INT/WIS/CHA. Angrebsspells ignorerer Half og Three-Quarters Cover. Ingen ulempe på spell-angreb i nærkamp. Spells med rækkevidde på 10+ ft der kræver et angrebsslag får +60 ft rækkevidde.",
  "Polearm Master":"Bonusangreb med skaftenden (1d4). Lejlighedsangreb når fjende træder ind i rækkevidde.",
  "Defense":"Kampstil: +1 AC mens du bærer rustning.",
  "Dueling":"Kampstil: +2 skade med ét nærkampsvåben.",
  "Two-Weapon Fighting":"Kampstil: læg evne-mod til skade med bihånds-våbnet.",
  "Archery":"Kampstil: +2 til afstandsangreb.",
  "Protection":"Kampstil: reaktion for at give ulempe på angreb mod allieret (skjold).",
  "Blind Fighting":"Kampstil: Blindsyn 10 ft.",
  "Great Weapon Fighting":"Kampstil: Behandl 1'ere og 2'ere på skadeterninger som 3'ere, for nærkampsvåben der holdes med to hænder (Two-Handed eller Versatile).",
  "Interception":"Kampstil: reaktion for at reducere skade givet til en allieret inden for 5 ft med 1d10+Prof.Bonus. Kræver skjold eller våben.",
  "Thrown Weapon Fighting":"Kampstil: +2 skade ved træf med kastede våben.",
  "Unarmed Fighting":"Kampstil: Unarmed Strike-skade bliver 1d6 (1d8 hvis tomhændet); bonus 1d4 til et grebet væsen hver tur.",
  "Hunter":"(Ranger) Colossus Slayer, Giant Killer eller Horde Breaker.",
  "Musician":"Proficiency med 3 instrumenter. Spil efter en Short eller Long Rest: allierede der hører det får Heroisk inspiration.",
  "Fey-Touched":"+1 INT/WIS/CHA. Altid-forberedt Misty Step + et valgt 1.-niveau Divination- eller Enchantment-spell; cast hver af dem gratis én gang, genoprettes efter en Long Rest.",
  "Shadow-Touched":"+1 INT/WIS/CHA. Altid-forberedt Invisibility + et valgt 1.-niveau Illusion- eller Necromancy-spell; cast hver af dem gratis én gang, genoprettes efter en Long Rest.",
};

// Short description of what each class feature does. Keyed by the English feature string. [en, da].
// Canon D&D keywords (proficiency, saves, spell slots, advantage) kept English in the Danish text too.
export const FEATURE_DESC={
  "Action Surge Lvl2":["Take one extra action on your turn, once per rest.","Tag én ekstra handling på din tur, én gang pr. Rest."],
  "Arcane Recovery 1/long rest":["Recover some spell slots on a short rest, once a day.","Få nogle spell slots tilbage på en Short Rest, én gang om dagen."],
  "Ritual Adept Lvl1":["Cast any spell in your spellbook as a Ritual if it has the Ritual tag, even without it prepared - but you must read the spell from the book.","Cast et vilkårligt spell i din spellbog som et Ritual hvis det har Ritual-mærket, selv uden at have det forberedt - men du skal læse spellet fra bogen."],
  "Scholar Lvl2":["Choose a skill among Arcana, History, Investigation, Medicine, Nature, or Religion in which you're proficient; gain Expertise in it.","Vælg en færdighed blandt Arcana, History, Investigation, Medicine, Nature eller Religion som du er proficient i; få Expertise i den."],
  "Memorize Spell Lvl5":["Whenever you finish a Short Rest, you can study your spellbook and replace one of your prepared level 1+ spells with another level 1+ spell from the book.","Når du fuldfører en Short Rest, kan du studere din spellbog og erstatte et af dine forberedte niveau 1+ spells med et andet niveau 1+ spell fra bogen."],
  "Signature Spells Lvl20":["Choose two level 3 spells in your spellbook as signature spells. You always have them prepared, and you can cast each once at level 3 without a spell slot; regain that on a Short or Long Rest. Casting either at a higher level still costs a spell slot.","Vælg to niveau 3-spells i din spellbog som signaturspells. Du har altid dem forberedt, og du kan caste hver af dem én gang på niveau 3 uden et spell slot; genopret den evne ved en Short eller Long Rest. At caste dem på et højere niveau koster stadig et spell slot."],
  "Aura of Protection Lvl6":["You and nearby allies add your CHA to saving throws.","Du og nære allierede lægger din CHA til saving throws."],
  "Bardic Inspiration CHA mod/long rest":["Give an ally a bonus die to add to a roll.","Giv en allieret en bonus-terning til at lægge til et slag."],
  "Blessed Strikes Lvl7":["Add extra radiant or necrotic damage to your attacks.","Tilføj ekstra strålende eller nekrotisk skade til dine angreb."],
  "Channel Divinity":["Channel divine energy for powerful special effects.","Kanalisér guddommelig energi til stærke særlige effekter."],
  "Cunning Action Lvl2":["Dash, Disengage or Hide as a bonus action.","Dash, Disengage eller Hide som en bonus-handling."],
  "Danger Sense Lvl2":["Advantage on DEX saves against effects you can see.","Fordel på DEX saves mod effekter du kan se."],
  "Primal Knowledge Lvl3":["Extra skill proficiency; while raging, use STR instead of certain skills' normal ability.","Ekstra færdigheds-proficiency; brug STR i stedet for visse færdigheders normale evne mens du raser."],
  "Deft Explorer Lvl2":["Expertise in one skill you lack it in, plus two languages of your choice.","Expertise i én færdighed du mangler den i, plus to valgfrie sprog."],
  "Roving Lvl6":["Speed +10 ft while not wearing Heavy armor; also gain a Climb Speed and a Swim Speed equal to your Speed.","Speed +10 ft når du ikke bærer Heavy rustning; få også en Climb Speed og en Swim Speed svarende til din Speed."],
  "Tireless Lvl10":["Magic action: gain Temp HP equal to 1d8 + WIS mod, a number of times equal to your WIS mod (min. once), regain on Long Rest. Also, whenever you finish a Short Rest, reduce your Exhaustion level by 1.","Magisk handling: få midlertidige HP svarende til 1d8 + WIS-mod, et antal gange svarende til dit WIS-mod (min. én gang), genoprettes ved Long Rest. Desuden reducerer du dit Exhaustion-niveau med 1, hver gang du fuldfører en Short Rest."],
  "Relentless Hunter Lvl13":["Taking damage can't break your Concentration on Hunter's Mark.","At tage skade kan ikke bryde din Concentration på Hunter's Mark."],
  "Nature's Veil Lvl14":["Bonus Action: give yourself the Invisible condition until the end of your next turn, a number of times equal to your WIS mod (min. once), regain on Long Rest.","Bonus-handling: giv dig selv Invisible indtil slutningen af din næste tur, et antal gange svarende til dit WIS-mod (min. én gang), genoprettes ved Long Rest."],
  "Precise Hunter Lvl17":["Advantage on attack rolls against the creature currently marked by your Hunter's Mark.","Advantage på angrebstjek mod det væsen der i øjeblikket er mærket af dit Hunter's Mark."],
  "Feral Senses Lvl18":["You have Blindsight with a range of 30 ft.","Du har Blindsight med en rækkevidde på 30 ft."],
  "Foe Slayer Lvl20":["The damage die of your Hunter's Mark is a d10 rather than a d6.","Skadeterningen for dit Hunter's Mark er en d10 i stedet for en d6."],
  "Divine Order Lvl1":["Choose Protector (martial) or Thaumaturge (extra cantrip).","Vælg Protector (kamp) eller Thaumaturge (ekstra cantrip)."],
  "Sear Undead Lvl5":["Whenever you use Turn Undead, roll a number of d8s equal to your Wisdom modifier (min. 1d8) and add them together; each Undead that fails its save against that use takes Radiant damage equal to the total.","Når du bruger Turn Undead, kast et antal d8'ere svarende til dit Wisdom-modifier (min. 1d8) og læg dem sammen; hvert Undead der fejler sit save mod det brug tager Radiant-skade svarende til summen."],
  "Divine Intervention Lvl10":["Magic action: choose a Cleric spell of level 5 or lower that doesn't require a Reaction, and cast it without a spell slot or components. Once per Long Rest.","Magisk handling: vælg en Cleric-spell af niveau 5 eller lavere der ikke kræver en Reaction, og cast den uden spell slot eller komponenter. Én gang pr. Long Rest."],
  "Improved Blessed Strikes Lvl14":["Your Blessed Strikes option grows more powerful: Divine Strike's extra damage increases to 2d8, or Potent Spellcasting also grants Temp HP (twice your WIS modifier) when a Cleric cantrip damages a creature.","Din Blessed Strikes-mulighed bliver stærkere: Divine Strikes ekstra skade stiger til 2d8, eller Potent Spellcasting giver også midlertidige HP (dobbelt dit WIS-modifier) når en Cleric-cantrip giver skade."],
  "Greater Divine Intervention Lvl20":["When you use Divine Intervention, you can choose Wish as the spell. If you do, you can't use Divine Intervention again until you finish 2d4 Long Rests.","Når du bruger Divine Intervention, kan du vælge Wish som spell. Hvis du gør det, kan du ikke bruge Divine Intervention igen før du har fuldført 2d4 Long Rests."],
  "Paladin's Smite Lvl2":["You always have the Divine Smite spell prepared, and you can cast it once without a spell slot; regain that ability on a Long Rest. Divine Smite: Bonus Action right after a melee/unarmed hit: 2d8 Radiant damage (+1d8 vs. a Fiend or Undead), +1d8 per spell slot level above 1st.","Du har altid Divine Smite-spellet forberedt, og du kan caste det én gang uden et spell slot; genopret den evne ved en Long Rest. Divine Smite: Bonus-handling lige efter et ramt nærkamps-/ubevæbnet angreb: 2d8 Radiant-skade (+1d8 mod en Fiend eller Undead), +1d8 pr. spell slot-niveau over 1."],
  "Channel Divinity Lvl2":["Magic action: channel divine energy to fuel a chosen effect - starts with Divine Spark (heal or deal Necrotic/Radiant damage) and Turn Undead (Frighten nearby Undead); gain more options and uses at higher levels.","Magisk handling: kanaliser guddommelig energi til en valgt effekt - starter med Divine Spark (hel eller giv Necrotic/Radiant-skade) og Turn Undead (gør nærliggende Undead Frightened); få flere muligheder og brug ved højere niveauer."],
  "Channel Divinity Lvl3":["Channel divine energy for a chosen effect - starts with Divine Sense (detect Celestials/Fiends/Undead); your Oath grants more options at higher levels.","Kanaliser guddommelig energi til en valgt effekt - starter med Divine Sense (opdag Celestials/Fiends/Undead); dit Oath giver flere muligheder ved højere niveauer."],
  "Faithful Steed Lvl5":["You always have the Find Steed spell prepared, and you can cast it once without a spell slot; regain that ability on a Long Rest.","Du har altid Find Steed-spellet forberedt, og du kan caste det én gang uden et spell slot; genopret den evne ved en Long Rest."],
  "Abjure Foes Lvl9":["Magic action: expend a use of Channel Divinity to Frighten a number of creatures equal to your Charisma modifier (min. 1) within 60 ft; Wisdom save or Frightened for 1 minute (or until it takes damage). While Frightened this way, a target can only move, take an action, or take a Bonus Action on its turn.","Magisk handling: brug et Channel Divinity-brug til at give et antal væsener svarende til dit Charisma-modifier (min. 1) inden for 60 ft Frightened; Wisdom save eller Frightened i 1 minut (eller til det tager skade). Mens Frightened på denne måde kan et mål kun bevæge sig, tage en handling, eller tage en bonus-handling på sin tur."],
  "Aura of Courage Lvl10":["You and allies in your Aura of Protection have Immunity to the Frightened condition. If a Frightened ally enters the aura, the condition has no effect on them while there.","Du og allierede i din Aura of Protection har Immunitet mod Frightened. Hvis en Frightened allieret træder ind i auraen, har tilstanden ingen effekt på dem mens de er der."],
  "Radiant Strikes Lvl11":["Your melee weapon and Unarmed Strike hits deal an extra 1d8 Radiant damage.","Dine nærkamps-våben- og Unarmed Strike-træf giver ekstra 1d8 Radiant-skade."],
  "Restoring Touch Lvl14":["When you use Lay on Hands on a creature, you can also remove Blinded, Charmed, Deafened, Frightened, Paralyzed, or Stunned from it; spend 5 HP from the Lay on Hands pool per condition removed (this doesn't also restore HP).","Når du bruger Lay on Hands på et væsen, kan du også fjerne Blinded, Charmed, Deafened, Frightened, Paralyzed eller Stunned fra det; brug 5 HP fra Lay on Hands-puljen pr. fjernet tilstand (genopretter ikke også HP)."],
  "Aura Expansion Lvl18":["Your Aura of Protection is now a 30-foot Emanation.","Din Aura of Protection er nu en 30-fods udstråling."],
  "Druidic language":["You know the secret language of druids.","Du kan druidernes hemmelige sprog."],
  "Wild Companion Lvl2":["Magic action: expend a spell slot or a Wild Shape use to cast Find Familiar without Material components. The familiar is Fey and disappears when you finish a Long Rest.","Magisk handling: brug et spell slot eller et Wild Shape-brug til at caste Find Familiar uden Material-komponenter. Familiaren er Fey og forsvinder når du fuldfører en Long Rest."],
  "Wild Resurgence Lvl5":["Once on each of your turns, if you have no uses of Wild Shape left, you can give yourself one use by expending a spell slot (no action required). You can also expend a use of Wild Shape to give yourself a level 1 spell slot (no action required), but not again until a Long Rest.","Én gang på hver af dine ture, hvis du ikke har flere Wild Shape-brug tilbage, kan du give dig selv ét brug ved at bruge et spell slot (ingen handling krævet). Du kan også bruge et Wild Shape-brug til at give dig selv et niveau 1 spell slot (ingen handling krævet), men ikke igen før en Long Rest."],
  "Elemental Fury Lvl7":["Choose Potent Spellcasting (add your Wisdom modifier to Druid cantrip damage) or Primal Strike (once per turn, a hit with a weapon or a Beast form's attack in Wild Shape deals an extra 1d8 Cold/Fire/Lightning/Thunder damage, your choice).","Vælg Potent Spellcasting (læg dit Wisdom-modifier til Druid-cantrip-skade) eller Primal Strike (én gang pr. tur giver et træf med et våben eller en Beast-forms angreb i Wild Shape ekstra 1d8 Cold/Fire/Lightning/Thunder-skade, dit valg)."],
  "Improved Elemental Fury Lvl15":["Your Elemental Fury option grows more powerful: Potent Spellcasting's cantrips with a range of 10+ ft gain +300 ft range, or Primal Strike's extra damage increases to 2d8.","Din Elemental Fury-mulighed bliver stærkere: Potent Spellcastings cantrips med rækkevidde 10+ ft får +300 ft rækkevidde, eller Primal Strikes ekstra skade stiger til 2d8."],
  "Beast Spells Lvl18":["While using Wild Shape, you can cast spells in Beast form, except spells with a costly or consumed Material component.","Mens du bruger Wild Shape, kan du caste spells i Beast-form, undtagen spells med en dyr eller forbrugt Material-komponent."],
  "Archdruid Lvl20":["Evergreen Wild Shape: on Initiative with no Wild Shape uses left, regain one. Nature Magician: convert unexpended Wild Shape uses into a single spell slot (2 spell levels per use, no action), once per Long Rest. Longevity: you age at a tenth the normal rate.","Evergreen Wild Shape: ved Initiativ uden Wild Shape-brug tilbage, genopret ét. Nature Magician: konverter ubrugte Wild Shape-brug til ét spell slot (2 spell-niveauer pr. brug, ingen handling), én gang pr. Long Rest. Longevity: du ældes med en tiendedel af normal hastighed."],
  "Eldritch Invocations Lvl1":["Special magical abilities you pick and can swap.","Særlige magiske evner du vælger og kan bytte."],
  "Epic Boon Lvl19":["Gain an Epic Boon feat (see Feats) or another feat of your choice for which you qualify.","Få et Epic Boon-feat (se Feats) eller et andet valgfrit feat du kvalificerer til."],
  "Expertise Lvl1":["Double your proficiency bonus in chosen skills.","Fordobl din proficiency bonus i valgte færdigheder."],
  "Expertise Lvl2":["Gain Expertise (double proficiency bonus) in two skill proficiencies of your choice.","Få Expertise (dobbelt proficiency bonus) i to valgfrie færdigheds-proficiencies."],
  "Expertise Lvl9":["Gain Expertise in two more skill proficiencies of your choice.","Få Expertise i to yderligere valgfrie færdigheds-proficiencies."],
  "Font of Inspiration Lvl5":["You regain all expended Bardic Inspiration dice on a Short or Long Rest. You can also expend a spell slot (no action required) to regain one expended use.","Du genopretter alle brugte Bardic Inspiration-terninger ved en Short eller Long Rest. Du kan også bruge et spell slot (ingen handling krævet) til at genoprette ét brugt anvendelse."],
  "Countercharm Lvl7":["Reaction when you or a creature within 30 ft fails a save against a Charmed or Frightened effect: the save is rerolled with Advantage.","Reaktion når du eller et væsen inden for 30 ft fejler et save mod en Charmed- eller Frightened-effekt: savet kastes om med Advantage."],
  "Magical Secrets Lvl10":["Whenever your Prepared Spells number increases (including now), you can choose new prepared spells from the Bard, Cleric, Druid, or Wizard list; they count as Bard spells for you.","Når dit antal forberedte spells stiger (inkl. nu), kan du vælge nye forberedte spells fra Bard-, Cleric-, Druid- eller Wizard-listen; de tæller som Bard-spells for dig."],
  "Superior Inspiration Lvl18":["When you roll Initiative, you regain expended Bardic Inspiration dice until you have two if you have fewer.","Når du slår Initiativ, genopretter du brugte Bardic Inspiration-terninger til du har to, hvis du har færre."],
  "Words of Creation Lvl20":["You always have Power Word Heal and Power Word Kill prepared. When you cast either, you can target a second creature within 10 ft of the first.","Du har altid Power Word Heal og Power Word Kill forberedt. Når du caster en af dem, kan du ramme et andet væsen inden for 10 ft af det første."],
  "Extra Attack Lvl5":["Attack twice when you take the Attack action.","Angrib to gange når du tager Attack-handlingen."],
  "Favored Enemy Lvl1":["Always have Hunter's Mark ready to track prey.","Har altid Hunter's Mark klar til at spore bytte."],
  "Fighting Style Lvl1":["A combat specialty like Archery or Defense.","En kamp-specialitet som Archery eller Defense."],
  "Tactical Mind Lvl2":["When you fail an ability check, you can expend a use of Second Wind to add 1d10 to the check instead of regaining HP; if it still fails, the use isn't expended.","Når du fejler et ability-check, kan du bruge et Second Wind-brug til at lægge 1d10 til checket i stedet for at genoprette HP; hvis det stadig fejler, bruges brugen ikke."],
  "Tactical Shift Lvl5":["Whenever you activate Second Wind with a Bonus Action, you can move up to half your Speed without provoking Opportunity Attacks.","Når du aktiverer Second Wind med en bonus-handling, kan du bevæge dig op til halv Speed uden at fremkalde lejlighedsangreb."],
  "Indomitable Lvl9":["If you fail a saving throw, you can reroll it with a bonus equal to your Fighter level (must use the new roll). 1 use, 2 at level 13, 3 at level 17; regain on a Long Rest.","Hvis du fejler et saving throw, kan du kaste det om med en bonus svarende til dit Fighter-niveau (skal bruge det nye resultat). 1 brug, 2 ved niveau 13, 3 ved niveau 17; genoprettes ved en Long Rest."],
  "Tactical Master Lvl9":["When you attack with a weapon whose mastery property you can use, you can replace that property with Push, Sap, or Slow for that attack.","Når du angriber med et våben hvis mastery-egenskab du kan bruge, kan du erstatte den egenskab med Push, Sap eller Slow for det angreb."],
  "Two Extra Attacks Lvl11":["You can attack three times instead of once whenever you take the Attack action on your turn.","Du kan angribe tre gange i stedet for én, når du udfører Attack-handlingen på din tur."],
  "Studied Attacks Lvl13":["If you miss with an attack roll against a creature, you have Advantage on your next attack roll against that creature before the end of your next turn.","Hvis du misser et angrebstjek mod et væsen, har du Advantage på dit næste angrebstjek mod det væsen inden slutningen af din næste tur."],
  "Three Extra Attacks Lvl20":["You can attack four times instead of once whenever you take the Attack action on your turn.","Du kan angribe fire gange i stedet for én, når du udfører Attack-handlingen på din tur."],
  "Font of Magic Lvl2":["Sorcery Points to make or convert spell slots.","Sorcery Points til at lave eller omdanne spell slots."],
  "Innate Sorcery Lvl1":["Bonus Action, 1 minute: +1 to your spell save DC and Advantage on attack rolls of Sorcerer spells you cast. Twice per Long Rest.","Bonus-handling, 1 minut: +1 til din spell save DC og Advantage på angrebstjek for Sorcerer-spells du caster. To gange pr. Long Rest."],
  "Jack of All Trades Lvl2":["Add half your proficiency to non-proficient checks.","Læg halv proficiency til tjek du ikke er proficient i."],
  "Lay on Hands 5x level HP":["A pool of healing you touch into yourself or allies.","En pulje af healing du giver dig selv eller allierede ved berøring."],
  "Magical Cunning Lvl2":["Regain some Pact Magic spell slots once per long rest.","Få nogle Pact Magic-spell slots tilbage én gang pr. Long Rest."],
  "Contact Patron Lvl9":["You always have Contact Other Plane prepared and can cast it without a spell slot, automatically succeeding on the spell's saving throw. Once per Long Rest.","Du har altid Contact Other Plane forberedt og kan caste det uden et spell slot, og består automatisk spellets saving throw. Én gang pr. Long Rest."],
  "Mystic Arcanum Lvl11":["Choose one level 6 Warlock spell as your arcanum. Cast it once without a spell slot; regain that ability on a Long Rest.","Vælg et niveau 6 Warlock-spell som dit arcanum. Cast det én gang uden et spell slot; genopret den evne ved en Long Rest."],
  "Mystic Arcanum Lvl13":["Choose a level 7 Warlock spell as another arcanum, castable once without a spell slot per Long Rest.","Vælg et niveau 7 Warlock-spell som endnu et arcanum, der kan castes én gang uden et spell slot pr. Long Rest."],
  "Mystic Arcanum Lvl15":["Choose a level 8 Warlock spell as another arcanum, castable once without a spell slot per Long Rest.","Vælg et niveau 8 Warlock-spell som endnu et arcanum, der kan castes én gang uden et spell slot pr. Long Rest."],
  "Mystic Arcanum Lvl17":["Choose a level 9 Warlock spell as another arcanum, castable once without a spell slot per Long Rest.","Vælg et niveau 9 Warlock-spell som endnu et arcanum, der kan castes én gang uden et spell slot pr. Long Rest."],
  "Eldritch Master Lvl20":["When you use Magical Cunning, you regain all expended Pact Magic spell slots instead of only half.","Når du bruger Magical Cunning, genopretter du alle brugte Pact Magic-spell slots i stedet for kun halvdelen."],
  "Martial Arts Lvl1":["Unarmed strikes and monk weapons scale with a die.","Ubevæbnede slag og munkevåben skalerer med en terning."],
  "Unarmored Movement Lvl2":["Speed increases while you aren't wearing armor or wielding a Shield; the bonus grows as you gain Monk levels (+10 ft at 2, +15 at 6, +20 at 10, +25 at 14, +30 at 18).","Speed stiger når du ikke bærer rustning eller fører et skjold; bonussen vokser med Monk-niveau (+10 ft ved 2, +15 ved 6, +20 ved 10, +25 ved 14, +30 ved 18)."],
  "Uncanny Metabolism Lvl2":["When you roll Initiative, you can regain all expended Focus Points. When you do, roll your Martial Arts die and regain that many Hit Points plus your Monk level. Once per Long Rest.","Når du slår Initiativ, kan du genoprette alle brugte Focus Points. Når du gør det, slå din Martial Arts-terning og genopret det antal Hit Points plus dit Monk-niveau. Én gang pr. Long Rest."],
  "Deflect Attacks Lvl3":["Reaction when hit by an attack dealing Bludgeoning/Piercing/Slashing damage: reduce the damage by 1d10 + DEX mod + Monk level. If reduced to 0, expend 1 Focus Point to redirect force at a creature within 5 ft (melee) or 60 ft (ranged): DEX save or take damage equal to two Martial Arts die rolls + DEX mod, of the attack's type.","Reaktion når du rammes af et angreb med Bludgeoning/Piercing/Slashing-skade: reducer skaden med 1d10 + DEX-mod + Monk-niveau. Reduceres den til 0, kan du bruge 1 Focus Point til at omdirigere kraften mod et væsen inden for 5 ft (nærkamp) eller 60 ft (afstand): DEX save eller tag skade svarende til to Martial Arts-terningeslag + DEX-mod, af angrebets type."],
  "Slow Fall Lvl4":["Reaction when you fall: reduce the fall damage you take by an amount equal to five times your Monk level.","Reaktion når du falder: reducer faldskaden du tager med et beløb svarende til fem gange dit Monk-niveau."],
  "Empowered Strikes Lvl6":["Whenever you deal damage with your Unarmed Strike, it can deal Force damage instead of its normal type, your choice.","Når du giver skade med dit Unarmed Strike, kan det give Force-skade i stedet for dets normale type, dit valg."],
  "Evasion Lvl7":["When subjected to an effect that allows a Dexterity save for half damage, you instead take no damage on a success and only half on a failure (no benefit if Incapacitated).","Når du udsættes for en effekt der giver et Dexterity save for halv skade, tager du i stedet ingen skade ved succes og kun halv ved fejl (ingen fordel hvis du er Incapacitated)."],
  "Acrobatic Movement Lvl9":["While not wearing armor or wielding a Shield, you can move along vertical surfaces and across liquids on your turn without falling.","Mens du ikke bærer rustning eller fører et skjold, kan du bevæge dig langs lodrette overflader og hen over væsker på din tur uden at falde."],
  "Heightened Focus Lvl10":["Your Focus Point features improve: Flurry of Blows makes three Unarmed Strikes instead of two; Patient Defense grants Temp HP equal to two Martial Arts die rolls; Step of the Wind lets you bring a willing Large-or-smaller creature within 5 ft along with you.","Dine Focus Point-evner forbedres: Flurry of Blows udfører tre Unarmed Strikes i stedet for to; Patient Defense giver midlertidige HP svarende til to Martial Arts-terningeslag; Step of the Wind lader dig tage et villigt Large-eller-mindre væsen inden for 5 ft med dig."],
  "Self-Restoration Lvl10":["End the Charmed, Frightened, or Poisoned condition on yourself at the end of each of your turns. Forgoing food and drink doesn't give you levels of Exhaustion.","Afslut Charmed, Frightened eller Poisoned på dig selv i slutningen af hver af dine ture. At undvære mad og drikke giver dig ikke niveauer af Exhaustion."],
  "Deflect Energy Lvl13":["You can now use Deflect Attacks against attacks that deal any damage type, not just Bludgeoning, Piercing, or Slashing.","Du kan nu bruge Deflect Attacks mod angreb der giver enhver skadetype, ikke kun Bludgeoning, Piercing eller Slashing."],
  "Disciplined Survivor Lvl14":["Proficiency in all saving throws. Whenever you fail a saving throw, you can expend 1 Focus Point to reroll it, and you must use the new roll.","Proficiency i alle saving throws. Når du fejler et saving throw, kan du bruge 1 Focus Point til at kaste det om, og du skal bruge det nye resultat."],
  "Perfect Focus Lvl15":["When you roll Initiative and don't use Uncanny Metabolism, you regain expended Focus Points until you have 4 if you have 3 or fewer.","Når du slår Initiativ og ikke bruger Uncanny Metabolism, genopretter du brugte Focus Points til du har 4, hvis du har 3 eller færre."],
  "Superior Defense Lvl18":["At the start of your turn, you can expend 3 Focus Points to bolster yourself for 1 minute or until you have the Incapacitated condition: Resistance to all damage except Force.","I starten af din tur kan du bruge 3 Focus Points til at styrke dig selv i 1 minut eller til du får Incapacitated: Resistance mod al skade undtagen Force."],
  "Body and Mind Lvl20":["Your Dexterity and Wisdom scores increase by 4, to a maximum of 25.","Din Dexterity- og Wisdom-score stiger med 4, til et maksimum på 25."],
  "Metamagic Lvl2":["Choose two Metamagic options to bend your spells: twin, quicken, subtle and more.","Vælg to Metamagic-muligheder til at bøje dine spells: twin, quicken, subtle m.m."],
  "Sorcerous Restoration Lvl5":["When you finish a Short Rest, you can regain expended Sorcery Points, up to a number equal to half your Sorcerer level (round down). Once per Long Rest.","Når du fuldfører en Short Rest, kan du genoprette brugte Sorcery Points, op til et antal svarende til halvdelen af dit Sorcerer-niveau (rund ned). Én gang pr. Long Rest."],
  "Sorcery Incarnate Lvl7":["If you have no uses of Innate Sorcery left, you can activate it anyway by spending 2 Sorcery Points as part of the Bonus Action. While Innate Sorcery is active, you can use up to two Metamagic options on each spell you cast.","Hvis du ikke har flere brug af Innate Sorcery, kan du alligevel aktivere den ved at bruge 2 Sorcery Points som del af bonus-handlingen. Mens Innate Sorcery er aktiv, kan du bruge op til to Metamagic-muligheder på hvert spell du caster."],
  "Metamagic Lvl10":["Learn two more Metamagic options.","Lær to yderligere Metamagic-muligheder."],
  "Metamagic Lvl17":["Learn two more Metamagic options.","Lær to yderligere Metamagic-muligheder."],
  "Arcane Apotheosis Lvl20":["While your Innate Sorcery feature is active, you can use one Metamagic option on each of your turns without spending Sorcery Points on it.","Mens din Innate Sorcery-feature er aktiv, kan du bruge én Metamagic-mulighed på hver af dine ture uden at bruge Sorcery Points på den."],
  "Monks Focus Lvl2":["Focus Points power Flurry, Patient Defense and Step of the Wind.","Focus Points driver Flurry, Patient Defense og Step of the Wind."],
  "Pact Magic short rest recharge":["Your spell slots return after a short rest.","Dine spell slots vender tilbage efter en Short Rest."],
  "Primal Order Lvl1":["Choose Magician (extra cantrip) or Warden (martial).","Vælg Magician (ekstra cantrip) eller Warden (kamp)."],
  "Rage Lvl1":["Bonus Action (not in Heavy armor): Resistance to Bludgeoning/Piercing/Slashing damage, bonus damage on Strength attacks, Advantage on Strength checks and saves, can't Concentrate or cast spells. Lasts until the end of your next turn; extend by attacking, forcing a save, or a Bonus Action, up to 10 minutes total.","Bonus-handling (ikke i Heavy rustning): Modstand mod Bludgeoning/Piercing/Slashing-skade, bonus-skade på Strength-angreb, Fordel på Strength-checks og saves, kan ikke Concentrate eller caste spells. Varer til slutningen af din næste tur; forlænges ved at angribe, tvinge et save, eller en bonus-handling, op til 10 minutter i alt."],
  "Reckless Attack Lvl2":["Attack with advantage, but enemies hit you more easily.","Angrib med fordel, men fjender rammer dig lettere."],
  "Second Wind Lvl1":["Bonus Action: regain 1d10+Fighter level HP. 2 uses at level 1 (3 at level 4, 4 at level 10); regain 1 per Short Rest, all per Long Rest.","Bonus-handling: genopret 1d10+Fighter-niveau HP. 2 brug ved niveau 1 (3 ved niveau 4, 4 ved niveau 10); genopret 1 pr. Short Rest, alle pr. Long Rest."],
  "Sneak Attack 1d6 per 2 levels":["Bonus damage when you have advantage or an ally is near.","Bonus-skade når du har fordel eller en allieret er nær."],
  "Steady Aim Lvl3":["Bonus Action: give yourself Advantage on your next attack roll this turn. Only if you haven't moved this turn; after using it, your Speed is 0 until the end of the current turn.","Bonus-handling: giv dig selv Advantage på dit næste angrebstjek denne tur. Kun hvis du ikke har bevæget dig denne tur; efter brug er din Speed 0 til slutningen af den nuværende tur."],
  "Cunning Strike Lvl5":["When you deal Sneak Attack damage, you can forgo some of its dice to add a Cunning Strike effect (DC 8 + DEX mod + Prof. Bonus if it needs a save): Poison (Cost 1d6, requires a Poisoner's Kit): Constitution save or Poisoned for 1 minute. Trip (Cost 1d6): Large-or-smaller target makes a Dexterity save or is knocked Prone.","Når du giver Sneak Attack-skade, kan du undvære nogle af terningerne for at tilføje en Cunning Strike-effekt (DC 8 + DEX-mod + Prof. Bonus hvis den kræver et save): Poison (Pris 1d6, kræver et Poisoner's Kit): Constitution save eller Poisoned i 1 minut. Trip (Pris 1d6): Large-eller-mindre mål laver et Dexterity save eller bliver Prone."],
  "Expertise Lvl6":["Gain Expertise in two more skill proficiencies of your choice.","Få Expertise i to yderligere valgfrie færdigheds-proficiencies."],
  "Reliable Talent Lvl7":["Whenever you make an ability check using a skill or tool proficiency you have, treat a d20 roll of 9 or lower as a 10.","Når du laver et ability-check med en færdigheds- eller værktøjs-proficiency du har, behandl et d20-slag på 9 eller derunder som en 10."],
  "Improved Cunning Strike Lvl11":["You can use up to two Cunning Strike effects when you deal Sneak Attack damage, paying the die cost for each.","Du kan bruge op til to Cunning Strike-effekter når du giver Sneak Attack-skade, ved at betale terningeprisen for hver."],
  "Devious Strikes Lvl14":["Three more Cunning Strike options: Daze (Cost 2d6): Constitution save or the target can only move, take an action, OR a Bonus Action on its next turn. Knock Out (Cost 6d6): Constitution save or Unconscious for 1 minute (or until it takes damage). Obscure (Cost 3d6): Dexterity save or Blinded until the end of its next turn.","Tre flere Cunning Strike-muligheder: Daze (Pris 2d6): Constitution save eller målet kan kun bevæge sig, tage en handling, ELLER en bonus-handling på sin næste tur. Knock Out (Pris 6d6): Constitution save eller Unconscious i 1 minut (eller til det tager skade). Obscure (Pris 3d6): Dexterity save eller Blinded indtil slutningen af dets næste tur."],
  "Slippery Mind Lvl15":["Gain proficiency in Wisdom and Charisma saving throws.","Få proficiency i Wisdom- og Charisma-saving throws."],
  "Elusive Lvl18":["No attack roll can have Advantage against you unless you have the Incapacitated condition.","Intet angrebstjek kan have Advantage mod dig medmindre du har Incapacitated."],
  "Stroke of Luck Lvl20":["If you fail a D20 Test, you can turn the roll into a 20. Once per Short or Long Rest.","Hvis du fejler et D20 Test, kan du gøre resultatet til en 20. Én gang pr. Short eller Long Rest."],
  "Spell Mastery Lvl18":["Cast chosen 1st/2nd-level spells at will.","Cast valgte 1./2.-niveau spells frit."],
  "Spellcasting CHA":["You cast spells using Charisma.","Du caster spells med Charisma."],
  "Spellcasting CHA Lvl1":["You cast spells using Charisma.","Du caster spells med Charisma."],
  "Spellcasting INT":["Prepare a fresh set of Wizard spells each day.","Forbered et nyt sæt Wizard-spells hver dag."],
  "Spellcasting WIS Lvl1":["You cast spells using Wisdom.","Du caster spells med Wisdom."],
  "Stunning Strike Lvl5":["Spend Focus to try to stun a creature you hit.","Brug Focus for at forsøge at stunne et væsen du rammer."],
  "Subclass Lvl3":["Choose a subclass that shapes your character.","Vælg en underklasse der former din karakter."],
  "Fast Movement Lvl5":["Speed +10 ft while you aren't wearing Heavy armor.","Speed +10 ft når du ikke bærer Heavy rustning."],
  "Feral Instinct Lvl7":["Advantage on Initiative rolls.","Fordel på Initiativ-slag."],
  "Instinctive Pounce Lvl7":["As part of the Bonus Action to enter your Rage, you can move up to half your Speed.","Som del af bonus-handlingen til at gå i Rage kan du bevæge dig op til halv Speed."],
  "Brutal Strike Lvl9":["Forgo Reckless Attack's Advantage on one Strength-based attack roll: on a hit, +1d10 damage of the weapon's/Unarmed Strike's type, plus one Brutal Strike effect (Forceful Blow: push 15 ft; Hamstring Blow: Speed -15 ft until the start of its next turn).","Opgiv Reckless Attacks Fordel på ét Strength-baseret angrebstjek: ved træf, +1d10 skade af våbnets/Unarmed Strikes type, plus én Brutal Strike-effekt (Forceful Blow: skub 15 ft; Hamstring Blow: Speed -15 ft indtil starten af dets næste tur)."],
  "Relentless Rage Lvl11":["If you drop to 0 HP while Raging (without dying outright), DC 10 Constitution save to instead change your HP to twice your Barbarian level. DC +5 each further use this Rage, resets to 10 on a Short or Long Rest.","Hvis du falder til 0 HP mens du raser (uden at dø direkte), DC 10 Constitution save for i stedet at ændre din HP til dobbelt dit Barbarian-niveau. DC +5 for hver yderligere brug i dette raseri, nulstilles til 10 ved en Short eller Long Rest."],
  "Improved Brutal Strike Lvl13":["Two more Brutal Strike options: Staggering Blow (target has Disadvantage on its next save and can't make Opportunity Attacks until the start of its next turn) and Sundering Blow (the next attack roll against the target by another creature before your next turn gets a +5 bonus).","To flere Brutal Strike-muligheder: Staggering Blow (målet får Disadvantage på sit næste save og kan ikke lave Opportunity Attacks indtil starten af dets næste tur) og Sundering Blow (det næste angrebstjek mod målet fra et andet væsen før din næste tur får en +5-bonus)."],
  "Persistent Rage Lvl15":["When you roll Initiative, you can regain all expended uses of Rage (once per Long Rest). Your Rage now lasts 10 minutes without needing to extend it, and only ends early if you fall Unconscious or don Heavy armor.","Når du slår Initiativ, kan du genoprette alle brugte anvendelser af Rage (én gang pr. Long Rest). Dit raseri varer nu 10 minutter uden at skulle forlænges, og slutter kun tidligt hvis du bliver Unconscious eller tager Heavy rustning på."],
  "Improved Brutal Strike Lvl17":["The extra damage of your Brutal Strike increases to 2d10, and you can use two different Brutal Strike effects whenever you use the feature.","Den ekstra skade fra din Brutal Strike stiger til 2d10, og du kan bruge to forskellige Brutal Strike-effekter hver gang du bruger featuren."],
  "Indomitable Might Lvl18":["If your total for a Strength check or Strength saving throw is less than your Strength score, you can use that score in place of the total.","Hvis dit resultat for et Strength-check eller Strength saving throw er mindre end din Strength-score, kan du bruge den score i stedet for resultatet."],
  "Primal Champion Lvl20":["Your Strength and Constitution scores increase by 4, to a maximum of 25.","Din Strength- og Constitution-score stiger med 4, til et maksimum på 25."],
  "Thieves Cant":["A secret code of rogues and criminals.","En hemmelig kode blandt tyve og kriminelle."],
  "Unarmored Defense AC=10+DEX+CON":["Your AC is 10 + DEX + CON while wearing no armor.","Din AC er 10 + DEX + CON når du ikke bærer rustning."],
  "Unarmored Defense AC=10+DEX+WIS":["Your AC is 10 + DEX + WIS while wearing no armor.","Din AC er 10 + DEX + WIS når du ikke bærer rustning."],
  "Uncanny Dodge Lvl5":["Halve the damage from one attack as a reaction.","Halvér skaden fra ét angreb som en reaktion."],
  "Weapon Mastery x2":["Use the mastery property of 2 weapons.","Brug mastery-egenskaben på 2 våben."],
  "Weapon Mastery x3":["Use the mastery property of 3 weapons.","Brug mastery-egenskaben på 3 våben."],
  "Wild Shape Lvl2":["Transform into beasts you have learned.","Forvandl til dyr du har lært."],
};

export const SUBCLASS_DESC_DA={
  // Barbarian
  "Path of the Berserker":"Frenzy for ekstra angreb og frygt.",
  "Path of the Wild Heart":"Dyreånd-kræfter mens du raser.",
  "Path of the World Tree":"Livgivende vitalitet og gren-teleports.",
  "Path of the Zealot":"Guddommeligt raseri; svær at dræbe.",
  // Bard
  "College of Dance":"Adræt rustningsfrit forsvar og mobil inspiration.",
  "College of Glamour":"Fe-charme og fængslende optræden.",
  "College of Lore":"Ekstra færdigheder og Cutting Words.",
  "College of Valor":"Rustning, våben og kamp-inspiration.",
  // Cleric
  "Life Domain":"Den bedste healing i spillet.",
  "Light Domain":"Strålende ild og Warding Flare.",
  "Trickery Domain":"Illusioner, snig og dobbeltgængere.",
  "War Domain":"Våbendygtighed og krigs-velsignelser.",
  // Druid
  "Circle of the Land":"Bonus-spells fra valgt terræn.",
  "Circle of the Moon":"Stærke Wild Shape-kampformer.",
  "Circle of the Sea":"Storm, bølger og havets raseri.",
  "Circle of the Stars":"Stjernebilled-former.",
  // Fighter
  "Battle Master":"Taktiske manøvrer med superioritetsterninger.",
  "Champion":"Kritiske træf på 19-20.",
  "Eldritch Knight":"Wizard-spells plus våben.",
  "Psi Warrior":"Telekinetiske psioniske slag og skjolde.",
  // Monk
  "Warrior of Mercy":"Helbredende hænder eller skadende berøring.",
  "Warrior of Shadow":"Mørke, snig og skygge-teleports.",
  "Warrior of the Elements":"Elementinfunderede slag.",
  "Warrior of the Open Hand":"Klassisk kampkunst-mester.",
  // Paladin
  "Oath of Devotion":"Beskyttelse, ærlighed og helligt våben.",
  "Oath of Glory":"Atletisk fortræffelighed og heltemod.",
  "Oath of the Ancients":"Naturmagi og fe-lys.",
  "Oath of Vengeance":"Ubønhørlig jæger af ugerningsmænd.",
  // Ranger
  "Beast Master":"En loyal dyrekammerat kæmper med dig.",
  "Fey Wanderer":"Fe-charme og sindsbeskyttelse.",
  "Gloom Stalker":"Dødbringende baghold i mørke.",
  "Hunter":"Colossus Slayer og monster-dræbertaktik.",
  // Rogue
  "Arcane Trickster":"Snigende wizard-spells og Mage Hand-tricks.",
  "Assassin":"Dødbringende slag i overraskelsesrunden.",
  "Soulknife":"Psykiske blade og telepati.",
  "Thief":"Fast Hands og suveræn klatring.",
  // Sorcerer
  "Aberrant Sorcery":"Psioniske sindskræfter.",
  "Clockwork Sorcery":"Orden, balance og genoprettede kast.",
  "Draconic Sorcery":"Drage-hårdførhed og elementkraft.",
  "Wild Magic Sorcery":"Kaotiske magiske udladninger.",
  // Warlock
  "Archfey Patron":"Fe-teleports og forheksende magi.",
  "Celestial Patron":"Helbredende lys fra oven.",
  "Fiend Patron":"Ild, midlertidige HP og mørke aftaler.",
  "Great Old One Patron":"Psykiske hvisken og telepati.",
  // Wizard
  "Abjurer":"Beskyttende Arcane Ward opsuger skade.",
  "Diviner":"Portent: forudse og erstat terningkast.",
  "Evoker":"Form dine besværgelser uden om allierede.",
  "Illusionist":"Mester i forbedrede illusioner.",
};

// Arcana Unleashed feats + subclass blurbs (Danish)
Object.assign(FEATDESC_DA,{"Arcane Artist": "Lær Minor Illusion (INT/WIS/CHA). Inspiring Magic: når du caster en Illusion-spell, får en allieret inden for 30 ft der kan se dig Heroic Inspiration (én gang pr. Long Rest).", "Arcane Eloquence": "Lær Vicious Mockery (INT/WIS/CHA). Smooth Talker: læg 1d4 til CHA-checks (Deception, Intimidation eller Persuasion).", "Arcane Infiltrator": "Lær Friends (INT/WIS/CHA). Cunning Diversion: Dodge som Bonus Action, Proficiency Bonus gange pr. Long Rest.", "Arcane Omens": "Lær Guidance (INT/WIS/CHA). Helpful Premonition: Reaction når du eller et væsen inden for 30 ft fejler en save: læg 1d4 til savet. Proficiency Bonus gange pr. Long Rest.", "Arcane Overload": "Lær Fire Bolt (INT/WIS/CHA). Power Surge: når du gør skade med en Evocation-spell, læg din Proficiency Bonus til ét skadeslag (én gang pr. Long Rest).", "Arcane Safeguard": "Lær Resistance (INT/WIS/CHA); cast det som Bonus Action Proficiency Bonus gange pr. Long Rest. Sheltering Aid: når du hjælper en allieret med en ability check, får vedkommende Temp HP svarende til din Proficiency Bonus.", "Arcane Undertaker": "Lær en Necromancy-cantrip fra Cleric- eller Wizard-listen (INT/WIS/CHA). Knowledge from the Dead: +1d4 til History- eller Medicine-checks. Understanding of Death: når du Hjælper med at stabilisere et væsen på 0 HP, får du Heroic Inspiration (én gang pr. Long Rest).", "Familiar Friend": "Faithful Companion: Find Familiar er altid forberedt; cast det én gang gratis pr. Long Rest (INT/WIS/CHA). Fortified Familiar: familiarens HP-maks og nuværende HP +2x dit niveau. Helpful Friend: fordel på en færdighedscheck du er proficient i når familiaren er inden for 5 ft (Proficiency Bonus gange pr. Long Rest).", "Portal Jumper": "Otherworldly Resilience: resistens mod nekrotisk, psykisk eller strålende (vælg). Portal Step: brug 15 ft bevægelse til at teleportere til et ledigt felt du kan se inden for 15 ft (Proficiency Bonus gange pr. Long Rest, én gang pr. tur).", "Transmuted Anatomy": "Lengthened Stride: Speed +5 ft. Resilient Anatomy: fordel på saves mod at blive tvunget til at skifte form. Reaction: læg 1d4 til et fejlet CON save (Proficiency Bonus gange pr. Long Rest).", "Abjuration Adept": "Kræver: niveau 4+, Spellcasting. +1 INT, WIS eller CHA (maks 20). Har altid Shield, Lesser Restoration, Protection from Energy, Banishment, Mass Cure Wounds forberedt (efter slot-niveau). Protective Ward: en Abjuration-spell med slot giver dig eller et væsen inden for 30 ft Temp HP = 2x slot-niveau.", "Conjuration Adept": "Kræver: niveau 4+, Spellcasting. +1 INT, WIS eller CHA (maks 20). Har altid Entangle, Misty Step, Conjure Animals, Dimension Door, Conjure Elemental forberedt (efter slot-niveau). Persistent Conjuration: bonus til CON saves for at holde Concentration på Conjuration-spells lig featens ability modifier.", "Divination Adept": "Kræver: niveau 4+, Spellcasting. +1 INT, WIS eller CHA (maks 20). Har altid Detect Evil and Good, Mind Spike, Clairvoyance, Divination, Scrying forberedt (efter slot-niveau). Prescient Intervention: Reaction, giv fordel eller ulempe på en D20 Test inden for 60 ft (én gang pr. Long Rest; genfås ved at caste en Divination-spell med slot).", "Elemental Familiar": "Kræver: niveau 4+, Familiar Friend. +1 til en valgfri ability score (maks 20). Elemental Energy: vælg Acid, Cold, Fire, Lightning eller Thunder når du caster Find Familiar; familiaren får resistens og Energy Pulse (Bonus Action + dens Reaction): 5-ft udstråling, DEX save eller 2d4 skade og Prone (Medium eller mindre).", "Enchantment Adept": "Kræver: niveau 4+, Spellcasting. +1 INT, WIS eller CHA (maks 20). Har altid Dissonant Whispers, Enthrall, Hold Person, Dominate Beast, Modify Memory forberedt (efter slot-niveau). Subtle Enchantments: Enchantment-spells castet med slot kræver ingen V-, S- eller M-komponenter (undtagen dyre/forbrugte).", "Evocation Adept": "Kræver: niveau 4+, Spellcasting. +1 INT, WIS eller CHA (maks 20). Har altid Chromatic Orb, Shatter, Fireball, Vitriolic Sphere, Wall of Force forberedt (efter slot-niveau). Fueled Evocation: én gang pr. tur når en Evocation-spell gør skade, slå op til to ubrugte Hit Dice og læg summen til ét skadeslag.", "Illusion Adept": "Kræver: niveau 4+, Spellcasting. +1 INT, WIS eller CHA (maks 20). Har altid Silent Image, Phantasmal Force, Major Image, Hallucinatory Terrain, Seeming forberedt (efter slot-niveau). Masterful Illusions: Illusion-spells castet med slot kræver ingen V-, S- eller M-komponenter (undtagen dyre/forbrugte); ulempe på Investigation-checks for at gennemskue dem.", "Magic Connoisseur": "Kræver: niveau 4+, Magic Initiate. +1 INT, WIS eller CHA (maks 20). Vælg et niveau 1- og et niveau 2-spell fra din Magic Initiate-liste; altid forberedt, hver kan castes én gang gratis pr. Long Rest. Byt ét ved level-up.", "Necromancy Adept": "Kræver: niveau 4+, Spellcasting. +1 INT, WIS eller CHA (maks 20). Har altid Inflict Wounds, Ray of Enfeeblement, Vampiric Touch, Blight, Raise Dead forberedt (efter slot-niveau). Life Manipulation: en Necromancy-spell med slot lader dig slå op til to ubrugte Hit Dice og få HP = sum + slot-niveau.", "Otherworldly Familiar": "Kræver: niveau 4+, Familiar Friend. +1 til en valgfri ability score (maks 20). Otherworldly Power: når du caster Find Familiar, giv den resistens mod nekrotisk, gift, psykisk, strålende eller torden og Phase Walk (bevæg dig gennem væsener og genstande som vanskeligt terræn).", "Soothing Familiar": "Kræver: niveau 4+, Familiar Friend. +1 til en valgfri ability score (maks 20). Healing Beacon: 5-ft udstråling fra din familiar (inden for 120 ft): allierede behandler et 1 eller 2 på en helingsterning som et 3.", "Spell Resistant": "Kræver: niveau 4+. +1 DEX eller CON (maks 20). Magical Resilience: resistens mod nekrotisk, psykisk, strålende eller torden (vælg). Magic Resistant: læg 1d6 til et fejlet save mod en spell eller magisk effekt, Proficiency Bonus gange pr. Long Rest.", "Spell Subterfuge": "Kræver: niveau 4+, Spellcasting. +1 INT, WIS eller CHA (maks 20). Shrouding Spells: efter at have castet en action-spell med slot, Dash og Hide som Bonus Action (ability-mod gange pr. Long Rest). Sneaky Casting: verbale spells eller spell-angreb afslutter ikke Invisible fra Hide hvis du ender turen bag 3/4 eller Total Cover.", "Transmutation Adept": "Kræver: niveau 4+, Spellcasting. +1 INT, WIS eller CHA (maks 20). Har altid Jump, Spider Climb, Slow, Polymorph, Animate Objects forberedt (efter slot-niveau). Magical Augmentation: på din tur øger en Transmutation-spell castet med slot din Speed med 5 ft x slot-niveau til turens slutning.", "Warlike Familiar": "Kræver: niveau 4+, Familiar Friend. +1 til en valgfri ability score (maks 20). Battle Familiar er altid forberedt, castes én gang gratis pr. Long Rest. Intercept Attack: Reaction, familiaren lægger din Proficiency Bonus til AC for et væsen inden for 5 ft mod et angreb.", "Arcane Warrior": "Kræver: Fighting Style-evne. Lær to Wizard-cantrips (Mage Hand og Ray of Frost anbefales; INT/WIS/CHA). Byt ét ved level-up.", "Boon of Erupting Spellpower": "Kræver: niveau 19+, Spellcasting. +1 INT, WIS eller CHA (maks 30). Spell Overload: på en skadespell med slot behandles 1'ere og 2'ere på skadesterninger som 3, og skadede væsener er Prone (én gang indtil Initiative eller en Short/Long Rest).", "Boon of Magic School Mastery": "Kræver: niveau 19+, Spellcasting. +1 INT, WIS eller CHA (maks 30). Vælg en skole: Rote Casting (et niveau 1-spell fra den, altid forberedt, uden slot eller komponenter) og Signature Arcanum (et niveau 7-eller-lavere spell fra den, gratis én gang pr. Long Rest). Kan tages flere gange, ny skole hver gang.", "Boon of the Iron Mind": "Kræver: niveau 19+. +1 til en ability score (maks 30). Unshakable Focus: du mister kun Concentration ved at caste/aktivere en anden Concentration-effekt, blive Petrified eller Unconscious, eller dø."});
Object.assign(SUBCLASS_DESC_DA,{"Arcana Domain": "Magi-fokuseret Cleric: Modify Magic, Dispelling Recovery og Wizard-cantrips.", "Arcane Archer": "Fortryllet ammunition: Arcane Shot-effekter, kurvende skud og teleports.", "Warrior of the Mystic Arts": "Sorcerer-spellcasting flettet ind i kampsport (WIS).", "Vestige Patron": "Rester af en døende gud manifesterer sig som din Vestige Companion.", "Conjurer": "Teleportation (Benign Transposition) og tilkaldelse af åndeallierede.", "Enchanter": "Omtåger og fanger sind: Hypnotic Presence og Instinctive Charm.", "Necromancer": "Liv, død og undead: Undead Thralls og Harvest Undead.", "Transmuter": "Ændrer energi og materie: Transmuter's Stone og Shape-Shifter."});
