// Danish spell descriptions (D&D 2024). Keyed by the English spell name (which stays the lookup key everywhere).
// Damage types: fire=ild, cold=kulde, lightning=lyn, thunder=torden, necrotic=nekrotisk, radiant=strålende,
// poison=gift, acid=syre, force=kraft, psychic=psykisk, piercing=stik, bludgeoning=knusning, slashing=flæng.
// "X save" -> "X save". advantage=fordel, disadvantage=ulempe.
export const SDD={
  "Mind Sliver":"INT save eller 1d6 psykisk og -1d4 på næste save.",
  "Sorcerous Burst":"1d8 af en valgt skadetype; kan springe videre ved maks-kast.",
  "Starry Wisp":"Afstandsangreb med magi: 1d8 strålende; målet udsender svagt lys (10 ft) og kan ikke være usynligt til slutningen af din næste tur.",
  "Elementalism":"Mindre effekt af ild, vand, jord eller luft.",
  "Resistance":"Vælg en skadetype: det berørte væsen reducerer skade af den type med 1d4 (én gang pr. tur).",
  "Spare the Dying":"Stabilisér et væsen på 0 HP.",
  "Word of Radiance":"CON save eller 1d6 strålende til nære fjender.",
  "Fire Bolt":"Afstandsangreb med magi: 1d10 ild.",
  "Ray of Frost":"Ramt: 1d8 kulde, målets fart -10 ft.",
  "Shocking Grasp":"Nærkampsangreb med magi: 1d8 lyn; målet kan ikke foretage Opportunity Attacks før starten af dens næste tur.",
  "Mage Hand":"Spøgelseshånd, op til 10 pund.",
  "Minor Illusion":"Lyd eller billede. INT-tjek for at gennemskue.",
  "Prestidigitation":"Små magiske tricks.",
  "Magic Missile":"3 pile, 1d4+1 kraft hver, rammer automatisk.",
  "Shield":"+5 AC. Immun over for Magic Missile.",
  "Mage Armor":"AC = 13+DEX for et væsen uden rustning.",
  "Burning Hands":"DEX save eller 3d6 ild.",
  "Charm Person":"WIS save eller charmeret.",
  "Sleep":"5-ft kugle: WIS save eller Incapacitated; fejler målet også næste save, bliver det Unconscious. Slutter ved skade eller hvis nogen ryster det.",
  "Thunderwave":"CON save eller 2d8 torden + skubbet 10 ft.",
  "Misty Step":"Teleportér op til 30 ft.",
  "Hold Person":"WIS save eller humanoide lammes.",
  "Invisibility":"Målet er usynligt indtil det angriber eller caster.",
  "Mirror Image":"3 kopier opsuger angreb.",
  "Scorching Ray":"3 stråler, 2d6 ild hver.",
  "Shatter":"CON save eller 3d8 torden.",
  "Suggestion":"WIS save eller følg en opfordring.",
  "Counterspell":"Målet (castet) laver en CON save; ved fejl slår spellet fejl og handlingen er spildt (en spellplads bruges ikke).",
  "Fireball":"20-ft radius. DEX save eller 8d6 ild.",
  "Fly":"Flyvefart 60 ft.",
  "Haste":"Dobbelt fart, +2 AC, ekstra handling.",
  "Lightning Bolt":"DEX save eller 8d6 lyn.",
  "Slow":"WIS save eller halv fart, -2 AC/DEX.",
  "Fear":"WIS save eller skræmt og flygter.",
  "Banishment":"CHA save eller forvist.",
  "Greater Invisibility":"Usynlig selv mens du angriber.",
  "Ice Storm":"20-ft radius: DEX save eller 2d10 knusning + 4d6 kulde (halv ved succes); jorden bliver vanskeligt terræn.",
  "Polymorph":"WIS save eller forvandlet til et dyr.",
  "Confusion":"WIS save eller handl tilfældigt.",
  "Cone of Cold":"CON save eller 8d8 kulde.",
  "Hold Monster":"WIS save eller ethvert væsen lammes.",
  "Cloudkill":"20-ft giftig tåge, 5d8 gift pr. tur.",
  "Dominate Person":"WIS save eller kontrollér en humanoid.",
  "Sacred Flame":"DEX save eller 1d8 strålende. Skalerer ved 5/11/17.",
  "Guidance":"Vælg en færdighed: det berørte væsen lægger 1d4 til evnetjek med den.",
  "Light":"Genstand udsender skarpt lys 20 ft.",
  "Thaumaturgy":"Mindre vidundereffekt.",
  "Toll the Dead":"WIS save eller 1d8 (1d12 hvis såret) nekrotisk.",
  "Bless":"3 væsener lægger 1d4 til angreb/saves.",
  "Command":"WIS save eller ét-ords kommando.",
  "Cure Wounds":"Genopret 2d8+mod HP.",
  "Guiding Bolt":"4d6 strålende, næste angreb har fordel.",
  "Healing Word":"Genopret 2d4+mod HP.",
  "Inflict Wounds":"CON save eller 2d10 nekrotisk (halv ved succes).",
  "Shield of Faith":"+2 AC.",
  "Aid":"3 væsener får +5 maks HP.",
  "Lesser Restoration":"Fjern én tilstand: Blinded, Deafened, Paralyzed eller Poisoned.",
  "Prayer of Healing":"Op til 5 væsener, der forbliver inden for rækkevidde hele castingen, får en Short Rests fordele og får 2d8 HP tilbage (én gang pr. Long Rest hver).",
  "Spiritual Weapon":"Spøgelsesvåben: 1d8+mod kraft pr. tur.",
  "Animate Dead":"Skab en udød tjener.",
  "Daylight":"60-ft radius med skarpt lys.",
  "Dispel Magic":"Afslut én spell af 3. niveau eller lavere.",
  "Spirit Guardians":"WIS save eller 3d8 strålende/nekrotisk.",
  "Remove Curse":"Fjern alle forbandelser på målet.",
  "Death Ward":"Falder til 1 HP i stedet for 0, én gang.",
  "Freedom of Movement":"Ignorér vanskeligt terræn og fastholdelse.",
  "Guardian of Faith":"20 strålende til fjender inden for 10 ft.",
  "Flame Strike":"10-ft radius søjle: DEX save eller 5d6 ild + 5d6 strålende (halv ved succes).",
  "Greater Restoration":"Fjern en alvorlig tilstand eller forbandelse.",
  "Mass Cure Wounds":"Op til 6 væsener i en 30-ft radius får 5d8 + spellcasting-mod HP tilbage.",
  "Raise Dead":"Bring et dødt væsen til live (500 gp diamant).",
  "Druidcraft":"Mindre natureffekt.",
  "Produce Flame":"Flamme: lys eller kast for 1d8 ild.",
  "Shillelagh":"Kølle eller kampstav: angreb og skade bruger din spellcasting-evne; skadeterning bliver d8; kan gøre Force-skade.",
  "Thorn Whip":"1d6 stik, træk 10 ft.",
  "Animal Friendship":"WIS save eller dyret charmeres.",
  "Entangle":"STR save eller fastholdt af planter.",
  "Faerie Fire":"DEX save eller markeret; angreb har fordel.",
  "Goodberry":"10 bær, hvert giver 1 HP.",
  "Barkskin":"Ingen koncentration. AC 17.",
  "Flaming Sphere":"2d6 ildkugle, flyt med bonus-handling.",
  "Moonbeam":"CON save eller 2d10 strålende pr. tur.",
  "Pass without Trace":"+10 Stealth til dig og 10 ledsagere.",
  "Spike Growth":"2d4 stik pr. 5 ft bevæget.",
  "Call Lightning":"DEX save eller 3d10 lyn pr. tur.",
  "Conjure Animals":"Spøgelsesflok (fordel på STR saves inden for 5 ft af den); væsener nær den: DEX save eller 3d10 flæng.",
  "Plant Growth":"100-ft radius vanskeligt terræn.",
  "Blight":"CON save eller 8d8 nekrotisk.",
  "Insect Plague":"CON save eller 4d10 stik pr. tur.",
  "Vicious Mockery":"WIS save eller 1d6 psykisk (skalerer 2d6/3d6/4d6), ulempe på næste angreb.",
  "Dancing Lights":"4 svævende lys.",
  "Eldritch Blast":"Afstandsangreb med magi: 1d10 kraft. 2 stråler på niveau 5, 3 på niveau 11, 4 på niveau 17.",
  "Chill Touch":"Nærkampsangreb med magi: 1d10 nekrotisk; målet kan ikke få HP tilbage til slutningen af din næste tur.",
  "Armor of Agathys":"5 midlertidige HP; angriber tager 5 kulde.",
  "Arms of Hadar":"STR save eller 2d6 nekrotisk, ingen reaktioner.",
  "Hex":"+1d6 nekrotisk hver gang du rammer målet med et angreb; målet har ulempe på tjek med en valgt evne.",
  "Hellish Rebuke":"DEX save eller 2d10 ild.",
  "Witch Bolt":"2d12 lyn, oprethold for 1d12 pr. tur.",
  "Darkness":"15-ft magisk mørke.",
  "Vampiric Touch":"3d6 nekrotisk; få halvdelen som HP.",
  "Hunger of Hadar":"20-ft mørketomrum: 2d6 kulde + 2d6 syre.",
  "Divine Favor":"+1d4 strålende på våbentræf.",
  "Find Steed":"Fremkald et åndeligt ridedyr.",
  "Aura of Vitality":"30-ft udstråling: når du caster den og ved starten af hver af dine ture, gendan 2d6 HP til ét væsen i den.",
  "Revivify":"Bring en (død i 1 min) til live (300 gp diamant).",
  "Hunter's Mark":"+1d6 kraft hver gang du rammer målet med et angreb; fordel på Perception/Survival-tjek for at finde det; mærket kan flyttes.",
  "Fog Cloud":"20-ft kugle af tæt tåge.",
  "Ensnaring Strike":"STR save eller fastholdt; 1d6 stik pr. tur.",
  "Conjure Barrage":"60-ft kegle: DEX save eller 5d8 kraft (halv ved succes).",
  "Swift Quiver":"Koggeret laver ammunition; 2 afstandsangreb pr. bonus-handling.",
  "Wind Wall":"50-ft vindmur: STR save eller 4d8 knusning når den opstår (halv ved succes); stopper gas og små flyvende væsener.",
  "Silence":"20-ft kugle af magisk stilhed.",
  "Hypnotic Pattern":"30-ft terning: WIS save eller Charmed, Incapacitated med Speed 0; slutter ved skade eller hvis nogen ryster det.",
  "Major Image":"20-ft illusion med lyd og lugt.",
  "Sending":"25-ords besked til et kendt væsen.",
  "Dissonant Whispers":"WIS save eller 3d6 psykisk, må flygte.",
  "Heroism":"Immun over for skræmt; midlertidige HP hver tur.",
  "Enthrall":"WIS save eller distraheret af dig.",
  "Compulsion":"WIS save eller må bevæge sig i valgt retning.",
  "Dimension Door":"Teleportér dig selv + ét væsen op til 500 ft.",
  "Hallucinatory Terrain":"Terræn ser ud som en anden terræntype.",
  "Compelled Duel":"WIS save eller må kun kæmpe mod dig.",
  "Thunderous Smite":"+2d6 torden; STR save eller skubbet 10 ft og Prone.",
  "Wrathful Smite":"+1d6 nekrotisk ved træf; WIS save eller Frightened (gentag save hver tur).",
  "Branding Smite":"+2d6 strålende, målet kan ikke være usynligt.",
  "Crusader's Mantle":"Allierede inden for 30 ft laver +1d4 strålende.",
  "Elemental Weapon":"+1 våben, +1d4 energiskade.",
  "Blinding Smite":"+3d8 strålende; målet er Blinded til spellet slutter (CON save ved slutningen af hver af dens ture).",
  "Staggering Smite":"+4d6 psykisk; WIS save eller Stunned til slutningen af din næste tur.",
  "Holy Weapon":"+2d8 strålende ved træf.",
  "Hail of Thorns":"DEX save eller 1d10 stik i 5-ft område.",
  "Speak with Animals":"Tal med dyr.",
  "Lightning Arrow":"Dit næste afstandsangreb bliver til lyn: målet tager 4d8 lyn (halv ved forbier); væsener inden for 10 ft: DEX save eller 2d8.",
  "Steel Wind Strike":"5 mål: 6d10 kraft hver.",
  "Cordon of Arrows":"4 pile vogter en zone på 30 ft: DEX save eller 2d4 stik hver.",
  "Conjure Volley":"40-ft radius cylinder: DEX save eller 8d8 kraft (halv ved succes).",
  "Conjure Woodland Beings":"10-ft udstråling af naturånder: WIS save eller 5d8 kraft (halv ved succes) når et væsen træder ind eller slutter sin tur der.",
  "Grasping Vine":"Nærkampsangreb med magi (mål inden for 30 ft af vinen): 4d8 knusning, trækkes op til 30 ft mod vinen og Grappled.",
  "Tree Stride":"Teleportér mellem træer af samme art.",
  "Commune with Nature":"Lær om området omkring dig (3 miles udendørs, 300 ft under jorden): vælg tre fakta, fx bosættelser, portaler, kraftfulde væsener, mest udbredte plante/mineral/dyr, vandområder.",
  "Speak with Plants":"Tal med planter.",
  "Dominate Beast":"WIS save eller kontrollér et dyr.",
  "Giant Insect":"Tilkald en kæmpe tusindben, edderkop eller hveps (Giant Insect-statblok); den er din allierede.",
  "Antilife Shell":"Barriere forhindrer levende væsener i at komme ind.",
  "Reincarnate":"Genskab et dødt væsen i en ny krop.",
  "Animal Shapes":"Villige væsener bliver til dyr CR 4 eller lavere.",
  "Earth Tremor":"DEX save eller 1d6 knusning og liggende.",
  "Bane":"CHA save eller -1d4 til angreb/saves.",
  "Create or Destroy Water":"Skab eller ødelæg 10 liter vand.",
  "Detect Evil and Good":"Mærk djævle, udøde, himmelske inden for 30 ft.",
  "Detect Magic":"Mærk magi inden for 30 ft.",
  "Detect Poison and Disease":"Mærk gift og sygdom inden for 30 ft.",
  "Purify Food and Drink":"Rens mad og drikke i en 5-ft kugle.",
  "Sanctuary":"WIS save eller angribere må vælge nyt mål.",
  "Augury":"Held/uheld for en handling inden for 30 min.",
  "Calm Emotions":"Undertryk charme/frygt eller følelser.",
  "Enhance Ability":"Fordel på én slags evnetjek.",
  "Find Traps":"Mærk fælder i synslinjen.",
  "Locate Animals or Plants":"Mærk nærmeste navngivne dyr eller plante inden for 5 mil.",
  "Protection from Poison":"Fordel mod gift, modstand mod giftskade.",
  "Warding Bond":"+1 AC/saves, modstand; du deler den skade der tages.",
  "Zone of Truth":"CHA save eller kan ikke lyve i en 15-ft kugle.",
  "Beacon of Hope":"Fordel på WIS saves og death saves.",
  "Create Food and Water":"Skab 20 kg mad og 115 liter vand.",
  "Mass Healing Word":"Op til 6 væsener får 2d4 + spellcasting-mod HP tilbage.",
  "Meld into Stone":"Træd ind i en stengenstand.",
  "Speak with Dead":"Stil et lig 5 spørgsmål.",
  "Water Walk":"Gå på væske som var det fast.",
  "Divination":"Sandfærdigt svar om en begivenhed inden for 7 dage.",
  "Commune":"Stil en gud 3 ja/nej-spørgsmål.",
  "Contagion":"CON save eller 1d8 nekrotisk og Poisoned (ulempe på saves med en valgt evne); gentag hver tur: 3 succeser afslutter det, 3 fejl gør at det varer 7 dage.",
  "Dispel Evil and Good":"Celestials, Elementals, Fey, Fiends og Undead har ulempe på angreb mod dig; du kan afslutte spellet tidligt med en særlig funktion (Break Enchantment, Dismissal).",
  "Hallow":"60-ft radius helliget grund.",
  "Summon Celestial":"Fremkald en lydig himmelsk ånd.",
  "Animal Messenger":"Lille dyr leverer en 25-ords besked.",
  "Beast Sense":"Se og hør gennem et dyr.",
  "Flame Blade":"Ild-scimitar: 3d6 ild.",
  "Gust of Wind":"60-ft vindlinje skubber 15 ft.",
  "Heat Metal":"Metal gløder: 2d8 ild, CON save eller tab det.",
  "Locate Object":"Mærk retning til en kendt genstand inden for 1000 ft.",
  "Locate Creature":"Mærk retning til et kendt væsen inden for 1000 ft.",
  "Conjure Minor Elementals":"15-ft udstråling af elementarånder: dine træf på væsener i den giver +2d8 (syre, kulde, ild eller lyn, dit valg); vanskeligt terræn for fjender.",
  "Banishing Smite":"+5d10 kraft; efterlader det målet på 50 HP eller mindre: CHA save eller forvist.",
  "Circle of Power":"Allierede har fordel på magic saves.",
  "Destructive Wave":"30-ft udstråling: CON save eller 5d6 torden + 5d6 strålende eller nekrotisk (dit valg) og Prone; halv skade ved succes.",
  "Aura of Life":"Nekrotisk modstand; væsener på 0 HP får 1 HP pr. tur.",
  "Aura of Purity":"30-ft udstråling: du og allierede har modstand mod gift og fordel på saves mod Blinded, Charmed, Deafened, Frightened, Paralyzed, Poisoned og Stunned.",
  "Geas":"WIS save eller følg kommando; 5d10 psykisk pr. dag ved brud.",
  "Control Water":"Oversvøm, del, omdirigér eller lav malstrøm i en 100-ft terning vand.",
  "Animate Objects":"Animér ikke-magiske genstande (maks = din spellcasting-mod; Medium 1, Large 2, Huge 3); kommandér dem som bonus-handling; hver har et Slam-angreb.",
  "Conjure Elemental":"Stor elementaråndelig (skadetype efter element): DEX save eller 8d8 og Restrained; det Restrained mål gentager save hver tur for 4d8.",
  "Bigby's Hand":"Stor hånd (AC 20): bonus-handling til at flytte den 60 ft og bruge Clenched Fist (5d8 kraft), Forceful Hand (skub), Grasping Hand (grib, knus 4d6+mod) eller Interposing Hand (Half Cover).",
  "Teleportation Circle":"Portal til en permanent teleportationscirkel.",
  "Wall of Force":"Usynlig uforgængelig kraftmur.",
  "Wall of Stone":"Ikke-magisk stenmur; kan blive permanent.",
  "Chain Lightning":"DEX save eller 10d8 lyn (halv ved succes); 3 flere lyn springer til mål inden for 30 ft.",
  "Circle of Death":"60-ft radius: CON save eller 8d8 nekrotisk (halv ved succes).",
  "Disintegrate":"DEX save eller 10d6+40 kraft; 0 HP = støv.",
  "Eyebite":"WIS save eller sovende/panisk/kvalm.",
  "Globe of Invulnerability":"Spells af 5. niveau og lavere kan ikke komme ind.",
  "Mass Suggestion":"WIS save eller 12 væsener følger en opfordring.",
  "Sunbeam":"CON save eller 6d8 strålende og blindet.",
  "True Seeing":"Se gennem illusioner og usynlighed.",
  "Delayed Blast Fireball":"Vokser hver runde; DEX save eller 12d6 ild.",
  "Etherealness":"Træd ind i Æterplanet.",
  "Finger of Death":"CON save eller 7d8+30 nekrotisk; rejser sig som zombie.",
  "Forcecage":"Uundslippeligt 20-ft kraftbur.",
  "Teleport":"Transportér op til 9 væsener til et kendt sted.",
  "Dominate Monster":"WIS save eller kontrollér ethvert væsen.",
  "Feeblemind":"INT save eller INT og CHA falder til 1.",
  "Incendiary Cloud":"DEX save eller 10d8 ild pr. tur.",
  "Maze":"Forvis til en labyrint; DC 20 INT for at undslippe.",
  "Mind Blank":"Immun over for psykisk skade og spådom.",
  "Power Word Stun":"150 HP eller mindre: lammet indtil CON save.",
  "Sunburst":"CON save eller 12d6 strålende og blindet.",
  "Foresight":"Målet har fordel på D20-tests, og andre væsener har ulempe på angrebsslag mod det.",
  "Gate":"Portal til et andet plan; fremkald et bestemt væsen.",
  "Meteor Swarm":"4 meteorer: DEX save eller 20d6 ild + 20d6 knusning.",
  "Power Word Kill":"Et væsen med 100 HP eller mindre dør; ellers tager det 12d12 psykisk skade (ingen save).",
  "Wish":"Den mægtigste spell. Efterlign enhver spell af 8. niveau eller lavere, eller ønsk.",
  "Weird":"30-ft radius: WIS save eller 10d10 psykisk og Frightened (halv skade ved succes); et Frightened mål tager 5d10 psykisk ved hver fejlet save ved slutningen af dens ture.",
  "Time Stop":"Tag 1d4+1 ture mens tiden står stille.",
  "True Polymorph":"WIS save eller forvandl væsen eller genstand.",
  "Shapechange":"Forvandl til ethvert set væsen med CR lig med niveau eller lavere.",
  "Astral Projection":"Projicér op til 9 villige væsener ind i Astralplanet.",
  "Imprisonment":"WIS save eller væsenet fængsles.",
  "Prismatic Wall":"7-lags flerfarvet mur med forskellige effekter.",
  "Acid Splash":"5-ft radius: DEX save eller 1d6 syre.",
  "Blade Ward":"Angribere trækker 1d4 fra angrebsslag mod dig.",
  "Friends":"WIS save eller Charmed (automatisk succes hvis det ikke er en Humanoid, eller du kæmper mod det); slutter hvis du angriber, gør skade eller tvinger til en save.",
  "Mending":"Reparér et brud eller en flænge i en genstand.",
  "Message":"Hvisk til et væsen; det kan svare.",
  "Poison Spray":"Afstandsangreb med magi: 1d12 gift.",
  "True Strike":"Foretag ét våbenangreb med din spellcasting-evne; skaden kan være strålende eller våbnets normale type.",
  "Thunderclap":"CON save eller 1d6 torden.",
  "Alarm":"Alarm mod indtrængen i en 20-ft terning.",
  "Chromatic Orb":"3d8 af en valgt energitype.",
  "Color Spray":"15-ft kegle: CON save eller Blinded til slutningen af din næste tur.",
  "Comprehend Languages":"Forstå ethvert talt eller skrevet sprog.",
  "Disguise Self":"Skift dit udseende.",
  "Expeditious Retreat":"Bonus-handling Dash hver tur.",
  "False Life":"2d4+4 midlertidige HP; +5 pr. slotniveau over 1.",
  "Feather Fall":"5 væsener tager ingen faldskade.",
  "Find Familiar":"Få en familiar i dyreform.",
  "Grease":"DEX save eller fald ned; vanskeligt terræn.",
  "Hideous Laughter":"WIS save eller ude af stand til at handle af grin.",
  "Identify":"Lær en magisk genstands egenskaber.",
  "Illusory Script":"Skjult besked som kun tiltænkte læsere kan se.",
  "Jump":"Én gang på hver af dens ture kan målet hoppe op til 30 ft ved at bruge 10 ft bevægelse.",
  "Longstrider":"+10 ft fart.",
  "Protection from Evil and Good":"Aberrations, Celestials, Elementals, Fey, Fiends og Undead har ulempe mod målet og kan ikke besætte, Charme eller skræmme det.",
  "Ray of Sickness":"Afstandsangreb med magi: 2d8 gift og Poisoned til slutningen af din næste tur.",
  "Silent Image":"Visuel illusion op til en 15-ft terning.",
  "Unseen Servant":"Usynlig kraft udfører simple opgaver.",
  "Alter Self":"Skift udseende, ånd under vand eller få våben.",
  "Blindness/Deafness":"CON save eller blindet/døv.",
  "Blur":"Angreb mod dig har ulempe.",
  "Cloud of Daggers":"4d4 flæng i en 5-ft terning hver tur.",
  "Continual Flame":"Permanent flammelignende glød.",
  "Crown of Madness":"WIS save eller angriber et tilfældigt væsen.",
  "Darkvision":"Mørkesyn 60 ft.",
  "Detect Thoughts":"Læs overfladetanker hos væsener inden for 30 ft.",
  "Enlarge/Reduce":"Fordobl eller halvér størrelse; +/-1d4 skade.",
  "Gentle Repose":"Bevar lig; forlæng grænsen for Raise Dead.",
  "Knock":"Åbn en låst/fastklemt/barrikaderet genstand.",
  "Levitate":"Målet stiger op til 20 ft.",
  "Magic Mouth":"25-ords besked udløses på en betingelse.",
  "Magic Weapon":"Våben bliver +1 magisk.",
  "Melf's Acid Arrow":"4d4 syre nu + 2d4 næste tur.",
  "Phantasmal Force":"INT save eller et fantom kun målet opfatter (10-ft terning); en Study-handling (INT/Investigation mod din DC) afslører det; er det en fare, kan det gøre 2d8 psykisk på dine ture.",
  "Ray of Enfeeblement":"CON save: ved succes ulempe på dens næste angrebsslag; ved fejl ulempe på STR-baserede D20-tests og -1d8 på dens skadeslag (gentag save hver tur).",
  "Rope Trick":"Ekstradimensionelt rum for enden af et reb.",
  "See Invisibility":"Se usynlige væsener og genstande.",
  "Spider Climb":"Klatr på enhver overflade, også lofter.",
  "Web":"DEX save eller fastholdt i spind.",
  "Bestow Curse":"WIS save eller forbandet med forskellige straffe.",
  "Blink":"Ved slutningen af hver af dine ture slår du 1d6: ved 4-6 forsvinder du til Æterplanet og vender tilbage ved starten af din næste tur.",
  "Clairvoyance":"Usynlig sensor; se eller hør gennem den.",
  "Feign Death":"Fremstå død; modstand mod al skade undtagen psykisk.",
  "Gaseous Form":"Tågesky med Fly 10 ft: modstand mod knusning, stik og flæng, fordel på STR/DEX/CON saves; kan ikke angribe eller caste spells.",
  "Glyph of Warding":"Rune udløser en spell eller 5d8 eksplosion.",
  "Nondetection":"Kan ikke rammes af spådom eller skrying.",
  "Protection from Energy":"Modstand mod én energitype.",
  "Sleet Storm":"DEX save eller liggende; vanskeligt terræn.",
  "Stinking Cloud":"20-ft kugle, Heavily Obscured: et væsen der starter sin tur der laver en CON save eller er Poisoned til slutningen af turen og kan ikke tage handlinger eller bonus-handlinger.",
  "Tongues":"Forstå og tal ethvert sprog.",
  "Water Breathing":"10 væsener kan ånde under vand.",
  "Arcane Eye":"Usynligt magisk øje; mørkesyn 30 ft.",
  "Evard's Black Tentacles":"20-ft felt: STR save eller 3d6 knusning og Restrained; vanskeligt terræn; gentag ved indtræden eller slut på tur der (én gang pr. tur).",
  "Fabricate":"Forvandl råmaterialer til et produkt.",
  "Fire Shield":"Modstå ild eller kulde; angribere tager 2d8.",
  "Leomund's Secret Chest":"Skjul en kiste på Æterplanet.",
  "Mordenkainen's Faithful Hound":"Usynlig, ulegemlig vagthund gør ved ubudne gæster; hver af dine ture bider den en fjende inden for 5 ft: DEX save eller 4d8 kraft.",
  "Mordenkainen's Private Sanctum":"Blokér teleportation, skrying og lyd.",
  "Otiluke's Resilient Sphere":"DEX save eller lukket inde i en kraftkugle.",
  "Phantasmal Killer":"WIS save eller 4d10 psykisk og ulempe på evnetjek og angrebsslag (halv skade og spellet slutter ved succes); gentag save hver tur og tag skaden igen ved fejl.",
  "Stone Shape":"Form mellemstor sten til enhver form.",
  "Stoneskin":"Det berørte væsen har modstand mod knusnings-, stik- og flængskade.",
  "Wall of Fire":"5d8 ild til væsener inden for 10 ft.",
  "Creation":"Skab en ikke-levende genstand af skyggestof.",
  "Legend Lore":"Lær viden om en legendarisk person/sted/genstand.",
  "Mislead":"Bliv usynlig; skab en styrbar dobbeltgænger.",
  "Modify Memory":"WIS save eller Charmed og Incapacitated; du kan ændre dens erindring om en begivenhed inden for de sidste 24 timer (højst 10 min lang).",
  "Passwall":"Passage gennem en mur op til 20 ft dyb.",
  "Planar Binding":"CHA save eller himmelsk/djævel/fe tjener dig.",
  "Seeming":"Skift udseende på et vilkårligt antal væsener.",
  "Telekinesis":"Flyt væsener eller genstande op til 500 kg.",
  "Arcane Gate":"Forbind to portaler op til 500 ft fra hinanden.",
  "Contingency":"Forbered en spell til at udløse automatisk.",
  "Create Undead":"Skab 3 ghouls fra lig.",
  "Flesh to Stone":"CON save eller forstenet efter 3 fejl.",
  "Guards and Wards":"Magisk bygningsforsvar.",
  "Move Earth":"Omform en 40-ft terning af jord/sand/ler.",
  "Otiluke's Freezing Sphere":"CON save eller 10d6 kulde i en 60-ft radius.",
  "Otto's Irresistible Dance":"WIS save: ved succes danser det til slutningen af dens næste tur; ved fejl Charmed, danser på stedet med ulempe på DEX saves og angreb (angribere har fordel); det kan bruge en handling til at gentage save.",
  "Programmed Illusion":"Illusion aktiveres ved en udløser.",
  "Wall of Ice":"Isvæg (AC 12, 30 HP pr. 10-ft sektion): væsener i dens felt når den opstår: DEX save eller 10d6 kulde; en sprængt sektion efterlader kold luft (CON save eller 5d6 kulde).",
  "Mirage Arcane":"1-mils firkantet terrænillusion.",
  "Mordenkainen's Magnificent Mansion":"Ekstradimensionel bolig.",
  "Mordenkainen's Sword":"Spøgelsessværd: nærkampsangreb med magi for 4d12 + spellcasting-mod kraft; bonus-handling: flyt det 30 ft og angrib igen.",
  "Plane Shift":"Transportér op til 9 væsener til et andet plan.",
  "Prismatic Spray":"8 farvede stråler med forskellige effekter.",
  "Project Image":"Illusorisk dobbeltgænger du kan sanse gennem.",
  "Reverse Gravity":"Genstande falder opad i en 50-ft radius.",
  "Symbol":"Skadelig rune udløses på en betingelse.",
  "Heal":"Gendan 70 HP; afslutter tilstandene Blinded, Deafened og Poisoned.",
  "Harm":"CON save eller 14d6 nekrotisk; sænker maks HP.",
  "Heroes' Feast":"12 væsener: immun over for gift/frygt, +2d10 maks HP.",
  "Planar Ally":"Guden sender en himmelsk/elementar/djævel.",
  "Word of Recall":"5 væsener teleporterer til et fristed.",
  "Conjure Celestial":"Lyssøjle (10-ft radius, 40 ft høj): vælg pr. væsen Healing Light (4d12 + spellcasting-mod HP) eller Searing Light (DEX save eller 6d12 strålende, halv ved succes).",
  "Divine Word":"Effekter baseret på væsenets HP.",
  "Fire Storm":"DEX save eller 7d10 ild i 10 terninger.",
  "Regenerate":"4d8+15 HP nu; genvækst af lemmer; 1 HP pr. runde.",
  "Resurrection":"Bring en (død i 100 år) til live (1000 gp diamant).",
  "Antimagic Field":"10-ft kugle hvor magi svigter.",
  "Control Weather":"Styr vejret i et 5-mils område.",
  "Earthquake":"100-ft radius voldsom rysten.",
  "Holy Aura":"Allierede har fordel på alle saves; fjender ulempe når de angriber dem.",
  "Mass Heal":"Fordel 700 HP blandt væsener.",
  "True Resurrection":"Bring en (død i 200 år) til live, selv uden krop.",
  "Antipathy/Sympathy":"Genstand frastøder eller tiltrækker en væsentype.",
  "Storm of Vengeance":"Kæmpe storm: lyn, syre, hagl hver runde.",
  "Conjure Fey":"Mellemstor fe-ånd: nærkampsangreb med magi for 3d12 + spellcasting-mod psykisk og Frightened; bonus-handling: teleportér den 30 ft og angrib igen.",
  "Transport via Plants":"Forbind to store+ planter på samme plan.",
  "Wall of Thorns":"Tornevæg blokerer sigt: DEX save eller 7d8 stik når den opstår og 7d8 flæng når et væsen første gang træder ind eller slutter sin tur i den; 4 ft bevægelse pr. fod.",
  "Wind Walk":"10 væsener bliver gasformige, flyv 300 ft.",
  "Glibness":"Charisma-tjek: du kan erstatte dit slag med 15; magi der opdager løgne siger, at du taler sandt.",
  "Power Word Heal":"Genopret alle HP; fjern tilstande.",
  "Find the Path":"Kend den korteste vej til et sted.",
  "Forbiddance":"Beskyt et område mod planrejser.",
  "Blade Barrier":"Klingemur (tre-kvart dækning, vanskeligt terræn): DEX save eller 6d10 kraft når et væsen er i den, træder ind eller slutter sin tur der (halv ved succes).",
  "Leomund's Tiny Hut":"10-ft udstråling omkring dig: væsener indeni bevæger sig frit, andre kan ikke passere; spells af niveau 3 eller lavere kan ikke castes igennem den.",
  "Magic Circle":"Barriere der holder en væsentype ude eller inde.",
  "Phantom Steed":"Halvvirkeligt ridedyr, fart 100 ft.",
};

// Reusable metadata translators (cover school / casting time / range / duration for every spell).
const SCHOOL_DA={Abjuration:"Afværgelse",Conjuration:"Fremkaldelse",Divination:"Spådom",Enchantment:"Fortryllelse",Evocation:"Besværgelse",Illusion:"Illusion",Necromancy:"Nekromanti",Transmutation:"Transmutation"};
export function trSchool(s){return SCHOOL_DA[s]||s;}
export function trCast(s){if(!s)return s;return s
  .replace("1 bonus action","1 bonus-handling")
  .replace("1 action","1 handling")
  .replace("1 reaction","1 reaktion")
  .replace(/(\d+)\s*hours?/,"$1 timer").replace("1 hour","1 time")
  .replace(/(\d+)\s*minutes?/,"$1 minutter").replace("1 min","1 min")
  .replace("(ritual)","(ritual)");}
export function trRange(s){if(!s)return s;return s
  .replace("Self","Selv").replace("Touch","Berøring").replace("Sight","Syn").replace("Unlimited","Ubegrænset")
  .replace("cone","kegle").replace("line","linje").replace("cube","terning").replace("radius","radius")
  .replace(/(\d+)\s*miles?/,"$1 mil").replace("mile","mil");}
export function trDur(s){if(!s)return s;return s
  .replace("Instant","Øjeblikkelig").replace("Special","Speciel")
  .replace("Until cured","Indtil helbredt").replace("Until dispelled or triggered","Indtil ophævet eller udløst").replace("Until dispelled","Indtil ophævet").replace("Until triggered","Indtil udløst")
  .replace("Concentration","Koncentration").replace("Conc.","Konc.")
  .replace("Up to","Op til")
  .replace(/(\d+)\s*hours?/,"$1 timer").replace(/\bhr\b/,"time").replace(/\bhour\b/,"time")
  .replace(/(\d+)\s*minutes?/,"$1 minutter").replace(/\bmin\b/,"min")
  .replace(/(\d+)\s*rounds?/,"$1 runder").replace(/\bround\b/,"runde")
  .replace(/(\d+)\s*days?/,"$1 dage").replace(/\bday\b/,"dag");}

// Arcana Unleashed spells (Danish)
Object.assign(SDD,{"Aura of Evasion": "30-ft udstråling: du og allierede har fordel på DEX saves; ved en save der halverer skade tager du ingen ved succes og halv ved fejl. Uarbejdsdygtige (Incapacitated) væsener får ingen fordel.", "Battle Familiar": "Fremtryl en Celestial/Fey/Fiend-familiar (Brute, Flyer eller Stalker) med Battle Familiar-statblokken: Rend 1d8+3+spellets niveau kraftskade pr. angreb, halvt spell-niveau angreb. Eller styrk din Find Familiar-familiar (får Temp HP).", "Catnap": "Op til 3 villige væsener bliver Unconscious; slutter ved skade eller når de rystes. Hele varigheden giver en Short Rests fordele (én gang pr. Long Rest). +1 mål pr. slot over 3.", "Detonate": "CON save eller 10d10 ild (halv ved succes), derefter eksploderer en 60-ft udstråling fra målet: DEX save eller 10d10 ild (ulempe hvis målet faldt til 0 HP).", "Disruptive Tune": "20-ft kugle: CON save eller mist Concentration og få ulempe på CON saves for at holde Concentration i varigheden.", "Distorted Distance": "60-ft kugle. Vælg for hvert væsen: Dizzying Elongation (INT save eller 2d10 psykisk og vanskeligt terræn) eller Shortened Space (Speed +20 ft). Én gang pr. tur pr. væsen.", "Dueling Ground": "15-ft kugle med to udpegede villige duellister. Et mål der falder til 0 HP er Stable og teleporteres ud; øjeblikkelig-død-effekter efterlader det i stedet på 0 HP. Slutter hvis andre træder ind. +1 mål pr. slot over 2.", "Enervation": "DEX save eller 6d8 nekrotisk (halv og spell slutter ved succes); Bonus Action hver tur for 2d8 automatisk. Du får halvdelen af den nekrotiske skade i HP.", "Entrancing Mirrors": "Op til 3 væsener: INT save eller 7d6 psykisk og Stunned (halv ved succes); gentag save ved slutningen af hver tur.", "Festering Blast": "60-ft linje: CON save eller 4d10 nekrotisk og Poisoned; Poisoned væsener tager 2d10 gift ved starten af hver tur og gentager save ved turens slutning.", "Fractured Awareness": "INT save eller 12d10 psykisk og ulempe på D20 Tests (halv og spell slutter ved succes); gentag save ved slutningen af hver tur.", "Grave Ground": "Fire 10-ft felter med vanskeligt terræn: STR save eller 6d6 nekrotisk og -1d6 på skadeslag til slutningen af næste tur. Save ved indtræden/turens slutning der.", "Hindsight": "Se begivenheder inden for rækkevidde fra de seneste 10 år med ca. 1 dag pr. sekund; du kan sænke, pause, spole tilbage eller frem.", "Illusory Dragon": "Kæmpe skyggedrage (immun over for skade/tilstande): fjender WIS save eller Frightened. Bonus Action: flyt 60 ft; ånde 60-ft kegle INT save, 6d6 skade af valgt type.", "Inflict Doubt": "WIS save eller ulempe på D20 Tests; gentag save ved slutningen af hver tur.", "Invulnerability": "Du har immunitet over for al skade indtil spellet slutter.", "Iron Body": "Villigt væsen: Exhaustion kan ikke stige; resistens mod knusning, ild, stik, flæng; immunitet mod giftskade og Paralyzed, Petrified, Poisoned.", "Lightning Ring": "10-ft udstråling: CON save eller 3d6 lyn + 3d6 torden og Deafened (halv ved succes). Magic action: 60-ft linje, DEX save eller 6d6 lyn.", "Moment of Prescience": "Når du fejler en D20 Test eller et væsen rammer dig: gør dit slag til et 20, eller angrebsslaget til et 1.", "Mordenkainen's Lucubration": "Genskab op til to brugte spell slots af niveau 2 eller lavere (niveau 3 med en 6-7 slot, niveau 4 med en 8+ slot).", "Negative Energy Flood": "CON save eller 3d10+25 nekrotisk (halv ved succes); en Humanoid der dræbes rejser sig som Zombie. Et Undead-mål får i stedet 3d10 Temp HP.", "Power Word Pain": "6d8 kraftskade; har målet 100 HP eller færre er det også Charmed (Speed maks 10, ulempe på D20 Tests undtagen CON saves, spells kræver CON save). CON save hver tur afslutter det.", "Reweave Fate": "Når et væsen fejler en D20 Test: det slår om med fordel og skal bruge det nye slag; ved succes får det 6d10 Temp HP.", "Spirit Lantern": "Spøgelseslanterne, Dim Light 60 ft. Fjender der dør i nærheden giver sjælefragmenter (maks = spell-mod); Bonus Action: Drain Life (CON save, 4d8+mod nekrotisk), Repair Undead (4d8+mod HP) eller Ward Ally (angribere har ulempe).", "Summon Dinosaur": "Tilkald en Dinosaur Spirit (Ankylosaur, Triceratops eller Tyrannosaur): Huge, HP 60+10 pr. niveau over 6, halvt spell-niveau angreb (Bite/Gore/Slam, d10+5+spellets niveau).", "Summon Plant": "Tilkald en Plant Spirit (Fungus, Tree eller Vine): Large, HP 50+10 pr. niveau over 5, halvt spell-niveau angreb (Slam 1d10+3+niveau / Spore Spray 1d4+niveau gift).", "Transfix": "Ét væsen inden for 60 ft: WIS save eller Charmed og Incapacitated; det bevæger sig mod dig og tager 4d8 psykisk hvis det ender sin tur inden for 5 ft. Gentag save ved slutningen af hver tur.", "Uncertain Footing": "Op til 3 væsener: INT save eller Speed halveres og de kan ikke Dash; gentag save ved slutningen af hver tur.", "Nystul's Magic Aura": "Skjul et væsen eller objekt for Divination-magi, eller få det til at fremstå som en anden væsenstype/genstand (False Aura)."});
Object.assign(SDD,{"Vision of Elapsing Eons": "INT save eller 10d12 psykisk og Paralyzed; gentag save ved slutningen af hver tur, få 1 Exhaustion ved fejl og afslut spellet ved succes. Slutter tidligt hvis nogen inden for 5 ft ryster målet fri.", "Wail of the Banshee": "Op til 10 væsener: dem med 50 HP eller færre dør; andre laver et CON save eller tager 12d10 psykisk og er Deafened i 1 time (halv skade ved succes). Væsener der ikke kan høre dig er upåvirkede.", "Waves of Exhaustion": "Magic action: 60-ft kegle, CON save eller få 1 Exhaustion (kan ikke hæve det over niveau 4). Exhaustion fra spellet fjernes når det slutter.", "Wither and Bloom": "10-ft radius kugle: CON save eller 3d6 nekrotisk (halv ved succes); ikke-magiske planter visner. Ét væsen deri kan bruge en Hit Die og få slaget + spellcasting-mod i HP. +1d6 pr. slot over 2.", "Zone of Amicability": "60-ft udstråling: på ability checks for at påvirke et væsen i den behandles et d20-slag på 9 eller lavere som et 10."});
SDD["Entrancing Mirrors"]="Op til 3 væsener: INT save eller 7d6 psykisk og Stunned med halveret Speed (halv skade ved succes); gentag save ved slutningen af hver tur.";
SDD["Dueling Ground"]="15-ft kugle med to udpegede villige duellister. Et mål der falder til 0 HP er Stable og teleporteres ud; en øjeblikkelig-død-effekt efterlader det i stedet på 0 HP, Unconscious og Stable. Slutter hvis andre træder ind. +1 mål pr. slot over 2.";
SDD["Yolande's Regal Presence"]="10-ft udstråling af majestæt: WIS save eller 4d6 psykisk og Prone (du kan skubbe det 10 ft); halv skade ved succes.";
SDD["Summon Fey"]="Tilkald en fe-ånd som allieret (Fuming, Mirthful eller Tricksy stemning).";
SDD["Scrying"]="WIS save (modificeret af hvor godt du kender målet) eller du kan se og høre et valgt væsen på afstand.";
SDD["Dream"]="Send et drømmebud til et væsen du kender; gør du det skræmmende: WIS save eller væsenet får ingen gavn af hvilen og tager 3d6 psykisk når det vågner.";
// PHB 2024 spells added to SD after auditing every class's spell list against the book (see gameData.js).
SDD["Awaken"]="Et mål-Beast/Plant (INT 3 eller lavere) eller en naturlig plante får INT 10 og et sprog; en naturlig plante bliver også et Plant-væsen. Charmed i 30 dage eller til du/allierede skader det.";
SDD["Befuddlement"]="INT save eller 10d12 psykisk (halv ved succes) og kan ikke caste spells eller bruge Magic action; tvunget Dodge i kamp. Ekstra 1d8 nekrotisk når du skader det med et angreb eller spell. Gentager save hver 30. dag.";
SDD["Charm Monster"]="WIS save (fordel hvis det kæmper mod dig/allierede) eller Charmed indtil spellet slutter eller du/allierede skader det.";
SDD["Fount of Moonlight"]="Bright Light 20 ft/Dim 20 ft mere; Resistance mod Radiant; nærkampstræf giver ekstra 2d6 Radiant. Reaktion når du skades af et væsen inden for 60 ft: CON save eller det bliver Blinded til slutningen af din næste tur.";
SDD["Ice Knife"]="Afstandsangreb med magi: 1d10 gennemtrængende; derefter et DEX save eller 2d6 kulde til målet og hvert væsen inden for 5 ft.";
SDD["Mind Spike"]="WIS save eller 3d8 psykisk (halv ved succes); ved fejl kender du målets position til spellet slutter (kun samme plan), og Invisible giver det ingen fordel mod dig.";
SDD["Power Word Fortify"]="Styrk op til 6 væsener inden for rækkevidde med 120 midlertidige HP i alt, fordelt mellem dem.";
SDD["Rary's Telepathic Bond"]="Telepatisk forbindelse mellem op til 8 villige væsener inden for rækkevidde i varigheden, uanset fælles sprog.";
SDD["Synaptic Static"]="20-ft kugle: INT save eller 8d6 psykisk (halv ved succes) og -1d6 til angrebstjek, evnetjek og Concentration-saves i 1 minut.";
SDD["Tasha's Hideous Laughter"]="WIS save eller Prone og Incapacitated, med gentaget save hver tur eller når det tager skade.";
SDD["Tsunami"]="En mur af vand op til 300 ft lang/høj, 50 ft tyk; et fanget væsen tager stump skade, hvorefter muren bevæger sig 50 ft mod dig hver runde og svækkes indtil den ophører.";
SDD["Summon Aberration"]="Tilkald en Aberrant Spirit som allieret (Beholderkin-, Mind Flayer- eller Slaad-form).";
SDD["Summon Beast"]="Tilkald en Bestial Spirit som allieret (Air-, Land- eller Water-miljø).";
SDD["Summon Construct"]="Tilkald en Construct Spirit som allieret (Clay-, Metal- eller Stone-materiale).";
SDD["Summon Dragon"]="Tilkald en Draconic Spirit som allieret, der ligner en drage af din valgte åndevåben-skadetype.";
SDD["Summon Elemental"]="Tilkald en Elemental Spirit som allieret (Air, Earth, Fire eller Water).";
SDD["Summon Fiend"]="Tilkald en Fiendish Spirit som allieret (Demon-, Devil- eller Yugoloth-form).";
SDD["Summon Undead"]="Tilkald en Undead Spirit som allieret (Ghostly-, Putrid- eller Skeletal-form).";
SDD["Divine Smite"]="Lige efter et ramt Melee- eller Unarmed Strike-angreb: ekstra 2d8 Radiant-skade (+1d8 mod en Fiend eller Undead), +1d8 pr. spell slot-niveau over 1.";
SDD["Searing Smite"]="Lige efter et ramt nærkamps-/ubevæbnet angreb: ekstra 1d6 ild-skade; målet tager også 1d6 ild i starten af hver af sine ture, med et CON save hver gang for at afslutte det.";
SDD["Shining Smite"]="Lige efter et ramt nærkamps-/ubevæbnet angreb: ekstra 2d6 Radiant-skade; målet udstråler Bright Light 5 ft, angrebstjek mod det har Advantage, og det kan ikke få gavn af Invisible.";
SDD["Arcane Vigor"]="Slå 1-2 ubrugte livsterninger og genopret HP svarende til slaget plus dit spellcasting-modifier.";
SDD["Dragon's Breath"]="Rør et villigt væsen og vælg en skadetype; Magic action for at ånde en 15-ft kegle, DEX save for halv, 3d6 skade af den type.";
SDD["Arcane Lock"]="Lås magisk en dør, et vindue, en kiste eller lignende; du og valgte væsener kan åbne/lukke den frit, og du kan sætte en adgangskode.";
SDD["Drawmij's Instant Summons"]="Bind en safir til en genstand; knus senere safiren (eller sig genstandens navn via safiren) for at teleportere genstanden til din hånd.";
SDD["Magic Jar"]="Din sjæl forlader kroppen til en beholder; derfra kan du forsøge at besætte en Humanoid inden for 100 ft (CHA save) og kontrollere dens krop.";
SDD["Tasha's Bubbling Cauldron"]="Fremtryl en gryde der laver en valgt Common- eller Uncommon-potion; hent én som en bonus-handling, op til dit spellcasting-modifier (min. 1) i alt.";
SDD["Jallarzi's Storm of Radiance"]="10-ft radius, 40-ft cylinder: CON save eller 2d10 Radiant + 2d10 torden (halv ved succes); væsener deri bliver Blinded/Deafened og kan ikke caste Verbal-spells.";
SDD["Vitriolic Sphere"]="20-ft kugle: DEX save eller 10d4 syre (halv ved succes), derefter yderligere 5d4 syre ved slutningen af dets næste tur.";
SDD["Contact Other Plane"]="DC 15 INT save eller tag 6d6 psykisk skade og bliv Incapacitated i varigheden; ved succes kan du stille en oversanselig enhed op til 5 étordsspørgsmål.";
SDD["Tenser's Floating Disk"]="Skab en 3-ft skive af kraft der bærer op til 500 lb og følger dig inden for 20 ft.";
