// Danish spell descriptions (D&D 2024). Keyed by the English spell name (which stays the lookup key everywhere).
// Damage types: fire=ild, cold=kulde, lightning=lyn, thunder=torden, necrotic=nekrotisk, radiant=strålende,
// poison=gift, acid=syre, force=kraft, psychic=psykisk, piercing=stik, bludgeoning=knusning, slashing=flæng.
// "X save" -> "X save". advantage=fordel, disadvantage=ulempe.
export const SDD={
  "Fire Bolt":"Afstandsangreb med magi: 1d10 ild.",
  "Ray of Frost":"Ramt: 1d8 kulde, målets fart -10 ft.",
  "Shocking Grasp":"Fordel mod metalrustning. Ramt: 1d8 lyn, ingen reaktioner.",
  "Mage Hand":"Spøgelseshånd, op til 10 pund.",
  "Minor Illusion":"Lyd eller billede. INT-tjek for at gennemskue.",
  "Prestidigitation":"Små magiske tricks.",
  "Magic Missile":"3 pile, 1d4+1 kraft hver, rammer automatisk.",
  "Shield":"+5 AC. Immun over for Magic Missile.",
  "Mage Armor":"AC = 13+DEX for et væsen uden rustning.",
  "Burning Hands":"DEX save eller 3d6 ild.",
  "Charm Person":"WIS save eller charmeret.",
  "Sleep":"Væsener med 5d8 HP i alt falder i søvn.",
  "Thunderwave":"CON save eller 2d8 torden + skubbet 10 ft.",
  "Misty Step":"Teleportér op til 30 ft.",
  "Hold Person":"WIS save eller humanoide lammes.",
  "Invisibility":"Målet er usynligt indtil det angriber eller caster.",
  "Mirror Image":"3 kopier opsuger angreb.",
  "Scorching Ray":"3 stråler, 2d6 ild hver.",
  "Shatter":"CON save eller 3d8 torden.",
  "Suggestion":"WIS save eller følg en opfordring.",
  "Counterspell":"Afbryd en spell der bliver castet.",
  "Fireball":"20-ft radius. DEX save eller 8d6 ild.",
  "Fly":"Flyvefart 60 ft.",
  "Haste":"Dobbelt fart, +2 AC, ekstra handling.",
  "Lightning Bolt":"DEX save eller 8d6 lyn.",
  "Slow":"WIS save eller halv fart, -2 AC/DEX.",
  "Fear":"WIS save eller skræmt og flygter.",
  "Banishment":"CHA save eller forvist.",
  "Greater Invisibility":"Usynlig selv mens du angriber.",
  "Ice Storm":"20-ft radius, 2d8 knusning + 4d6 kulde.",
  "Polymorph":"WIS save eller forvandlet til et dyr.",
  "Confusion":"WIS save eller handl tilfældigt.",
  "Cone of Cold":"CON save eller 8d8 kulde.",
  "Hold Monster":"WIS save eller ethvert væsen lammes.",
  "Cloudkill":"20-ft giftig tåge, 5d8 gift pr. tur.",
  "Dominate Person":"WIS save eller kontrollér en humanoid.",
  "Sacred Flame":"DEX save eller 1d8 strålende. Skalerer ved 5/11/17.",
  "Guidance":"Ingen koncentration. +1d4 til ét evnetjek.",
  "Light":"Genstand udsender skarpt lys 20 ft.",
  "Thaumaturgy":"Mindre vidundereffekt.",
  "Toll the Dead":"WIS save eller 1d8 (1d12 hvis såret) nekrotisk.",
  "Bless":"3 væsener lægger 1d4 til angreb/saves.",
  "Command":"WIS save eller ét-ords kommando.",
  "Cure Wounds":"Genopret 2d8+mod HP.",
  "Guiding Bolt":"4d6 strålende, næste angreb har fordel.",
  "Healing Word":"Genopret 2d4+mod HP.",
  "Inflict Wounds":"Nærkampsangreb med magi: 3d10 nekrotisk.",
  "Shield of Faith":"+2 AC.",
  "Aid":"3 væsener får +5 maks HP.",
  "Lesser Restoration":"Fjern én tilstand eller sygdom.",
  "Prayer of Healing":"6 væsener får 2d8+mod HP tilbage.",
  "Spiritual Weapon":"Spøgelsesvåben: 1d8+mod kraft pr. tur.",
  "Animate Dead":"Skab en udød tjener.",
  "Daylight":"60-ft radius med skarpt lys.",
  "Dispel Magic":"Afslut én spell af 3. niveau eller lavere.",
  "Spirit Guardians":"WIS save eller 3d8 strålende/nekrotisk.",
  "Remove Curse":"Fjern alle forbandelser på målet.",
  "Death Ward":"Falder til 1 HP i stedet for 0, én gang.",
  "Freedom of Movement":"Ignorér vanskeligt terræn og fastholdelse.",
  "Guardian of Faith":"20 strålende til fjender inden for 10 ft.",
  "Flame Strike":"DEX save eller 4d6 ild + 4d6 strålende.",
  "Greater Restoration":"Fjern en alvorlig tilstand eller forbandelse.",
  "Mass Cure Wounds":"6 væsener får 3d8+mod HP tilbage.",
  "Raise Dead":"Bring et dødt væsen til live (500 gp diamant).",
  "Druidcraft":"Mindre natureffekt.",
  "Produce Flame":"Flamme: lys eller kast for 1d8 ild.",
  "Shillelagh":"Ingen koncentration. Våben bruger WIS, skade 1d8+WIS.",
  "Thorn Whip":"1d6 stik, træk 10 ft.",
  "Animal Friendship":"WIS save eller dyret charmeres.",
  "Entangle":"STR save eller fastholdt af planter.",
  "Faerie Fire":"DEX save eller markeret; angreb har fordel.",
  "Goodberry":"10 bær, hvert giver 1 HP.",
  "Barkskin":"Ingen koncentration. AC 17.",
  "Flaming Sphere":"2d6 ildkugle, flyt med bonus-handling.",
  "Moonbeam":"CON save eller 2d10 strålende pr. tur.",
  "Pass without Trace":"+10 Stealth til dig og 10 ledsagere.",
  "Spike Growth":"2d4 stik pr. 5 ft bevæget.",
  "Call Lightning":"DEX save eller 3d10 lyn pr. tur.",
  "Conjure Animals":"Fremkald dyr med samlet CR 2.",
  "Plant Growth":"100-ft radius vanskeligt terræn.",
  "Blight":"CON save eller 8d8 nekrotisk.",
  "Insect Plague":"CON save eller 4d10 stik pr. tur.",
  "Vicious Mockery":"WIS save eller 1d6 psykisk (skalerer 2d6/3d6/4d6), ulempe på næste angreb.",
  "Dancing Lights":"4 svævende lys.",
  "Eldritch Blast":"1d10 kraftstråle. Ramt væsen kan skubbes 10 ft. Flere stråler ved højere niveauer.",
  "Chill Touch":"1d8 nekrotisk, målet kan ikke få HP tilbage.",
  "Armor of Agathys":"5 midlertidige HP; angriber tager 5 kulde.",
  "Arms of Hadar":"STR save eller 2d6 nekrotisk, ingen reaktioner.",
  "Hex":"+1d6 nekrotisk på våben- og magiangreb.",
  "Hellish Rebuke":"DEX save eller 2d10 ild.",
  "Witch Bolt":"1d12 lyn, oprethold for 1d12 pr. tur.",
  "Darkness":"15-ft magisk mørke.",
  "Vampiric Touch":"3d6 nekrotisk; få halvdelen som HP.",
  "Hunger of Hadar":"20-ft mørketomrum: 2d6 kulde + 2d6 syre.",
  "Divine Favor":"+1d4 strålende på våbentræf.",
  "Find Steed":"Fremkald et åndeligt ridedyr.",
  "Aura of Vitality":"Bonus-handling: genopret 2d6 HP til ét væsen.",
  "Revivify":"Bring en (død i 1 min) til live (300 gp diamant).",
  "Hunter's Mark":"+1d6 på våbentræf mod målet.",
  "Fog Cloud":"20-ft kugle af tæt tåge.",
  "Ensnaring Strike":"STR save eller fastholdt; 1d6 stik pr. tur.",
  "Conjure Barrage":"DEX save eller 3d8 skade af våbentype.",
  "Swift Quiver":"Koggeret laver ammunition; 2 afstandsangreb pr. bonus-handling.",
  "Wind Wall":"Vind-mur; 3d8 knusning.",
  "Silence":"20-ft kugle af magisk stilhed.",
  "Hypnotic Pattern":"WIS save eller ude af stand til at handle.",
  "Major Image":"20-ft illusion med lyd og lugt.",
  "Sending":"25-ords besked til et kendt væsen.",
  "Dissonant Whispers":"WIS save eller 3d6 psykisk, må flygte.",
  "Heroism":"Immun over for skræmt; midlertidige HP hver tur.",
  "Enthrall":"WIS save eller distraheret af dig.",
  "Compulsion":"WIS save eller må bevæge sig i valgt retning.",
  "Dimension Door":"Teleportér dig selv + ét væsen op til 500 ft.",
  "Hallucinatory Terrain":"Terræn ser ud som en anden terræntype.",
  "Compelled Duel":"WIS save eller må kun kæmpe mod dig.",
  "Thunderous Smite":"+2d6 torden, STR save eller liggende.",
  "Wrathful Smite":"+1d6 psykisk, WIS save eller skræmt.",
  "Branding Smite":"+2d6 strålende, målet kan ikke være usynligt.",
  "Crusader's Mantle":"Allierede inden for 30 ft laver +1d4 strålende.",
  "Elemental Weapon":"+1 våben, +1d4 energiskade.",
  "Blinding Smite":"+3d8 strålende, CON save eller blindet.",
  "Staggering Smite":"+4d6 psykisk, WIS save eller ulempe.",
  "Holy Weapon":"+2d8 strålende ved træf.",
  "Hail of Thorns":"DEX save eller 1d10 stik i 5-ft område.",
  "Speak with Animals":"Tal med dyr.",
  "Lightning Arrow":"Næste afstandstræf: 4d8 lyn.",
  "Steel Wind Strike":"5 mål: 6d10 kraft hver.",
  "Cordon of Arrows":"4 pile; DEX save eller 1d6 stik hver.",
  "Conjure Volley":"40-ft cylinder: DEX save eller 8d8 skade.",
  "Conjure Woodland Beings":"Fremkald fevæsener.",
  "Grasping Vine":"2d6 knusning, træk 20 ft.",
  "Tree Stride":"Teleportér mellem træer af samme art.",
  "Commune with Nature":"Lær 3 fakta om nærliggende terræn.",
  "Speak with Plants":"Tal med planter.",
  "Dominate Beast":"WIS save eller kontrollér et dyr.",
  "Giant Insect":"Insekter bliver til kæmpeversioner.",
  "Antilife Shell":"Barriere forhindrer levende væsener i at komme ind.",
  "Reincarnate":"Genskab et dødt væsen i en ny krop.",
  "Animal Shapes":"Villige væsener bliver til dyr CR 4 eller lavere.",
  "Earth Tremor":"DEX save eller 1d6 knusning og liggende.",
  "Bane":"CHA save eller -1d4 til angreb/saves.",
  "Create or Destroy Water":"Skab eller ødelæg 10 liter vand.",
  "Detect Evil and Good":"Mærk djævle, udøde, himmelske inden for 30 ft.",
  "Detect Magic":"Mærk magi inden for 30 ft.",
  "Detect Poison and Disease":"Mærk gift og sygdom inden for 30 ft.",
  "Purify Food and Drink":"Rens mad og drikke i en 5-ft kugle.",
  "Sanctuary":"WIS save eller angribere må vælge nyt mål.",
  "Augury":"Held/uheld for en handling inden for 30 min.",
  "Calm Emotions":"Undertryk charme/frygt eller følelser.",
  "Enhance Ability":"Fordel på én slags evnetjek.",
  "Find Traps":"Mærk fælder i synslinjen.",
  "Locate Animals or Plants":"Mærk nærmeste navngivne dyr eller plante inden for 5 mil.",
  "Protection from Poison":"Fordel mod gift, modstand mod giftskade.",
  "Warding Bond":"+1 AC/saves, modstand; du deler den skade der tages.",
  "Zone of Truth":"CHA save eller kan ikke lyve i en 15-ft kugle.",
  "Beacon of Hope":"Fordel på WIS saves og death saves.",
  "Create Food and Water":"Skab 20 kg mad og 115 liter vand.",
  "Mass Healing Word":"6 væsener får 1d4+mod HP tilbage.",
  "Meld into Stone":"Træd ind i en stengenstand.",
  "Speak with Dead":"Stil et lig 5 spørgsmål.",
  "Water Walk":"Gå på væske som var det fast.",
  "Divination":"Sandfærdigt svar om en begivenhed inden for 7 dage.",
  "Commune":"Stil en gud 3 ja/nej-spørgsmål.",
  "Contagion":"3 fejlede CON saves = syg.",
  "Dispel Evil and Good":"Djævle/udøde/feer har ulempe når de angriber dig.",
  "Hallow":"60-ft radius helliget grund.",
  "Summon Celestial":"Fremkald en lydig himmelsk ånd.",
  "Animal Messenger":"Lille dyr leverer en 25-ords besked.",
  "Beast Sense":"Se og hør gennem et dyr.",
  "Flame Blade":"Ild-scimitar: 3d6 ild.",
  "Gust of Wind":"60-ft vindlinje skubber 15 ft.",
  "Heat Metal":"Metal gløder: 2d8 ild, CON save eller tab det.",
  "Locate Object":"Mærk retning til en kendt genstand inden for 1000 ft.",
  "Locate Creature":"Mærk retning til et kendt væsen inden for 1000 ft.",
  "Conjure Minor Elementals":"Fremkald elementarer CR 2 eller lavere.",
  "Banishing Smite":"+5d10 kraft; under 50 HP = forvist.",
  "Circle of Power":"Allierede har fordel på magic saves.",
  "Destructive Wave":"CON save eller 5d6 torden + 5d6 strålende, liggende.",
  "Aura of Life":"Nekrotisk modstand; væsener på 0 HP får 1 HP pr. tur.",
  "Aura of Purity":"Allierede er immune over for sygdom, modstår gift.",
  "Geas":"WIS save eller følg kommando; 5d10 psykisk pr. dag ved brud.",
  "Control Water":"Oversvøm, del, omdirigér eller lav malstrøm i en 100-ft terning vand.",
  "Animate Objects":"Bring op til 10 små eller mindre genstande til live.",
  "Conjure Elemental":"Fremkald en elementar CR 5 eller lavere.",
  "Bigby's Hand":"Krafthånd: slå 4d8, skub eller grib.",
  "Teleportation Circle":"Portal til en permanent teleportationscirkel.",
  "Wall of Force":"Usynlig uforgængelig kraftmur.",
  "Wall of Stone":"Ikke-magisk stenmur; kan blive permanent.",
  "Chain Lightning":"4d8 lyn springer til 4 mål.",
  "Circle of Death":"CON save eller 8d6 nekrotisk i en 60-ft kugle.",
  "Disintegrate":"DEX save eller 10d6+40 kraft; 0 HP = støv.",
  "Eyebite":"WIS save eller sovende/panisk/kvalm.",
  "Globe of Invulnerability":"Spells af 5. niveau og lavere kan ikke komme ind.",
  "Mass Suggestion":"WIS save eller 12 væsener følger en opfordring.",
  "Sunbeam":"CON save eller 6d8 strålende og blindet.",
  "True Seeing":"Se gennem illusioner og usynlighed.",
  "Delayed Blast Fireball":"Vokser hver runde; DEX save eller 12d6 ild.",
  "Etherealness":"Træd ind i Æterplanet.",
  "Finger of Death":"CON save eller 7d8+30 nekrotisk; rejser sig som zombie.",
  "Forcecage":"Uundslippeligt 20-ft kraftbur.",
  "Teleport":"Transportér op til 9 væsener til et kendt sted.",
  "Dominate Monster":"WIS save eller kontrollér ethvert væsen.",
  "Feeblemind":"INT save eller INT og CHA falder til 1.",
  "Incendiary Cloud":"DEX save eller 10d8 ild pr. tur.",
  "Maze":"Forvis til en labyrint; DC 20 INT for at undslippe.",
  "Mind Blank":"Immun over for psykisk skade og spådom.",
  "Power Word Stun":"150 HP eller mindre: lammet indtil CON save.",
  "Sunburst":"CON save eller 12d6 strålende og blindet.",
  "Foresight":"Kan ikke overraskes. Fordel på alt.",
  "Gate":"Portal til et andet plan; fremkald et bestemt væsen.",
  "Meteor Swarm":"4 meteorer: DEX save eller 20d6 ild + 20d6 knusning.",
  "Power Word Kill":"100 HP eller mindre: øjeblikkelig død, ingen save.",
  "Wish":"Den mægtigste spell. Efterlign enhver spell af 8. niveau eller lavere, eller ønsk.",
  "Weird":"WIS save eller skræmt; 4d10 psykisk pr. tur.",
  "Time Stop":"Tag 1d4+1 ture mens tiden står stille.",
  "True Polymorph":"WIS save eller forvandl væsen eller genstand.",
  "Shapechange":"Forvandl til ethvert set væsen med CR lig med niveau eller lavere.",
  "Astral Projection":"Projicér op til 9 villige væsener ind i Astralplanet.",
  "Imprisonment":"WIS save eller væsenet fængsles.",
  "Prismatic Wall":"7-lags flerfarvet mur med forskellige effekter.",
  "Acid Splash":"1d6 syre mod ét eller to væsener.",
  "Blade Ward":"Modstand mod våbenskade.",
  "Friends":"Fordel på CHA-tjek mod ét væsen.",
  "Mending":"Reparér et brud eller en flænge i en genstand.",
  "Message":"Hvisk til et væsen; det kan svare.",
  "Poison Spray":"CON save eller 1d12 gift.",
  "True Strike":"Lav ét angreb med fordel med din magi-evne.",
  "Thunderclap":"CON save eller 1d6 torden.",
  "Alarm":"Alarm mod indtrængen i en 20-ft terning.",
  "Chromatic Orb":"3d8 af en valgt energitype.",
  "Color Spray":"Væsener med 6d10 HP i alt blindes.",
  "Comprehend Languages":"Forstå ethvert talt eller skrevet sprog.",
  "Disguise Self":"Skift dit udseende.",
  "Expeditious Retreat":"Bonus-handling Dash hver tur.",
  "False Life":"1d4+4 midlertidige HP.",
  "Feather Fall":"5 væsener tager ingen faldskade.",
  "Find Familiar":"Få en familiar i dyreform.",
  "Grease":"DEX save eller fald ned; vanskeligt terræn.",
  "Hideous Laughter":"WIS save eller ude af stand til at handle af grin.",
  "Identify":"Lær en magisk genstands egenskaber.",
  "Illusory Script":"Skjult besked som kun tiltænkte læsere kan se.",
  "Jump":"Tredobl springafstand.",
  "Longstrider":"+10 ft fart.",
  "Protection from Evil and Good":"Beskyttet mod aberrationer, djævle, udøde.",
  "Ray of Sickness":"2d8 gift; CON save eller forgiftet.",
  "Silent Image":"Visuel illusion op til en 15-ft terning.",
  "Unseen Servant":"Usynlig kraft udfører simple opgaver.",
  "Alter Self":"Skift udseende, ånd under vand eller få våben.",
  "Blindness/Deafness":"CON save eller blindet/døv.",
  "Blur":"Angreb mod dig har ulempe.",
  "Cloud of Daggers":"4d4 flæng i en 5-ft terning hver tur.",
  "Continual Flame":"Permanent flammelignende glød.",
  "Crown of Madness":"WIS save eller angriber et tilfældigt væsen.",
  "Darkvision":"Mørkesyn 60 ft.",
  "Detect Thoughts":"Læs overfladetanker hos væsener inden for 30 ft.",
  "Enlarge/Reduce":"Fordobl eller halvér størrelse; +/-1d4 skade.",
  "Gentle Repose":"Bevar lig; forlæng grænsen for Raise Dead.",
  "Knock":"Åbn en låst/fastklemt/barrikaderet genstand.",
  "Levitate":"Målet stiger op til 20 ft.",
  "Magic Mouth":"25-ords besked udløses på en betingelse.",
  "Magic Weapon":"Våben bliver +1 magisk.",
  "Melf's Acid Arrow":"4d4 syre nu + 2d4 næste tur.",
  "Phantasmal Force":"INT save eller opfat illusion som virkelig: 1d6 psykisk pr. tur.",
  "Ray of Enfeeblement":"CON save eller halv skade med STR-angreb.",
  "Rope Trick":"Ekstradimensionelt rum for enden af et reb.",
  "See Invisibility":"Se usynlige væsener og genstande.",
  "Spider Climb":"Klatr på enhver overflade, også lofter.",
  "Web":"DEX save eller fastholdt i spind.",
  "Bestow Curse":"WIS save eller forbandet med forskellige straffe.",
  "Blink":"d20 11+: skift til Æteren til næste tur.",
  "Clairvoyance":"Usynlig sensor; se eller hør gennem den.",
  "Feign Death":"Fremstå død; modstand mod al skade undtagen psykisk.",
  "Gaseous Form":"Tågesky, flyv 10 ft, modstå ikke-magisk skade.",
  "Glyph of Warding":"Rune udløser en spell eller 5d8 eksplosion.",
  "Nondetection":"Kan ikke rammes af spådom eller skrying.",
  "Protection from Energy":"Modstand mod én energitype.",
  "Sleet Storm":"DEX save eller liggende; vanskeligt terræn.",
  "Stinking Cloud":"CON save eller spild handling på at brække sig.",
  "Tongues":"Forstå og tal ethvert sprog.",
  "Water Breathing":"10 væsener kan ånde under vand.",
  "Arcane Eye":"Usynligt magisk øje; mørkesyn 30 ft.",
  "Evard's Black Tentacles":"DEX save eller fastholdt + 3d6 knusning pr. tur.",
  "Fabricate":"Forvandl råmaterialer til et produkt.",
  "Fire Shield":"Modstå ild eller kulde; angribere tager 2d8.",
  "Leomund's Secret Chest":"Skjul en kiste på Æterplanet.",
  "Mordenkainen's Faithful Hound":"Usynlig vagthund; 4d8 stikangreb.",
  "Mordenkainen's Private Sanctum":"Blokér teleportation, skrying og lyd.",
  "Otiluke's Resilient Sphere":"DEX save eller lukket inde i en kraftkugle.",
  "Phantasmal Killer":"WIS save eller skræmt; 4d10 psykisk pr. tur.",
  "Stone Shape":"Form mellemstor sten til enhver form.",
  "Stoneskin":"Modstand mod ikke-magisk våbenskade.",
  "Wall of Fire":"5d8 ild til væsener inden for 10 ft.",
  "Creation":"Skab en ikke-levende genstand af skyggestof.",
  "Legend Lore":"Lær viden om en legendarisk person/sted/genstand.",
  "Mislead":"Bliv usynlig; skab en styrbar dobbeltgænger.",
  "Modify Memory":"WIS save eller ændr 10 min af minder.",
  "Passwall":"Passage gennem en mur op til 20 ft dyb.",
  "Planar Binding":"CHA save eller himmelsk/djævel/fe tjener dig.",
  "Seeming":"Skift udseende på et vilkårligt antal væsener.",
  "Telekinesis":"Flyt væsener eller genstande op til 500 kg.",
  "Arcane Gate":"Forbind to portaler op til 500 ft fra hinanden.",
  "Contingency":"Forbered en spell til at udløse automatisk.",
  "Create Undead":"Skab 3 ghouls fra lig.",
  "Flesh to Stone":"CON save eller forstenet efter 3 fejl.",
  "Guards and Wards":"Magisk bygningsforsvar.",
  "Move Earth":"Omform en 40-ft terning af jord/sand/ler.",
  "Otiluke's Freezing Sphere":"CON save eller 10d6 kulde i en 60-ft radius.",
  "Otto's Irresistible Dance":"WIS save eller må danse: -2 AC, ingen bevægelse.",
  "Programmed Illusion":"Illusion aktiveres ved en udløser.",
  "Wall of Ice":"CON save eller 10d6 kulde ved skabelse.",
  "Mirage Arcane":"1-mils firkantet terrænillusion.",
  "Mordenkainen's Magnificent Mansion":"Ekstradimensionel bolig.",
  "Mordenkainen's Sword":"Svævende sværd: 3d10 kraft på kommando.",
  "Plane Shift":"Transportér op til 9 væsener til et andet plan.",
  "Prismatic Spray":"8 farvede stråler med forskellige effekter.",
  "Project Image":"Illusorisk dobbeltgænger du kan sanse gennem.",
  "Reverse Gravity":"Genstande falder opad i en 50-ft radius.",
  "Symbol":"Skadelig rune udløses på en betingelse.",
  "Heal":"Genopret 70 HP og fjern blindhed/døvhed/sygdom.",
  "Harm":"CON save eller 14d6 nekrotisk; sænker maks HP.",
  "Heroes' Feast":"12 væsener: immun over for gift/frygt, +2d10 maks HP.",
  "Planar Ally":"Guden sender en himmelsk/elementar/djævel.",
  "Word of Recall":"5 væsener teleporterer til et fristed.",
  "Conjure Celestial":"Fremkald en himmelsk CR 4 eller lavere.",
  "Divine Word":"Effekter baseret på væsenets HP.",
  "Fire Storm":"DEX save eller 7d10 ild i 10 terninger.",
  "Regenerate":"4d8+15 HP nu; genvækst af lemmer; 1 HP pr. runde.",
  "Resurrection":"Bring en (død i 100 år) til live (1000 gp diamant).",
  "Antimagic Field":"10-ft kugle hvor magi svigter.",
  "Control Weather":"Styr vejret i et 5-mils område.",
  "Earthquake":"100-ft radius voldsom rysten.",
  "Holy Aura":"Allierede har fordel på alle saves; fjender ulempe når de angriber dem.",
  "Mass Heal":"Fordel 700 HP blandt væsener.",
  "True Resurrection":"Bring en (død i 200 år) til live, selv uden krop.",
  "Antipathy/Sympathy":"Genstand frastøder eller tiltrækker en væsentype.",
  "Storm of Vengeance":"Kæmpe storm: lyn, syre, hagl hver runde.",
  "Conjure Fey":"Fremkald et fevæsen CR 6 eller lavere.",
  "Transport via Plants":"Forbind to store+ planter på samme plan.",
  "Wall of Thorns":"7d8 stik for at komme igennem.",
  "Wind Walk":"10 væsener bliver gasformige, flyv 300 ft.",
  "Glibness":"CHA-tjek behandler slag på 9 eller lavere som 10.",
  "Power Word Heal":"Genopret alle HP; fjern tilstande.",
  "Find the Path":"Kend den korteste vej til et sted.",
  "Forbiddance":"Beskyt et område mod planrejser.",
  "Blade Barrier":"DEX save eller 6d10 flæng for at komme igennem.",
  "Leomund's Tiny Hut":"10-ft kuppel-ly for 9 væsener.",
  "Magic Circle":"Barriere der holder en væsentype ude eller inde.",
  "Phantom Steed":"Halvvirkeligt ridedyr, fart 100 ft.",
};

// Reusable metadata translators (cover school / casting time / range / duration for every spell).
const SCHOOL_DA={Abjuration:"Afværgelse",Conjuration:"Fremkaldelse",Divination:"Spådom",Enchantment:"Fortryllelse",Evocation:"Besværgelse",Illusion:"Illusion",Necromancy:"Nekromanti",Transmutation:"Transmutation"};
export function trSchool(s){return SCHOOL_DA[s]||s;}
export function trCast(s){if(!s)return s;return s
  .replace("1 bonus action","1 bonus-handling")
  .replace("1 action","1 handling")
  .replace("1 reaction","1 reaktion")
  .replace(/(\d+)\s*hours?/,"$1 timer").replace("1 hour","1 time")
  .replace(/(\d+)\s*minutes?/,"$1 minutter").replace("1 min","1 min")
  .replace("(ritual)","(ritual)");}
export function trRange(s){if(!s)return s;return s
  .replace("Self","Selv").replace("Touch","Berøring").replace("Sight","Syn").replace("Unlimited","Ubegrænset")
  .replace("cone","kegle").replace("line","linje").replace("cube","terning").replace("radius","radius")
  .replace(/(\d+)\s*miles?/,"$1 mil").replace("mile","mil");}
export function trDur(s){if(!s)return s;return s
  .replace("Instant","Øjeblikkelig").replace("Special","Speciel")
  .replace("Until cured","Indtil helbredt").replace("Until dispelled","Indtil ophævet").replace("Until triggered","Indtil udløst")
  .replace("Concentration","Koncentration").replace("Conc.","Konc.")
  .replace("Up to","Op til")
  .replace(/(\d+)\s*hours?/,"$1 timer").replace(/\bhr\b/,"time").replace(/\bhour\b/,"time")
  .replace(/(\d+)\s*minutes?/,"$1 minutter").replace(/\bmin\b/,"min")
  .replace(/(\d+)\s*rounds?/,"$1 runder").replace(/\bround\b/,"runde")
  .replace(/(\d+)\s*days?/,"$1 dage").replace(/\bday\b/,"dag");}
